export type RefundAutoConfidenceBucket =
    | 'AUTO_REFUND_EXACT_TITLE'
    | 'AUTO_REFUND_LOCALIZED_REFUND_TITLE'
    | 'AUTO_REFUND_REJECTED_PAYMENT_PRINCIPAL_TITLE'
    | 'AUTO_REFUND_REJECTED_PAYMENT_FEE_TITLE';
