export type TransferPairAutoConfidenceBucket =
    | 'AUTO_IBAN_AMOUNT'
    | 'AUTO_SAME_CURRENCY_AMOUNT'
    | 'AUTO_CROSS_CURRENCY_OPERATION'
    | 'AUTO_CROSS_CURRENCY_IMPLIED_RATE'
    | 'AUTO_SAME_BANK_HINTED_FEE';
