export enum AiSystemStateEnum {
    DISABLED = 'DISABLED',
    BOOTING = 'BOOTING',
    SUSPENDED = 'SUSPENDED',
    TRANSLATING = 'TRANSLATING',
    INDEXING = 'INDEXING',
    BOOSTING = 'BOOSTING',
    READY = 'READY',
    ERROR = 'ERROR'
}
