import { msg } from '@lingui/core/macro';

import type { MessageDescriptor } from '@lingui/core';

export const DEFAULT_CATEGORY_TITLE: Record<number, MessageDescriptor> = {
    1: msg`Currency Purchase`,
    2: msg`Currency Sale`,
    3: msg`Crypto Purchase`,
    4: msg`Crypto Sale`,
    5: msg`Stock Purchase`,
    6: msg`Stock Sale`,
    7: msg`Currency Transfer`,
    8: msg`Crypto Transfer`,
    9: msg`Stock Transfer`,
    10: msg`Housing & Utilities`,
    11: msg`Groceries`,
    12: msg`Restaurants & Cafes`,
    13: msg`Transportation`,
    14: msg`Car & Fuel`,
    15: msg`Health & Medical`,
    16: msg`Insurance`,
    17: msg`Debt Payments`,
    18: msg`Savings`,
    19: msg`Investments`,
    20: msg`Salary & Wages`,
    21: msg`Freelance & Side Hustle`,
    22: msg`Shopping`,
    23: msg`Subscriptions`,
    24: msg`Entertainment`,
    25: msg`Education`,
    26: msg`Gifts & Donations`,
    27: msg`Family & Kids`,
    28: msg`Pets`,
    29: msg`Travel`,
    30: msg`Business Expenses`,
    31: msg`Taxes`,
    32: msg`Bank Fees & Charges`,
    33: msg`Home Maintenance`,
    34: msg`Personal Care`,
    35: msg`Electronics & Gadgets`,
    36: msg`Sport & Fitness`,
    37: msg`Clothing & Accessories`,
    38: msg`Other`,
    39: msg`Emergency Fund`
};
