// Generated by scripts/generate-icons-constant.ts. Do not edit.
import { UserIconNameEnum } from '@budgie/contracts';

import { ICON_IMPORTS_CHUNK_1 } from './icons/icons-a-arrow-down.constant';
import { ICON_IMPORTS_CHUNK_2 } from './icons/icons-cable.constant';
import { ICON_IMPORTS_CHUNK_3 } from './icons/icons-crown.constant';
import { ICON_IMPORTS_CHUNK_4 } from './icons/icons-glasses.constant';
import { ICON_IMPORTS_CHUNK_5 } from './icons/icons-mic.constant';
import { ICON_IMPORTS_CHUNK_6 } from './icons/icons-router.constant';
import { ICON_IMPORTS_CHUNK_7 } from './icons/icons-tally-2.constant';

import type { LucideIconModuleInterface } from '../interface/lucide-icon-module.interface';

export const ICON_IMPORTS: Partial<Record<UserIconNameEnum, () => Promise<LucideIconModuleInterface>>> = {
    ...ICON_IMPORTS_CHUNK_1,
    ...ICON_IMPORTS_CHUNK_2,
    ...ICON_IMPORTS_CHUNK_3,
    ...ICON_IMPORTS_CHUNK_4,
    ...ICON_IMPORTS_CHUNK_5,
    ...ICON_IMPORTS_CHUNK_6,
    ...ICON_IMPORTS_CHUNK_7
};
