// Generated by scripts/generate-icons-constant.ts. Do not edit.
import { UserIconNameEnum } from '@budgie/contracts';

import { ICON_IMPORTS_CHUNK_1 } from './icons/icons-aarrow-down.constant';
import { ICON_IMPORTS_CHUNK_2 } from './icons/icons-brick-wall-shield.constant';
import { ICON_IMPORTS_CHUNK_3 } from './icons/icons-cloudy.constant';
import { ICON_IMPORTS_CHUNK_4 } from './icons/icons-flower2.constant';
import { ICON_IMPORTS_CHUNK_5 } from './icons/icons-library.constant';
import { ICON_IMPORTS_CHUNK_6 } from './icons/icons-palette.constant';
import { ICON_IMPORTS_CHUNK_7 } from './icons/icons-shield-cog.constant';
import { ICON_IMPORTS_CHUNK_8 } from './icons/icons-thumbs-down.constant';

import type { ReiconModuleInterface } from '../interface/reicon-module.interface';

export const ICON_IMPORTS: Partial<Record<UserIconNameEnum, () => Promise<ReiconModuleInterface>>> = {
    ...ICON_IMPORTS_CHUNK_1,
    ...ICON_IMPORTS_CHUNK_2,
    ...ICON_IMPORTS_CHUNK_3,
    ...ICON_IMPORTS_CHUNK_4,
    ...ICON_IMPORTS_CHUNK_5,
    ...ICON_IMPORTS_CHUNK_6,
    ...ICON_IMPORTS_CHUNK_7,
    ...ICON_IMPORTS_CHUNK_8
};
