/* eslint-disable max-lines,lingui/no-unlocalized-strings */
import { UserIconNameEnum } from '@budgie/contracts';

export const USER_ICON_TAGS: Record<UserIconNameEnum | string, string[]> = {
    [UserIconNameEnum.Activity]: ['pulse', 'health', 'fitness', 'heart', 'monitor', 'medical'],
    [UserIconNameEnum.Airplay]: ['stream', 'cast', 'screen', 'mirror'],
    [UserIconNameEnum.AlarmClock]: ['time', 'wake', 'morning', 'reminder'],
    [UserIconNameEnum.Archive]: ['storage', 'box', 'save', 'backup'],
    [UserIconNameEnum.ArrowDownUp]: ['sort', 'swap', 'exchange'],
    [UserIconNameEnum.ArrowLeftRight]: ['swap', 'exchange', 'transfer'],
    [UserIconNameEnum.ArrowRightLeft]: ['swap', 'exchange', 'transfer'],
    [UserIconNameEnum.ArrowUpDown]: ['sort', 'swap', 'exchange'],
    [UserIconNameEnum.Baby]: ['child', 'infant', 'kid', 'family', 'newborn', 'parenting'],
    [UserIconNameEnum.Backpack]: ['bag', 'school', 'travel', 'hiking', 'student'],
    [UserIconNameEnum.Banknote]: ['money', 'cash', 'bill', 'currency', 'payment', 'salary', 'income'],
    [UserIconNameEnum.Bath]: ['bathroom', 'shower', 'wash', 'hygiene', 'home'],
    [UserIconNameEnum.BatteryCharging]: ['power', 'energy', 'charge', 'electric'],
    [UserIconNameEnum.Bed]: ['sleep', 'bedroom', 'rest', 'hotel', 'accommodation', 'furniture'],
    [UserIconNameEnum.Beer]: ['drink', 'alcohol', 'bar', 'pub', 'beverage', 'party'],
    [UserIconNameEnum.Bike]: ['bicycle', 'cycling', 'transport', 'exercise', 'sport'],
    [UserIconNameEnum.Bitcoin]: ['crypto', 'cryptocurrency', 'digital', 'blockchain', 'btc'],
    [UserIconNameEnum.Blinds]: ['window', 'curtain', 'home', 'interior'],
    [UserIconNameEnum.Book]: ['reading', 'education', 'library', 'study', 'literature'],
    [UserIconNameEnum.BookOpen]: ['reading', 'education', 'library', 'study', 'literature'],
    [UserIconNameEnum.Briefcase]: ['work', 'job', 'business', 'career', 'office', 'professional'],
    [UserIconNameEnum.Building]: ['office', 'company', 'corporate', 'business', 'apartment'],
    [UserIconNameEnum.Building2]: ['office', 'company', 'corporate', 'business', 'apartment', 'bank'],
    [UserIconNameEnum.Bus]: ['transport', 'public', 'travel', 'commute', 'transit'],
    [UserIconNameEnum.Cable]: ['wire', 'connection', 'internet', 'tech'],
    [UserIconNameEnum.Cake]: ['birthday', 'celebration', 'party', 'dessert', 'bakery'],
    [UserIconNameEnum.Calculator]: ['math', 'finance', 'accounting', 'numbers'],
    [UserIconNameEnum.Calendar]: ['date', 'schedule', 'event', 'appointment', 'planner'],
    [UserIconNameEnum.Calendar1]: ['date', 'schedule', 'event', 'appointment', 'planner'],
    [UserIconNameEnum.CalendarDays]: ['date', 'schedule', 'event', 'appointment', 'planner'],
    [UserIconNameEnum.Camera]: ['photo', 'photography', 'picture', 'image', 'snapshot'],
    [UserIconNameEnum.Car]: ['vehicle', 'auto', 'automobile', 'transport', 'drive', 'gas', 'fuel', 'parking'],
    [UserIconNameEnum.CarFront]: ['vehicle', 'auto', 'automobile', 'transport', 'drive'],
    [UserIconNameEnum.ChartNoAxesColumn]: ['analytics', 'statistics', 'graph', 'data', 'report'],
    [UserIconNameEnum.Check]: ['done', 'complete', 'success', 'confirm', 'approve'],
    [UserIconNameEnum.ChevronDown]: ['arrow', 'expand', 'dropdown'],
    [UserIconNameEnum.ChevronLeft]: ['arrow', 'back', 'previous'],
    [UserIconNameEnum.ChevronRight]: ['arrow', 'forward', 'next'],
    [UserIconNameEnum.ChevronUp]: ['arrow', 'collapse'],
    [UserIconNameEnum.ChevronsDown]: ['arrow', 'expand'],
    [UserIconNameEnum.ChevronsRight]: ['arrow', 'forward'],
    [UserIconNameEnum.Church]: ['religion', 'worship', 'faith', 'spiritual', 'donation'],
    [UserIconNameEnum.Cigarette]: ['smoking', 'tobacco', 'habit'],
    [UserIconNameEnum.Circle]: ['shape', 'dot', 'bullet'],
    [UserIconNameEnum.CircleDot]: ['target', 'focus', 'center'],
    [UserIconNameEnum.Clapperboard]: ['movie', 'film', 'cinema', 'entertainment', 'video'],
    [UserIconNameEnum.Clock]: ['time', 'hour', 'watch', 'schedule'],
    [UserIconNameEnum.Cloud]: ['weather', 'storage', 'sky', 'upload'],
    [UserIconNameEnum.CloudRain]: ['weather', 'rain', 'umbrella'],
    [UserIconNameEnum.CloudSun]: ['weather', 'sunny', 'partly'],
    [UserIconNameEnum.Code]: ['programming', 'developer', 'software', 'tech'],
    [UserIconNameEnum.Coffee]: ['drink', 'cafe', 'beverage', 'morning', 'caffeine', 'breakfast'],
    [UserIconNameEnum.Coins]: ['money', 'currency', 'cash', 'payment', 'savings'],
    [UserIconNameEnum.Compass]: ['navigation', 'direction', 'travel', 'explore'],
    [UserIconNameEnum.Construction]: ['building', 'work', 'renovation', 'repair'],
    [UserIconNameEnum.Cookie]: ['snack', 'food', 'dessert', 'sweet'],
    [UserIconNameEnum.CookingPot]: ['kitchen', 'cook', 'food', 'meal', 'dinner'],
    [UserIconNameEnum.CreditCard]: ['payment', 'card', 'bank', 'finance', 'purchase', 'shopping'],
    [UserIconNameEnum.Croissant]: ['food', 'breakfast', 'bakery', 'pastry', 'french'],
    [UserIconNameEnum.Crown]: ['king', 'queen', 'royal', 'premium', 'vip'],
    [UserIconNameEnum.Database]: ['storage', 'data', 'server', 'backup'],
    [UserIconNameEnum.Delete]: ['remove', 'trash', 'erase', 'backspace'],
    [UserIconNameEnum.Diamond]: ['luxury', 'gem', 'jewelry', 'precious', 'expensive'],
    [UserIconNameEnum.Dice1]: ['game', 'gambling', 'casino', 'luck', 'random'],
    [UserIconNameEnum.Dice2]: ['game', 'gambling', 'casino', 'luck', 'random'],
    [UserIconNameEnum.Dice3]: ['game', 'gambling', 'casino', 'luck', 'random'],
    [UserIconNameEnum.Dice4]: ['game', 'gambling', 'casino', 'luck', 'random'],
    [UserIconNameEnum.Dice5]: ['game', 'gambling', 'casino', 'luck', 'random'],
    [UserIconNameEnum.Dice6]: ['game', 'gambling', 'casino', 'luck', 'random'],
    [UserIconNameEnum.DollarSign]: ['money', 'currency', 'usd', 'dollar', 'finance', 'price'],
    [UserIconNameEnum.Dot]: ['point', 'bullet', 'circle'],
    [UserIconNameEnum.Download]: ['save', 'get', 'receive'],
    [UserIconNameEnum.Drama]: ['theater', 'acting', 'performance', 'entertainment'],
    [UserIconNameEnum.Dribbble]: ['design', 'creative', 'portfolio'],
    [UserIconNameEnum.Droplet]: ['water', 'liquid', 'rain', 'drink'],
    [UserIconNameEnum.Dumbbell]: ['gym', 'fitness', 'exercise', 'workout', 'sport', 'health', 'muscle'],
    [UserIconNameEnum.Ear]: ['hearing', 'listen', 'sound', 'audio'],
    [UserIconNameEnum.Egg]: ['food', 'breakfast', 'cooking', 'protein'],
    [UserIconNameEnum.Euro]: ['money', 'currency', 'eur', 'europe', 'finance'],
    [UserIconNameEnum.Eye]: ['view', 'see', 'watch', 'visible', 'show'],
    [UserIconNameEnum.EyeOff]: ['hide', 'invisible', 'hidden', 'private'],
    [UserIconNameEnum.Facebook]: ['social', 'media', 'network'],
    [UserIconNameEnum.Factory]: ['industry', 'manufacturing', 'production', 'business'],
    [UserIconNameEnum.Fan]: ['cooling', 'air', 'ventilation', 'appliance'],
    [UserIconNameEnum.FileText]: ['document', 'file', 'paper', 'text', 'note'],
    [UserIconNameEnum.Film]: ['movie', 'cinema', 'video', 'entertainment'],
    [UserIconNameEnum.Fingerprint]: ['security', 'identity', 'biometric', 'auth'],
    [UserIconNameEnum.Flag]: ['country', 'nation', 'mark', 'report'],
    [UserIconNameEnum.Flame]: ['fire', 'hot', 'trending', 'popular'],
    [UserIconNameEnum.Flashlight]: ['light', 'torch', 'emergency'],
    [UserIconNameEnum.FlaskConical]: ['science', 'chemistry', 'lab', 'experiment'],
    [UserIconNameEnum.Flower]: ['plant', 'garden', 'nature', 'bloom', 'gift'],
    [UserIconNameEnum.Flower2]: ['plant', 'garden', 'nature', 'bloom', 'gift'],
    [UserIconNameEnum.Folder]: ['file', 'directory', 'organize', 'category'],
    [UserIconNameEnum.FolderX]: ['file', 'directory', 'delete', 'remove'],
    [UserIconNameEnum.Footprints]: ['walk', 'travel', 'track', 'hike'],
    [UserIconNameEnum.Fuel]: ['gas', 'petrol', 'car', 'vehicle', 'energy'],
    [UserIconNameEnum.Gamepad]: ['game', 'gaming', 'play', 'controller', 'entertainment', 'console'],
    [UserIconNameEnum.Gamepad2]: ['game', 'gaming', 'play', 'controller', 'entertainment', 'console'],
    [UserIconNameEnum.Gauge]: ['speed', 'performance', 'meter', 'dashboard'],
    [UserIconNameEnum.Gem]: ['diamond', 'jewelry', 'precious', 'luxury'],
    [UserIconNameEnum.Ghost]: ['halloween', 'spooky', 'spirit'],
    [UserIconNameEnum.Gift]: ['present', 'birthday', 'celebration', 'surprise', 'holiday'],
    [UserIconNameEnum.GlassWater]: ['drink', 'water', 'beverage', 'hydrate'],
    [UserIconNameEnum.Glasses]: ['eyewear', 'vision', 'reading', 'optical'],
    [UserIconNameEnum.Globe]: ['world', 'earth', 'international', 'global', 'internet'],
    [UserIconNameEnum.GraduationCap]: ['education', 'school', 'university', 'college', 'degree', 'student', 'tuition'],
    [UserIconNameEnum.Grape]: ['fruit', 'wine', 'food', 'vineyard'],
    [UserIconNameEnum.Grip]: ['handle', 'drag', 'move'],
    [UserIconNameEnum.Guitar]: ['music', 'instrument', 'band', 'rock'],
    [UserIconNameEnum.Hammer]: ['tool', 'construction', 'repair', 'build'],
    [UserIconNameEnum.HandCoins]: ['money', 'payment', 'give', 'donate', 'tip', 'loan', 'debt'],
    [UserIconNameEnum.HandHeart]: ['charity', 'donate', 'give', 'love', 'care'],
    [UserIconNameEnum.HandHelping]: ['help', 'support', 'assist', 'charity'],
    [UserIconNameEnum.Handshake]: ['deal', 'agreement', 'partnership', 'business'],
    [UserIconNameEnum.HardDrive]: ['storage', 'computer', 'data', 'disk'],
    [UserIconNameEnum.HardHat]: ['construction', 'safety', 'worker', 'building'],
    [UserIconNameEnum.Hash]: ['number', 'tag', 'hashtag', 'social'],
    [UserIconNameEnum.Headphones]: ['music', 'audio', 'listen', 'sound', 'podcast'],
    [UserIconNameEnum.Headset]: ['music', 'audio', 'gaming', 'support', 'call'],
    [UserIconNameEnum.Heart]: ['love', 'like', 'favorite', 'health', 'romance'],
    [UserIconNameEnum.HeartHandshake]: ['partnership', 'love', 'agreement', 'charity'],
    [UserIconNameEnum.HeartPulse]: ['health', 'medical', 'heartbeat', 'fitness', 'hospital'],
    [UserIconNameEnum.Heater]: ['warm', 'heating', 'home', 'appliance'],
    [UserIconNameEnum.Highlighter]: ['marker', 'pen', 'office', 'school'],
    [UserIconNameEnum.History]: ['time', 'past', 'record', 'log'],
    [UserIconNameEnum.Home]: ['house', 'residence', 'property', 'mortgage', 'rent', 'living'],
    [UserIconNameEnum.Hospital]: ['health', 'medical', 'emergency', 'doctor', 'clinic'],
    [UserIconNameEnum.Hotel]: ['accommodation', 'travel', 'room', 'stay', 'vacation'],
    [UserIconNameEnum.Hourglass]: ['time', 'wait', 'loading', 'timer'],
    [UserIconNameEnum.IceCreamBowl]: ['dessert', 'sweet', 'food', 'treat', 'summer'],
    [UserIconNameEnum.IceCreamCone]: ['dessert', 'sweet', 'food', 'treat', 'summer'],
    [UserIconNameEnum.Image]: ['photo', 'picture', 'gallery', 'media'],
    [UserIconNameEnum.Images]: ['photo', 'picture', 'gallery', 'media', 'album'],
    [UserIconNameEnum.Import]: ['upload', 'bring', 'add', 'data'],
    [UserIconNameEnum.Inbox]: ['mail', 'email', 'message', 'receive'],
    [UserIconNameEnum.IndianRupee]: ['money', 'currency', 'inr', 'india', 'rupee', 'finance'],
    [UserIconNameEnum.Info]: ['information', 'help', 'about', 'details'],
    [UserIconNameEnum.Instagram]: ['social', 'media', 'photo', 'network'],
    [UserIconNameEnum.JapaneseYen]: ['money', 'currency', 'jpy', 'japan', 'yen', 'finance'],
    [UserIconNameEnum.Joystick]: ['game', 'gaming', 'play', 'controller'],
    [UserIconNameEnum.Key]: ['security', 'lock', 'access', 'password'],
    [UserIconNameEnum.KeyRound]: ['security', 'lock', 'access', 'password'],
    [UserIconNameEnum.Keyboard]: ['type', 'input', 'computer', 'tech'],
    [UserIconNameEnum.Lamp]: ['light', 'home', 'interior', 'desk'],
    [UserIconNameEnum.LampDesk]: ['light', 'home', 'interior', 'desk', 'office'],
    [UserIconNameEnum.Landmark]: ['bank', 'government', 'building', 'institution', 'finance'],
    [UserIconNameEnum.Languages]: ['translate', 'international', 'global', 'speech'],
    [UserIconNameEnum.Laptop]: ['computer', 'tech', 'work', 'device'],
    [UserIconNameEnum.Layers]: ['stack', 'organize', 'design'],
    [UserIconNameEnum.Leaf]: ['nature', 'plant', 'eco', 'green', 'environment'],
    [UserIconNameEnum.Library]: ['books', 'reading', 'education', 'study'],
    [UserIconNameEnum.Lightbulb]: ['idea', 'electricity', 'creative', 'innovation', 'utility'],
    [UserIconNameEnum.Link]: ['url', 'connection', 'web', 'chain'],
    [UserIconNameEnum.Linkedin]: ['social', 'professional', 'network', 'job'],
    [UserIconNameEnum.List]: ['menu', 'items', 'todo', 'organize'],
    [UserIconNameEnum.ListTodo]: ['task', 'checklist', 'organize', 'todo'],
    [UserIconNameEnum.Loader]: ['loading', 'wait', 'progress'],
    [UserIconNameEnum.Lock]: ['security', 'password', 'protect', 'private'],
    [UserIconNameEnum.LockKeyhole]: ['security', 'password', 'protect', 'private'],
    [UserIconNameEnum.LogIn]: ['enter', 'sign', 'access'],
    [UserIconNameEnum.LogOut]: ['exit', 'sign', 'leave'],
    [UserIconNameEnum.Luggage]: ['travel', 'suitcase', 'trip', 'vacation', 'bag'],
    [UserIconNameEnum.Mail]: ['email', 'message', 'letter', 'communication'],
    [UserIconNameEnum.Mailbox]: ['mail', 'post', 'letter', 'receive'],
    [UserIconNameEnum.Map]: ['navigation', 'location', 'direction', 'travel'],
    [UserIconNameEnum.MapPin]: ['location', 'place', 'marker', 'address'],
    [UserIconNameEnum.Martini]: ['drink', 'alcohol', 'cocktail', 'bar', 'party'],
    [UserIconNameEnum.Medal]: ['award', 'achievement', 'prize', 'winner'],
    [UserIconNameEnum.Megaphone]: ['announcement', 'marketing', 'advertising', 'promotion'],
    [UserIconNameEnum.MessageCircle]: ['chat', 'message', 'communication', 'talk'],
    [UserIconNameEnum.MessageSquare]: ['chat', 'message', 'communication', 'talk'],
    [UserIconNameEnum.Mic]: ['microphone', 'audio', 'record', 'voice', 'podcast'],
    [UserIconNameEnum.Milestone]: ['goal', 'achievement', 'progress', 'road'],
    [UserIconNameEnum.Milk]: ['drink', 'dairy', 'breakfast', 'beverage'],
    [UserIconNameEnum.Moon]: ['night', 'dark', 'sleep', 'theme'],
    [UserIconNameEnum.Mountain]: ['nature', 'hiking', 'outdoor', 'adventure', 'travel'],
    [UserIconNameEnum.MountainSnow]: ['nature', 'winter', 'skiing', 'adventure'],
    [UserIconNameEnum.Mouse]: ['computer', 'click', 'device', 'tech'],
    [UserIconNameEnum.Music]: ['audio', 'song', 'sound', 'entertainment', 'spotify'],
    [UserIconNameEnum.Music2]: ['audio', 'song', 'sound', 'entertainment'],
    [UserIconNameEnum.Navigation]: ['direction', 'gps', 'location', 'travel'],
    [UserIconNameEnum.Network]: ['connection', 'internet', 'social', 'web'],
    [UserIconNameEnum.Newspaper]: ['news', 'article', 'media', 'reading', 'subscription'],
    [UserIconNameEnum.Notebook]: ['note', 'writing', 'journal', 'study'],
    [UserIconNameEnum.NotebookPen]: ['note', 'writing', 'journal', 'study'],
    [UserIconNameEnum.Nut]: ['food', 'snack', 'protein', 'allergy'],
    [UserIconNameEnum.OctagonAlert]: ['warning', 'danger', 'stop', 'alert'],
    [UserIconNameEnum.Package]: ['box', 'delivery', 'shipping', 'parcel', 'ecommerce'],
    [UserIconNameEnum.Paintbrush]: ['art', 'design', 'creative', 'paint'],
    [UserIconNameEnum.Palette]: ['art', 'design', 'color', 'creative'],
    [UserIconNameEnum.Paperclip]: ['attachment', 'file', 'document', 'clip'],
    [UserIconNameEnum.PartyPopper]: ['celebration', 'party', 'birthday', 'event', 'fun'],
    [UserIconNameEnum.PawPrint]: ['pet', 'animal', 'dog', 'cat', 'veterinary'],
    [UserIconNameEnum.Pen]: ['write', 'edit', 'note', 'sign'],
    [UserIconNameEnum.Pencil]: ['write', 'edit', 'draw', 'note'],
    [UserIconNameEnum.PencilRuler]: ['design', 'draw', 'measure', 'architect'],
    [UserIconNameEnum.Percent]: ['discount', 'sale', 'percentage', 'math'],
    [UserIconNameEnum.PersonStanding]: ['human', 'people', 'walk', 'standing'],
    [UserIconNameEnum.Phone]: ['call', 'mobile', 'telephone', 'contact', 'communication'],
    [UserIconNameEnum.PhoneCall]: ['call', 'mobile', 'telephone', 'communication'],
    [UserIconNameEnum.Piano]: ['music', 'instrument', 'keyboard', 'classical'],
    [UserIconNameEnum.Pickaxe]: ['mining', 'tool', 'dig', 'work'],
    [UserIconNameEnum.PiggyBank]: ['savings', 'money', 'bank', 'save', 'investment'],
    [UserIconNameEnum.Pill]: ['medicine', 'pharmacy', 'health', 'drug', 'medical'],
    [UserIconNameEnum.Pin]: ['location', 'mark', 'attach', 'note'],
    [UserIconNameEnum.Pizza]: ['food', 'restaurant', 'meal', 'delivery', 'italian'],
    [UserIconNameEnum.Plane]: ['travel', 'flight', 'airplane', 'airport', 'vacation', 'trip'],
    [UserIconNameEnum.PlaneTakeoff]: ['travel', 'flight', 'airplane', 'departure'],
    [UserIconNameEnum.PlaneLanding]: ['travel', 'flight', 'airplane', 'arrival'],
    [UserIconNameEnum.Play]: ['video', 'music', 'start', 'media'],
    [UserIconNameEnum.Plug]: ['electricity', 'power', 'connect', 'utility'],
    [UserIconNameEnum.Plus]: ['add', 'new', 'create', 'increase'],
    [UserIconNameEnum.Podcast]: ['audio', 'show', 'listen', 'radio'],
    [UserIconNameEnum.Popcorn]: ['movie', 'cinema', 'snack', 'entertainment', 'theater'],
    [UserIconNameEnum.PoundSterling]: ['money', 'currency', 'gbp', 'uk', 'british', 'finance'],
    [UserIconNameEnum.Power]: ['on', 'off', 'switch', 'electricity'],
    [UserIconNameEnum.Printer]: ['print', 'document', 'office', 'paper'],
    [UserIconNameEnum.Projector]: ['presentation', 'movie', 'display', 'meeting'],
    [UserIconNameEnum.Puzzle]: ['game', 'piece', 'solve', 'hobby'],
    [UserIconNameEnum.QrCode]: ['scan', 'code', 'payment', 'link'],
    [UserIconNameEnum.Quote]: ['text', 'citation', 'saying'],
    [UserIconNameEnum.Radio]: ['music', 'broadcast', 'audio', 'listen'],
    [UserIconNameEnum.Receipt]: ['bill', 'invoice', 'payment', 'transaction', 'purchase', 'expense'],
    [UserIconNameEnum.RefreshCcw]: ['reload', 'sync', 'update', 'refresh'],
    [UserIconNameEnum.RefreshCw]: ['reload', 'sync', 'update', 'refresh'],
    [UserIconNameEnum.Refrigerator]: ['kitchen', 'food', 'appliance', 'cold', 'home'],
    [UserIconNameEnum.Repeat]: ['loop', 'recurring', 'repeat', 'subscription'],
    [UserIconNameEnum.Reply]: ['respond', 'answer', 'message'],
    [UserIconNameEnum.Ribbon]: ['award', 'prize', 'decoration', 'gift'],
    [UserIconNameEnum.Rocket]: ['launch', 'startup', 'space', 'fast'],
    [UserIconNameEnum.RockingChair]: ['furniture', 'relax', 'home', 'comfort'],
    [UserIconNameEnum.RollerCoaster]: ['fun', 'amusement', 'park', 'entertainment', 'thrill'],
    [UserIconNameEnum.RotateCcw]: ['rotate', 'undo', 'turn', 'left'],
    [UserIconNameEnum.Router]: ['wifi', 'internet', 'network', 'connection'],
    [UserIconNameEnum.Rss]: ['feed', 'blog', 'news', 'subscribe'],
    [UserIconNameEnum.RussianRuble]: ['money', 'currency', 'rub', 'russia', 'ruble', 'finance'],
    [UserIconNameEnum.Sailboat]: ['boat', 'water', 'sailing', 'travel', 'vacation'],
    [UserIconNameEnum.Salad]: ['food', 'healthy', 'vegetable', 'meal', 'diet'],
    [UserIconNameEnum.Sandwich]: ['food', 'lunch', 'meal', 'snack'],
    [UserIconNameEnum.Save]: ['disk', 'store', 'keep', 'backup'],
    [UserIconNameEnum.Scale]: ['weight', 'balance', 'measure', 'justice'],
    [UserIconNameEnum.ScanFace]: ['face', 'biometric', 'security', 'identity'],
    [UserIconNameEnum.School]: ['education', 'learning', 'student', 'building'],
    [UserIconNameEnum.Scissors]: ['cut', 'tool', 'craft', 'edit'],
    [UserIconNameEnum.Search]: ['find', 'look', 'query', 'magnify'],
    [UserIconNameEnum.SearchX]: ['find', 'not found', 'no results'],
    [UserIconNameEnum.Send]: ['message', 'share', 'email', 'submit'],
    [UserIconNameEnum.Settings]: ['gear', 'preferences', 'options', 'config'],
    [UserIconNameEnum.Share]: ['social', 'send', 'distribute'],
    [UserIconNameEnum.Shield]: ['security', 'protect', 'safe', 'insurance'],
    [UserIconNameEnum.ShieldCheck]: ['security', 'verified', 'protect', 'safe', 'insurance'],
    [UserIconNameEnum.Ship]: ['boat', 'cruise', 'travel', 'water', 'shipping'],
    [UserIconNameEnum.Shirt]: ['clothing', 'fashion', 'apparel', 'wear', 'shopping'],
    [UserIconNameEnum.ShoppingBag]: ['shop', 'purchase', 'retail', 'store', 'ecommerce'],
    [UserIconNameEnum.ShoppingBasket]: ['grocery', 'shop', 'purchase', 'store', 'supermarket'],
    [UserIconNameEnum.ShoppingCart]: ['shop', 'purchase', 'cart', 'ecommerce', 'buy'],
    [UserIconNameEnum.Shovel]: ['garden', 'dig', 'tool', 'work'],
    [UserIconNameEnum.Signpost]: ['direction', 'sign', 'navigation', 'road'],
    [UserIconNameEnum.Smartphone]: ['phone', 'mobile', 'device', 'tech', 'cell'],
    [UserIconNameEnum.Smile]: ['happy', 'emoji', 'face', 'emotion'],
    [UserIconNameEnum.Snail]: ['slow', 'animal', 'nature'],
    [UserIconNameEnum.Snowflake]: ['winter', 'cold', 'snow', 'ice'],
    [UserIconNameEnum.Sofa]: ['furniture', 'living', 'home', 'couch', 'relax'],
    [UserIconNameEnum.Soup]: ['food', 'meal', 'hot', 'bowl', 'lunch'],
    [UserIconNameEnum.Sparkles]: ['magic', 'new', 'shine', 'ai', 'special'],
    [UserIconNameEnum.Speaker]: ['audio', 'sound', 'music', 'volume'],
    [UserIconNameEnum.Sprout]: ['plant', 'grow', 'nature', 'eco'],
    [UserIconNameEnum.Square]: ['shape', 'box', 'stop'],
    [UserIconNameEnum.Stamp]: ['mail', 'post', 'approve', 'official'],
    [UserIconNameEnum.Star]: ['favorite', 'rating', 'bookmark', 'important'],
    [UserIconNameEnum.Stethoscope]: ['medical', 'doctor', 'health', 'hospital'],
    [UserIconNameEnum.Store]: ['shop', 'retail', 'business', 'market', 'ecommerce'],
    [UserIconNameEnum.Sticker]: ['label', 'tag', 'emoji'],
    [UserIconNameEnum.Sun]: ['weather', 'day', 'light', 'bright', 'summer'],
    [UserIconNameEnum.Sunrise]: ['morning', 'dawn', 'weather', 'day'],
    [UserIconNameEnum.Sunset]: ['evening', 'dusk', 'weather', 'day'],
    [UserIconNameEnum.SwissFranc]: ['money', 'currency', 'chf', 'switzerland', 'franc', 'finance'],
    [UserIconNameEnum.Sword]: ['weapon', 'game', 'fight', 'battle'],
    [UserIconNameEnum.Swords]: ['weapon', 'game', 'fight', 'battle'],
    [UserIconNameEnum.Syringe]: ['medical', 'injection', 'vaccine', 'health'],
    [UserIconNameEnum.Table]: ['furniture', 'data', 'spreadsheet'],
    [UserIconNameEnum.Tablet]: ['device', 'ipad', 'tech', 'screen'],
    [UserIconNameEnum.Tag]: ['label', 'price', 'category', 'mark'],
    [UserIconNameEnum.Target]: ['goal', 'aim', 'focus', 'objective'],
    [UserIconNameEnum.Tent]: ['camping', 'outdoor', 'travel', 'adventure'],
    [UserIconNameEnum.Terminal]: ['code', 'command', 'developer', 'tech'],
    [UserIconNameEnum.Thermometer]: ['temperature', 'weather', 'health', 'fever'],
    [UserIconNameEnum.ThumbsDown]: ['dislike', 'bad', 'negative'],
    [UserIconNameEnum.ThumbsUp]: ['like', 'good', 'positive', 'approve'],
    [UserIconNameEnum.Ticket]: ['event', 'movie', 'concert', 'pass', 'entertainment'],
    [UserIconNameEnum.Timer]: ['time', 'countdown', 'clock', 'stopwatch'],
    [UserIconNameEnum.ToggleLeft]: ['switch', 'off', 'option'],
    [UserIconNameEnum.ToggleRight]: ['switch', 'on', 'option'],
    [UserIconNameEnum.Tornado]: ['weather', 'storm', 'disaster'],
    [UserIconNameEnum.Tractor]: ['farm', 'agriculture', 'vehicle'],
    [UserIconNameEnum.TrafficCone]: ['road', 'construction', 'warning'],
    [UserIconNameEnum.TrainFront]: ['transport', 'railway', 'travel', 'commute'],
    [UserIconNameEnum.Trash]: ['delete', 'remove', 'bin', 'garbage'],
    [UserIconNameEnum.Trash2]: ['delete', 'remove', 'bin', 'garbage'],
    [UserIconNameEnum.TreePalm]: ['tropical', 'beach', 'vacation', 'nature'],
    [UserIconNameEnum.TreePine]: ['forest', 'nature', 'christmas', 'outdoor'],
    [UserIconNameEnum.Trees]: ['forest', 'nature', 'park', 'outdoor'],
    [UserIconNameEnum.TrendingDown]: ['decrease', 'loss', 'expense', 'negative', 'stock'],
    [UserIconNameEnum.TrendingUp]: ['increase', 'profit', 'income', 'positive', 'stock', 'growth'],
    [UserIconNameEnum.Trophy]: ['award', 'winner', 'achievement', 'prize', 'competition'],
    [UserIconNameEnum.Truck]: ['delivery', 'shipping', 'transport', 'vehicle', 'logistics'],
    [UserIconNameEnum.Tv]: ['television', 'screen', 'entertainment', 'watch', 'media'],
    [UserIconNameEnum.Twitch]: ['streaming', 'gaming', 'social', 'live'],
    [UserIconNameEnum.Twitter]: ['social', 'media', 'network', 'tweet'],
    [UserIconNameEnum.Umbrella]: ['rain', 'weather', 'protection'],
    [UserIconNameEnum.University]: ['education', 'college', 'school', 'degree', 'academic'],
    [UserIconNameEnum.Upload]: ['share', 'send', 'cloud', 'file'],
    [UserIconNameEnum.Usb]: ['device', 'connection', 'tech', 'storage'],
    [UserIconNameEnum.User]: ['person', 'account', 'profile', 'contact'],
    [UserIconNameEnum.Users]: ['people', 'group', 'team', 'community'],
    [UserIconNameEnum.Utensils]: [
        'food',
        'restaurant',
        'eating',
        'dining',
        'meal',
        'fork',
        'knife',
        'cutlery',
        'dinner',
        'lunch',
        'breakfast'
    ],
    [UserIconNameEnum.UtensilsCrossed]: ['food', 'restaurant', 'eating', 'dining', 'meal', 'closed'],
    [UserIconNameEnum.Vault]: ['safe', 'security', 'bank', 'storage', 'money'],
    [UserIconNameEnum.Vegan]: ['food', 'plant', 'diet', 'healthy'],
    [UserIconNameEnum.Video]: ['camera', 'record', 'film', 'media'],
    [UserIconNameEnum.Volleyball]: ['sport', 'game', 'ball', 'beach'],
    [UserIconNameEnum.Volume]: ['sound', 'audio', 'speaker'],
    [UserIconNameEnum.Volume2]: ['sound', 'audio', 'speaker'],
    [UserIconNameEnum.Wallet]: ['money', 'payment', 'finance', 'cash', 'purse'],
    [UserIconNameEnum.Wand]: ['magic', 'edit', 'tool'],
    [UserIconNameEnum.Warehouse]: ['storage', 'inventory', 'logistics', 'building'],
    [UserIconNameEnum.WashingMachine]: ['laundry', 'clothes', 'clean', 'appliance', 'home'],
    [UserIconNameEnum.Watch]: ['time', 'wrist', 'clock', 'accessory'],
    [UserIconNameEnum.Waves]: ['water', 'ocean', 'sea', 'beach'],
    [UserIconNameEnum.Webcam]: ['camera', 'video', 'call', 'meeting'],
    [UserIconNameEnum.Weight]: ['scale', 'fitness', 'gym', 'measure'],
    [UserIconNameEnum.Wheat]: ['grain', 'food', 'farm', 'bread'],
    [UserIconNameEnum.Wifi]: ['internet', 'wireless', 'connection', 'network'],
    [UserIconNameEnum.Wind]: ['weather', 'air', 'blow'],
    [UserIconNameEnum.Wine]: ['drink', 'alcohol', 'bar', 'restaurant', 'beverage'],
    [UserIconNameEnum.Wrench]: ['tool', 'repair', 'fix', 'maintenance', 'settings'],
    [UserIconNameEnum.X]: ['close', 'cancel', 'delete', 'remove'],
    [UserIconNameEnum.Youtube]: ['video', 'social', 'media', 'streaming'],
    [UserIconNameEnum.Zap]: ['electricity', 'power', 'energy', 'lightning', 'fast'],
    [UserIconNameEnum.ZoomIn]: ['magnify', 'enlarge', 'plus'],
    [UserIconNameEnum.ZoomOut]: ['magnify', 'shrink', 'minus']
};
