const normalizePart = (value: string) => value.replace(/[^a-zA-Z0-9]+/gu, '_');

export const SettingsPageSelector = {
    Container: 'SettingsPage.Container',
    AppLockCard: 'SettingsPage.AppLockCard',
    AppLockChangePinButton: 'SettingsPage.AppLockChangePinButton',
    AppLockDisableButton: 'SettingsPage.AppLockDisableButton',
    AppLockBiometricSwitch: 'SettingsPage.AppLockBiometricSwitch',
    ScreenshotProtectionCard: 'SettingsPage.ScreenshotProtectionCard',
    ScreenshotProtectionSwitch: 'SettingsPage.ScreenshotProtectionSwitch',
    LanguageCard: 'SettingsPage.LanguageCard',
    LanguageValue: (code: string) => `SettingsPage.LanguageValue.${normalizePart(code)}` as const,
    MainCurrencyCard: 'SettingsPage.MainCurrencyCard',
    MainCurrencyValue: (code: string) => `SettingsPage.MainCurrencyValue.${normalizePart(code)}` as const,
    DefaultAccountCard: 'SettingsPage.DefaultAccountCard',
    DefaultAccountValue: (title: string) => `SettingsPage.DefaultAccountValue.${normalizePart(title)}` as const,
    DarkModeCard: 'SettingsPage.DarkModeCard',
    DarkModeSwitch: 'SettingsPage.DarkModeSwitch',
    ShowCentsCard: 'SettingsPage.ShowCentsCard',
    ShowCentsSwitch: 'SettingsPage.ShowCentsSwitch',
    ManageCategoriesCard: 'SettingsPage.ManageCategoriesCard',
    ManageTagsCard: 'SettingsPage.ManageTagsCard',
    ArchivedCard: 'SettingsPage.ArchivedCard',
    InactiveCard: 'SettingsPage.InactiveCard',
    ImportDatabaseCard: 'SettingsPage.ImportDatabaseCard',
    ExportDatabaseCard: 'SettingsPage.ExportDatabaseCard',
    ClearDataCard: 'SettingsPage.ClearDataCard',
    ManageRulesCard: 'SettingsPage.ManageRulesCard',
    MoneyDataUpgradeCard: 'SettingsPage.MoneyDataUpgradeCard'
} as const;
