export const BudgetSelector = {
    WidgetEmptyState: 'BudgetWidget.EmptyState',
    WidgetCard: 'BudgetWidget.Card',
    WidgetSpentLabel: 'BudgetWidget.SpentLabel',
    WidgetRemainingLabel: 'BudgetWidget.RemainingLabel',
    WidgetCategoryRow: (categoryId: number) => `BudgetWidget.CategoryRow.${categoryId}` as const,
    WidgetCategorySpentLabel: (categoryId: number) => `BudgetWidget.CategorySpentLabel.${categoryId}` as const,
    WidgetMoreCategoriesLabel: 'BudgetWidget.MoreCategoriesLabel',
    DetailsEditButton: 'BudgetDetails.EditButton',
    DetailsSpentLabel: 'BudgetDetails.SpentLabel',
    DetailsRemainingLabel: 'BudgetDetails.RemainingLabel',
    DetailsCategoryRow: (categoryId: number) => `BudgetDetails.CategoryRow.${categoryId}` as const,
    DetailsCategorySpentLabel: (categoryId: number) => `BudgetDetails.CategorySpentLabel.${categoryId}` as const,
    DetailsOtherCategoryRow: 'BudgetDetails.OtherCategoryRow',
    DetailsOtherCategorySpentLabel: 'BudgetDetails.OtherCategorySpentLabel',
    SetupOverallLimitInput: 'BudgetSetup.OverallLimitInput',
    SetupSpentLabel: 'BudgetSetup.SpentLabel',
    SetupRemainingLabel: 'BudgetSetup.RemainingLabel',
    SetupSaveButton: 'BudgetSetup.SaveButton',
    SetupDeleteButton: 'BudgetSetup.DeleteButton',
    SetupCategoryLimitsHeader: 'BudgetSetup.CategoryLimitsHeader',
    SetupCategoryLimitAddButton: 'BudgetSetup.CategoryLimitAddButton',
    SetupCategoryLimitRow: (index: number) => `BudgetSetup.CategoryLimit.${index}.Row` as const,
    SetupCategoryLimitAmountInput: (index: number) => `BudgetSetup.CategoryLimit.${index}.AmountInput` as const,
    SetupOtherCategoryLimitRow: 'BudgetSetup.OtherCategoryLimit.Row',
    SetupOtherCategoryLimitAmountInput: 'BudgetSetup.OtherCategoryLimit.AmountInput',
    SetupAllocationSummaryOverBy: 'BudgetSetup.AllocationSummary.OverBy',
    SetupAllocationSummaryRemaining: 'BudgetSetup.AllocationSummary.Remaining'
} as const;
