export enum TransferPairAutoConfidenceBucketEnum {
    AUTO_CROSS_CURRENCY_IMPLIED_RATE = 'AUTO_CROSS_CURRENCY_IMPLIED_RATE',
    AUTO_CROSS_CURRENCY_OPERATION = 'AUTO_CROSS_CURRENCY_OPERATION',
    AUTO_IBAN_AMOUNT = 'AUTO_IBAN_AMOUNT',
    AUTO_INTERBANK_HINTED_FEE = 'AUTO_INTERBANK_HINTED_FEE',
    AUTO_SAME_BANK_CROSS_CURRENCY = 'AUTO_SAME_BANK_CROSS_CURRENCY',
    AUTO_SAME_BANK_HINTED_FEE = 'AUTO_SAME_BANK_HINTED_FEE',
    AUTO_SAME_CURRENCY_AMOUNT = 'AUTO_SAME_CURRENCY_AMOUNT'
}
