export enum TransactionConsolidationTypeEnum {
    TRANSFER_PAIR = 'TRANSFER_PAIR',
    IBAN_BRIDGE_TRANSFER = 'IBAN_BRIDGE_TRANSFER',
    IBAN_BRIDGE_CHAIN_TRANSFER = 'IBAN_BRIDGE_CHAIN_TRANSFER',
    ATM_CASH_WITHDRAWAL = 'ATM_CASH_WITHDRAWAL',
    CROSS_CURRENCY_EXCHANGE = 'CROSS_CURRENCY_EXCHANGE',
    REFUND = 'REFUND'
}
