export enum ExternalSourceEnum {
    MANUAL = 'MANUAL',
    MONOBANK = 'MONOBANK',
    PRIVATBANK = 'PRIVATBANK',
    ERSTE = 'ERSTE',
    REVOLUT = 'REVOLUT',
    BINANCE = 'BINANCE',
    COINBASE = 'COINBASE',
    WISE = 'WISE',
    APPLE_PAY_AUTOMATION = 'APPLE_PAY_AUTOMATION',
    CSV = 'CSV'
}
