CREATE TABLE `mcc_groups` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`deleted_at` integer,
	`type` text NOT NULL,
	`description` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `mcc_groups_type_unique` ON `mcc_groups` (`type`);
--> statement-breakpoint
CREATE TABLE `mcc_categories` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`deleted_at` integer,
	`mcc` text NOT NULL,
	`mcc_group_id` integer NOT NULL,
	`short_description` text NOT NULL,
	`full_description` text NOT NULL,
	FOREIGN KEY (`mcc_group_id`) REFERENCES `mcc_groups`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `mcc_categories_mcc_unique` ON `mcc_categories` (`mcc`);
--> statement-breakpoint
INSERT INTO `mcc_groups` (`id`, `type`, `description`) VALUES
(1, 'AS', 'Agricultural Services'),
(2, 'CS', 'Contract services'),
(3, 'WSM', 'Wholesale suppliers and manufacturers'),
(4, 'AL', 'Airlines'),
(5, 'CR', 'Car rent'),
(6, 'HR', 'Hotels / Resorts'),
(7, 'NC', 'Not categorized'),
(8, 'TS', 'Transportation Services'),
(9, 'US', 'Utility Services'),
(10, 'SP', 'Service provider'),
(11, 'ROS', 'Retail Outlet Services'),
(12, 'CV', 'Cars and vehicles'),
(13, 'CLS', 'Clothing stores'),
(14, 'MS', 'Miscellaneous Stores'),
(15, 'MTS', 'Mail / Telephone Sales'),
(16, 'PS', 'Personal services'),
(17, 'BS', 'Business Services'),
(18, 'RS', 'Repair services'),
(19, 'ES', 'Entertainment services'),
(20, 'PFS', 'Professional services'),
(21, 'MO', 'Membership оrganizations'),
(22, 'GS', 'Government Services');--> statement-breakpoint
INSERT INTO `mcc_categories` (`mcc`, `mcc_group_id`, `short_description`, `full_description`) VALUES
('0742', 1, 'Veterinary Services', 'Veterinary Services'),
('0743', 1, 'Wine producers', 'Wine producers'),
('0744', 1, 'Champagne producers', 'Champagne producers'),
('0763', 1, 'Agricultural Co-operatives', 'Agricultural Co-operatives'),
('0780', 1, 'Horticultural and landscaping', 'Horticultural Services, Landscaping Services'),
('1520', 2, 'General Contractors', 'General Contractors - Residential and Commercial'),
('1711', 2, 'Heating, Plumbing, A/C', 'Air Conditioning Contractors - Sales and Installation, Heating Contractors - Sales, Service, Installation'),
('1731', 2, 'Electrical Contractors', 'Electrical Contractors'),
('1740', 2, 'Masonry, Stonework, and Plaster', 'Insulation - Contractors, Masonry, Stonework Contractors, Plastering Contractors, Stonework and Masonry Contractors, Tile Settings Contractors'),
('1750', 2, 'Carpentry Contractors', 'Carpentry Contractors'),
('1761', 2, 'Roofing/Siding, Sheet Metal', 'Roofing - Contractors, Sheet Metal Work - Contractors, Siding - Contractors'),
('1771', 2, 'Concrete Work Contractors', 'Contractors - Concrete Work'),
('1799', 2, 'Special Trade Contractors', 'Contractors - Special Trade'),
('2741', 3, 'Miscellaneous Publishing and Printing', 'Miscellaneous Publishing and Printing'),
('2744', 3, 'Miscellaneous Publishing and Printing', 'Miscellaneous Publishing and Printing'),
('2791', 3, 'Typesetting, Plate Making', 'Typesetting, Plate Making & Related Services'),
('2842', 3, 'Specialty Cleaning', 'Specialty Cleaning, Polishing, and Sanitation Preparations'),
('3000', 4, 'Airlines', 'United Airlines'),
('3001', 4, 'Airlines', 'American Airlines'),
('3002', 4, 'Airlines', 'Pan American World Airways'),
('3003', 4, 'Airlines', 'Eurofly'),
('3004', 4, 'Airlines', 'Dragon Airlines'),
('3005', 4, 'Airlines', 'British Airways'),
('3006', 4, 'Airlines', 'Japan Air Lines'),
('3007', 4, 'Airlines', 'Air France'),
('3008', 4, 'Airlines', 'Lufthansa'),
('3009', 4, 'Airlines', 'Air Canada'),
('3010', 4, 'Airlines', 'KLM (Royal Dutch Airlines)'),
('3011', 4, 'Airlines', 'Aeroflot - Russian Airlines'),
('3012', 4, 'Airlines', 'Qantas'),
('3013', 4, 'Airlines', 'Alitalia'),
('3014', 4, 'Airlines', 'Saudi Arabian Airlines'),
('3015', 4, 'Airlines', 'Swiss International Air Lines'),
('3016', 4, 'Airlines', 'Scandinavian Airline System'),
('3017', 4, 'Airlines', 'South African Airways'),
('3018', 4, 'Airlines', 'Varig (Brazil)'),
('3019', 4, 'Airlines', 'Airlines'),
('3020', 4, 'Airlines', 'Air India'),
('3021', 4, 'Airlines', 'Air Algerie'),
('3022', 4, 'Airlines', 'Philippine Airlines'),
('3023', 4, 'Airlines', 'Mexicana de Aviación'),
('3024', 4, 'Airlines', 'Pakistan International Airlines'),
('3025', 4, 'Airlines', 'Air New Zealand Limited International'),
('3026', 4, 'Airlines', 'Emirates Airlines'),
('3027', 4, 'Airlines', 'Union de Transports Aeriens'),
('3028', 4, 'Airlines', 'Air Malta'),
('3029', 4, 'Airlines', 'SN Brussels Airlines'),
('3030', 4, 'Airlines', 'Aerolineas Argentinas'),
('3031', 4, 'Airlines', 'Olympic Airways'),
('3032', 4, 'Airlines', 'El Al'),
('3033', 4, 'Airlines', 'Ansett Airlines'),
('3034', 4, 'Airlines', 'Etihad Airways'),
('3035', 4, 'Airlines', 'Tap (Portugal)'),
('3036', 4, 'Airlines', 'VASP (Brazil)'),
('3037', 4, 'Airlines', 'EgyptAir'),
('3038', 4, 'Airlines', 'Kuwait Airways'),
('3039', 4, 'Airlines', 'Avianca'),
('3040', 4, 'Airlines', 'Gulf Air (Bahrain)'),
('3041', 4, 'Airlines', 'Balkan-Bulgarian Airlines'),
('3042', 4, 'Airlines', 'Finnair'),
('3043', 4, 'Airlines', 'Aer Lingus (Ireland)'),
('3044', 4, 'Airlines', 'Air Lanka'),
('3045', 4, 'Airlines', 'Nigeria Airways'),
('3046', 4, 'Airlines', 'Cruzeiro do Sul (Brazil)'),
('3047', 4, 'Airlines', 'Turkish Airlines'),
('3048', 4, 'Airlines', 'Royal Air Maroc'),
('3049', 4, 'Airlines', 'Tunis Air'),
('3050', 4, 'Airlines', 'Icelandair'),
('3051', 4, 'Airlines', 'Austrian Airlines'),
('3052', 4, 'Airlines', 'LATAM Chile Airlines'),
('3053', 4, 'Airlines', 'AVIACO (Spain)'),
('3054', 4, 'Airlines', 'LADECO (Chile)'),
('3055', 4, 'Airlines', 'LAB (Bolivia)'),
('3056', 4, 'Airlines', 'Jet Airways (India)'),
('3057', 4, 'Airlines', 'Virgin America'),
('3058', 4, 'Airlines', 'Delta Air Lines'),
('3059', 4, 'Airlines', 'DBA Airlines'),
('3060', 4, 'Airlines', 'Northwest Airlines (USA)'),
('3061', 4, 'Airlines', 'Continental Airlines'),
('3062', 4, 'Airlines', 'Hapag-Lloyd Express'),
('3063', 4, 'Airlines', 'U.S. Airways'),
('3064', 4, 'Airlines', 'Adria Airways'),
('3065', 4, 'Airlines', 'Air Inter'),
('3066', 4, 'Airlines', 'Southwest Airlines (USA)'),
('3067', 4, 'Airlines', 'Vanguard Airlines (USA)'),
('3068', 4, 'Airlines', 'Air Astana'),
('3069', 4, 'Airlines', 'Sun Country Airlines'),
('3070', 4, 'Airlines', 'Pacific Southwest Airlines'),
('3071', 4, 'Airlines', 'Air British Columbia (Canada)'),
('3072', 4, 'Airlines', 'Cebu Pacific (Philippines)'),
('3073', 4, 'Airlines', 'Air California'),
('3074', 4, 'Airlines', 'Airlines'),
('3075', 4, 'Airlines', 'Singapore Airlines'),
('3076', 4, 'Airlines', 'Aeromexico'),
('3077', 4, 'Airlines', 'Thai International Airlines'),
('3078', 4, 'Airlines', 'China Airlines'),
('3079', 4, 'Airlines', 'Jetstar Airways (Australia)'),
('3080', 4, 'Airlines', 'Airlines'),
('3081', 4, 'Airlines', 'Nordair (Canada)'),
('3082', 4, 'Airlines', 'Korean Airlines'),
('3083', 4, 'Airlines', 'Air Afrique'),
('3084', 4, 'Airlines', 'Eva Airways (Taiwan)'),
('3085', 4, 'Airlines', 'Midwest Express Airlines'),
('3086', 4, 'Airlines', 'Carnival Airlines (USA)'),
('3087', 4, 'Airlines', 'Metro Airlines'),
('3088', 4, 'Airlines', 'Croatia Air'),
('3089', 4, 'Airlines', 'Transaero (Russia)'),
('3090', 4, 'Airlines', 'Uni Airways (Taiwan)'),
('3091', 4, 'Airlines', 'Airlines'),
('3092', 4, 'Airlines', 'Midway Airlines (USA)'),
('3093', 4, 'Airlines', 'Airlines'),
('3094', 4, 'Airlines', 'Zambia Airways'),
('3095', 4, 'Airlines', 'Airlines'),
('3096', 4, 'Airlines', 'Air Zimbabwe'),
('3097', 4, 'Airlines', 'Spanair'),
('3098', 4, 'Airlines', 'Asiana Airlines'),
('3099', 4, 'Airlines', 'Cathay Pacific (Hong Kong)'),
('3100', 4, 'Airlines', 'Malaysian Airline System'),
('3101', 4, 'Airlines', 'Airlines'),
('3102', 4, 'Airlines', 'Iberia (Spain)'),
('3103', 4, 'Airlines', 'Garuda (Indonesia)'),
('3104', 4, 'Airlines', 'Airlines'),
('3105', 4, 'Airlines', 'Airlines'),
('3106', 4, 'Airlines', 'Braathens S.A.F.E. (Norway)'),
('3107', 4, 'Airlines', 'Airlines'),
('3108', 4, 'Airlines', 'Airlines'),
('3109', 4, 'Airlines', 'Airlines'),
('3110', 4, 'Airlines', 'Airlines'),
('3111', 4, 'Airlines', 'British Midland Airways'),
('3112', 4, 'Airlines', 'Windward Island'),
('3113', 4, 'Airlines', 'Airlines'),
('3114', 4, 'Airlines', 'Airlines'),
('3115', 4, 'Airlines', 'Airlines'),
('3116', 4, 'Airlines', 'Airlines'),
('3117', 4, 'Airlines', 'Venezolana International de Aviacion'),
('3118', 4, 'Airlines', 'Valley International Airport'),
('3119', 4, 'Airlines', 'Airlines'),
('3120', 4, 'Airlines', 'Airlines'),
('3121', 4, 'Airlines', 'Airlines'),
('3122', 4, 'Airlines', 'Airlines'),
('3123', 4, 'Airlines', 'Airlines'),
('3124', 4, 'Airlines', 'Airlines'),
('3125', 4, 'Airlines', 'Tan Airlines'),
('3126', 4, 'Airlines', 'Talair (Papua New Guinea)'),
('3127', 4, 'Airlines', 'TACA International'),
('3128', 4, 'Airlines', 'Airlines'),
('3129', 4, 'Airlines', 'Surinam Airways'),
('3130', 4, 'Airlines', 'Sunworld International Airways'),
('3131', 4, 'Airlines', 'VLM Airlines (Belgium)'),
('3132', 4, 'Airlines', 'Frontier Airlines (USA)'),
('3133', 4, 'Airlines', 'Sunbelt Airlines'),
('3134', 4, 'Airlines', 'Airlines'),
('3135', 4, 'Airlines', 'Sudan Airways'),
('3136', 4, 'Airlines', 'Qatar Airways'),
('3137', 4, 'Airlines', 'Singleton'),
('3138', 4, 'Airlines', 'Simmons Airlines (USA)'),
('3139', 4, 'Airlines', 'Airlines'),
('3140', 4, 'Airlines', 'Airlines'),
('3141', 4, 'Airlines', 'Airlines'),
('3142', 4, 'Airlines', 'Airlines'),
('3143', 4, 'Airlines', 'Scenic Airlines (USA)'),
('3144', 4, 'Airlines', 'Virgin Atlantic (USA)'),
('3145', 4, 'Airlines', 'San Juan Airlines'),
('3146', 4, 'Airlines', 'Luxair (Luxembourg)'),
('3147', 4, 'Airlines', 'Airlines'),
('3148', 4, 'Airlines', 'Air Littoral (France)'),
('3149', 4, 'Airlines', 'Airlines'),
('3150', 4, 'Airlines', 'Airlines'),
('3151', 4, 'Airlines', 'Air Zaire'),
('3152', 4, 'Airlines', 'Airlines'),
('3153', 4, 'Airlines', 'Airlines'),
('3154', 4, 'Airlines', 'Princeville'),
('3155', 4, 'Airlines', 'Airlines'),
('3156', 4, 'Airlines', 'GO FLY Airline'),
('3157', 4, 'Airlines', 'Airlines'),
('3158', 4, 'Airlines', 'Airlines'),
('3159', 4, 'Airlines', 'Provincetown-Boston Airways'),
('3160', 4, 'Airlines', 'Airlines'),
('3161', 4, 'Airlines', 'All Nippon Airways (Japan)'),
('3162', 4, 'Airlines', 'Airlines'),
('3163', 4, 'Airlines', 'Airlines'),
('3164', 4, 'Airlines', 'Norontair (Canada)'),
('3165', 4, 'Airlines', 'Airlines'),
('3166', 4, 'Airlines', 'Airlines'),
('3167', 4, 'Airlines', 'Aero Continente (Peru)'),
('3168', 4, 'Airlines', 'Airlines'),
('3169', 4, 'Airlines', 'Airlines'),
('3170', 4, 'Airlines', 'Mount Cook'),
('3171', 4, 'Airlines', 'Canadian Airlines'),
('3172', 4, 'Airlines', 'National Airlines (USA)'),
('3173', 4, 'Airlines', 'Airlines'),
('3174', 4, 'Airlines', 'JetBlue Airways (USA)'),
('3175', 4, 'Airlines', 'Middle East Air (Lebanon)'),
('3176', 4, 'Airlines', 'Metroflight airlines (USA)'),
('3177', 4, 'Airlines', 'AirTran Airways (USA)'),
('3178', 4, 'Airlines', 'Mesa Air (USA)'),
('3179', 4, 'Airlines', 'Airlines'),
('3180', 4, 'Airlines', 'Westjet Airlines (Canada)'),
('3181', 4, 'Airlines', 'Malev Hungarian Airlines'),
('3182', 4, 'Airlines', 'LOT - Polish Airlines'),
('3183', 4, 'Airlines', 'Oman Aviation Services'),
('3184', 4, 'Airlines', 'LIAT (Antigua and Barbuda)'),
('3185', 4, 'Airlines', 'LAV (Venezuela)'),
('3186', 4, 'Airlines', 'LAP (Paraguay)'),
('3187', 4, 'Airlines', 'Avianca Costa Rica'),
('3188', 4, 'Airlines', 'Virgin Express (Belgium)'),
('3189', 4, 'Airlines', 'Airlines'),
('3190', 4, 'Airlines', 'Jugoslav Air (Serbia)'),
('3191', 4, 'Airlines', 'Island Airlines (USA)'),
('3192', 4, 'Airlines', 'Iran Air'),
('3193', 4, 'Airlines', 'Indian Airlines'),
('3194', 4, 'Airlines', 'Airlines'),
('3195', 4, 'Airlines', 'Airlines'),
('3196', 4, 'Airlines', 'Hawaiian Airlines'),
('3197', 4, 'Airlines', 'Havasu Airlines'),
('3198', 4, 'Airlines', 'Airlines'),
('3199', 4, 'Airlines', 'Servicios Aereos Militares'),
('3200', 4, 'Airlines', 'Guyana Airways'),
('3201', 4, 'Airlines', 'Airlines'),
('3202', 4, 'Airlines', 'Airlines'),
('3203', 4, 'Airlines', 'Golden Pacific Airlines (USA)'),
('3204', 4, 'Airlines', 'Freedom Airline Express (Kenya)'),
('3205', 4, 'Airlines', 'Airlines'),
('3206', 4, 'Airlines', 'China Eastern Airlines'),
('3207', 4, 'Airlines', 'Airlines'),
('3208', 4, 'Airlines', 'Airlines'),
('3209', 4, 'Airlines', 'Airlines'),
('3210', 4, 'Airlines', 'Airlines'),
('3211', 4, 'Airlines', 'Norwegian Air Shuttle'),
('3212', 4, 'Airlines', 'Dominicana de Aviacion'),
('3213', 4, 'Airlines', 'Braathens Regional Airlines (Sweden)'),
('3214', 4, 'Airlines', 'Airlines'),
('3215', 4, 'Airlines', 'Dan-Air (United Kingdom)'),
('3216', 4, 'Airlines', 'Greater Cumberland Regional Airport'),
('3217', 4, 'Airlines', 'CSA Ceskoslovenske Aerolinie'),
('3218', 4, 'Airlines', 'Crown Airways (USA)'),
('3219', 4, 'Airlines', 'Compania Panamena de Aviacion'),
('3220', 4, 'Airlines', 'Compania Faucett (Peru)'),
('3221', 4, 'Airlines', 'Transportes Aeros Militares Ecuatorianos'),
('3222', 4, 'Airlines', 'Command Airways (USA)'),
('3223', 4, 'Airlines', 'Comair (South Africa)'),
('3224', 4, 'Airlines', 'Airlines'),
('3225', 4, 'Airlines', 'Airlines'),
('3226', 4, 'Airlines', 'Skyways Express (Sweden)'),
('3227', 4, 'Airlines', 'Airlines'),
('3228', 4, 'Airlines', 'Cayman Airways'),
('3229', 4, 'Airlines', 'Sociedad Ecuatorianas De Transportes Aereo'),
('3230', 4, 'Airlines', 'Airlines'),
('3231', 4, 'Airlines', 'Servicio Aero de Honduras'),
('3232', 4, 'Airlines', 'Airlines'),
('3233', 4, 'Airlines', 'Capitol Air'),
('3234', 4, 'Airlines', 'Caribbean Airlines / West Indies Airways'),
('3235', 4, 'Airlines', 'Brockway Air'),
('3236', 4, 'Airlines', 'Air Arabia Airline (United Arab Emirates)'),
('3237', 4, 'Airlines', 'Airlines'),
('3238', 4, 'Airlines', 'Bemidji Airlines (USA)'),
('3239', 4, 'Airlines', 'Bar Harbor Airlines (USA)'),
('3240', 4, 'Airlines', 'Bahamasair (Bahamas)'),
('3241', 4, 'Airlines', 'Avianca (Guatemala)'),
('3242', 4, 'Airlines', 'Avensa (Venezuela)'),
('3243', 4, 'Airlines', 'Austrian Airlines'),
('3244', 4, 'Airlines', 'Airlines'),
('3245', 4, 'Airlines', 'EasyJet (United Kingdom)'),
('3246', 4, 'Airlines', 'Ryanair'),
('3247', 4, 'Airlines', 'Gol Airlines (Brazil)'),
('3248', 4, 'Airlines', 'Tam Airlines (Brazil)'),
('3249', 4, 'Airlines', 'Airlines'),
('3250', 4, 'Airlines', 'Airlines'),
('3251', 4, 'Airlines', 'Aloha Airlines (USA)'),
('3252', 4, 'Airlines', 'ALM Antilean Airlines'),
('3253', 4, 'Airlines', 'America West Airlines'),
('3254', 4, 'Airlines', 'Trump Airline'),
('3255', 4, 'Airlines', 'Airlines'),
('3256', 4, 'Airlines', 'Alaska Airlines'),
('3257', 4, 'Airlines', 'Airlines'),
('3258', 4, 'Airlines', 'Airlines'),
('3259', 4, 'Airlines', 'American Trans Air'),
('3260', 4, 'Airlines', 'Spirit Airlines (USA)'),
('3261', 4, 'Airlines', 'Air China'),
('3262', 4, 'Airlines', 'Reno Air, Inc. / American Airlines'),
('3263', 4, 'Airlines', 'Aserca Airlines / Aero Servicio Carabobo (Venezuela)'),
('3264', 4, 'Airlines', 'Airlines'),
('3265', 4, 'Airlines', 'Airlines'),
('3266', 4, 'Airlines', 'Air Seychelles'),
('3267', 4, 'Airlines', 'Air Panama International'),
('3268', 4, 'Airlines', 'Airlines'),
('3269', 4, 'Airlines', 'Airlines'),
('3270', 4, 'Airlines', 'Airlines'),
('3271', 4, 'Airlines', 'Airlines'),
('3272', 4, 'Airlines', 'Airlines'),
('3273', 4, 'Airlines', 'Airlines'),
('3274', 4, 'Airlines', 'Airlines'),
('3275', 4, 'Airlines', 'Airlines'),
('3276', 4, 'Airlines', 'Airlines'),
('3277', 4, 'Airlines', 'Airlines'),
('3278', 4, 'Airlines', 'Airlines'),
('3279', 4, 'Airlines', 'Airlines'),
('3280', 4, 'Airlines', 'Air Jamaica'),
('3281', 4, 'Airlines', 'Air Djibouti'),
('3282', 4, 'Airlines', 'Air Djibouti'),
('3283', 4, 'Airlines', 'Airlines'),
('3284', 4, 'Airlines', 'Aero Virgin Islands'),
('3285', 4, 'Airlines', 'Aero Peru'),
('3286', 4, 'Airlines', 'Aero Nicaraguenses'),
('3287', 4, 'Airlines', 'Aero Coach Aviation'),
('3288', 4, 'Airlines', 'Airlines'),
('3289', 4, 'Airlines', 'Airlines'),
('3290', 4, 'Airlines', 'Airlines'),
('3291', 4, 'Airlines', 'Ariana Afghan Airlines'),
('3292', 4, 'Airlines', 'Cyprus Airways'),
('3293', 4, 'Airlines', 'Ecuatoriana de Aviación'),
('3294', 4, 'Airlines', 'Ethiopian Airlines'),
('3295', 4, 'Airlines', 'Kenya Airways'),
('3296', 4, 'Airlines', 'Air Berlin'),
('3297', 4, 'Airlines', 'TAROM / Romanian Air Transport'),
('3298', 4, 'Airlines', 'Air Mauritius'),
('3299', 4, 'Airlines', 'Wideroes Flyveselskap (Norway)'),
('3300', 4, 'Airlines', 'Azul Airlines (Brazil)'),
('3301', 4, 'Airlines', 'Wizz Air (Hungary)'),
('3302', 4, 'Airlines', 'Flybe Air (United Kingdom)'),
('3351', 5, 'Car rent', 'Affiliated Auto Rental'),
('3352', 5, 'Car rent', 'American Intl Rent-a-car'),
('3353', 5, 'Car rent', 'Brooks Rent-a-car'),
('3354', 5, 'Car rent', 'Action Auto Rental'),
('3355', 5, 'Car rent', 'Car rental agencies'),
('3356', 5, 'Car rent', 'Car rental agencies'),
('3357', 5, 'Car rent', 'Hertz Rent-a-car'),
('3358', 5, 'Car rent', 'Car rental agencies'),
('3359', 5, 'Car rent', 'Payless Car Rental'),
('3360', 5, 'Car rent', 'Snappy Car Rental'),
('3361', 5, 'Car rent', 'Airways Rent-a-car'),
('3362', 5, 'Car rent', 'Altra Auto Rental'),
('3363', 5, 'Car rent', 'Car rental agencies'),
('3364', 5, 'Car rent', 'Agency Rent-a-car'),
('3365', 5, 'Car rent', 'Car rental agencies'),
('3366', 5, 'Car rent', 'Budget Rent a Car'),
('3367', 5, 'Car rent', 'Car rental agencies'),
('3368', 5, 'Car rent', 'Holiday Rent-a-wreck'),
('3369', 5, 'Car rent', 'Car rental agencies'),
('3370', 5, 'Car rent', 'Rent-a-wreck'),
('3371', 5, 'Car rent', 'Car rental agencies'),
('3372', 5, 'Car rent', 'Car rental agencies'),
('3373', 5, 'Car rent', 'Car rental agencies'),
('3374', 5, 'Car rent', 'Car rental agencies'),
('3375', 5, 'Car rent', 'Car rental agencies'),
('3376', 5, 'Car rent', 'Ajax Rent-a-car'),
('3377', 5, 'Car rent', 'Car rental agencies'),
('3378', 5, 'Car rent', 'Car rental agencies'),
('3379', 5, 'Car rent', 'Car rental agencies'),
('3380', 5, 'Car rent', 'Car rental agencies'),
('3381', 5, 'Car rent', 'Europ Car'),
('3382', 5, 'Car rent', 'Car rental agencies'),
('3383', 5, 'Car rent', 'Car rental agencies'),
('3384', 5, 'Car rent', 'Car rental agencies'),
('3385', 5, 'Car rent', 'Tropical Rent-a-car'),
('3386', 5, 'Car rent', 'Showcase Rental Cars'),
('3387', 5, 'Car rent', 'Alamo Rent-a-car'),
('3388', 5, 'Car rent', 'Car rental agencies'),
('3389', 5, 'Car rent', 'Avis Rent-a-car'),
('3390', 5, 'Car rent', 'Dollar Rent-a-car'),
('3391', 5, 'Car rent', 'Europe By Car'),
('3392', 5, 'Car rent', 'Car rental agencies'),
('3393', 5, 'Car rent', 'National Car Rental'),
('3394', 5, 'Car rent', 'Kemwell Group Rent-a-car'),
('3395', 5, 'Car rent', 'Thrifty Rent-a-car'),
('3396', 5, 'Car rent', 'Tilden Tent-a-car'),
('3397', 5, 'Car rent', 'Car rental agencies'),
('3398', 5, 'Car rent', 'Econo-car Rent-a-car'),
('3399', 5, 'Car rent', 'Amerex Rent-a-Car'),
('3400', 5, 'Car rent', 'Auto Host Cost Car Rentals'),
('3401', 5, 'Car rent', 'Car rental agencies'),
('3402', 5, 'Car rent', 'Car rental agencies'),
('3403', 5, 'Car rent', 'Car rental agencies'),
('3404', 5, 'Car rent', 'Car rental agencies'),
('3405', 5, 'Car rent', 'Enterprise Rent-a-car'),
('3406', 5, 'Car rent', 'Car rental agencies'),
('3407', 5, 'Car rent', 'Car rental agencies'),
('3408', 5, 'Car rent', 'Car rental agencies'),
('3409', 5, 'Car rent', 'General Rent-a-car'),
('3410', 5, 'Car rent', 'Car rental agencies'),
('3411', 5, 'Car rent', 'Car rental agencies'),
('3412', 5, 'Car rent', 'A-1 Rent-a-car'),
('3413', 5, 'Car rent', 'Car rental agencies'),
('3414', 5, 'Car rent', 'Godfrey Natl Rent-a-car'),
('3415', 5, 'Car rent', 'Car rental agencies'),
('3416', 5, 'Car rent', 'Car rental agencies'),
('3417', 5, 'Car rent', 'Car rental agencies'),
('3418', 5, 'Car rent', 'Car rental agencies'),
('3419', 5, 'Car rent', 'Alpha Rent-a-car'),
('3420', 5, 'Car rent', 'Ansa Intl Rent-a-car'),
('3421', 5, 'Car rent', 'Allstae Rent-a-car'),
('3422', 5, 'Car rent', 'Car rental agencies'),
('3423', 5, 'Car rent', 'Avcar Rent-a-car'),
('3424', 5, 'Car rent', 'Car rental agencies'),
('3425', 5, 'Car rent', 'Automate Rent-a-car'),
('3426', 5, 'Car rent', 'Car rental agencies'),
('3427', 5, 'Car rent', 'Avon Rent-a-car'),
('3428', 5, 'Car rent', 'Carey Rent-a-car'),
('3429', 5, 'Car rent', 'Insurance Rent-a-car'),
('3430', 5, 'Car rent', 'Major Rent-a-car'),
('3431', 5, 'Car rent', 'Replacement Rent-a-car'),
('3432', 5, 'Car rent', 'Reserve Rent-a-car'),
('3433', 5, 'Car rent', 'Ugly Duckling Rent-a-car'),
('3434', 5, 'Car rent', 'USA Rent-a-car'),
('3435', 5, 'Car rent', 'Value Rent-a-car'),
('3436', 5, 'Car rent', 'Autohansa Rent-a-car'),
('3437', 5, 'Car rent', 'Cite Rent-a-car'),
('3438', 5, 'Car rent', 'Interent Rent-a-car'),
('3439', 5, 'Car rent', 'Milleville Rent-a-car'),
('3440', 5, 'Car rent', 'Via Route Rent-a-Car'),
('3441', 5, 'Car rent', 'Car rental agencies'),
('3501', 6, 'Hotels and resorts', 'Holiday Inns'),
('3502', 6, 'Hotels and resorts', 'Best Western Hotels & Resorts'),
('3503', 6, 'Hotels and resorts', 'Sheraton Hotels and Resorts'),
('3504', 6, 'Hotels and resorts', 'Hilton Hotels & Resorts'),
('3505', 6, 'Hotels and resorts', 'Rocco Forte Hotels'),
('3506', 6, 'Hotels and resorts', 'Golden Tulip Hotels'),
('3507', 6, 'Hotels and resorts', 'Friendship Inns'),
('3508', 6, 'Hotels and resorts', 'Quality Inns'),
('3509', 6, 'Hotels and resorts', 'Marriott Hotels'),
('3510', 6, 'Hotels and resorts', 'Days Inn'),
('3511', 6, 'Hotels and resorts', 'Arabella Hotels'),
('3512', 6, 'Hotels and resorts', 'Inter-continental Hotels'),
('3513', 6, 'Hotels and resorts', 'Westin Hotels & Resorts'),
('3514', 6, 'Hotels and resorts', 'AmeriSuites Hotels'),
('3515', 6, 'Hotels and resorts', 'Rodeway Inns'),
('3516', 6, 'Hotels and resorts', 'La Quinta Motor Inns'),
('3517', 6, 'Hotels and resorts', 'Americana Hotels'),
('3518', 6, 'Hotels and resorts', 'Sol Hotels'),
('3519', 6, 'Hotels and resorts', 'Pullman International Hotels'),
('3520', 6, 'Hotels and resorts', 'Meridien Hotels'),
('3521', 6, 'Hotels and resorts', 'Forte Crest Hotels'),
('3522', 6, 'Hotels and resorts', 'Tokyo Hotel'),
('3523', 6, 'Hotels and resorts', 'Peninsula Hotels'),
('3524', 6, 'Hotels and resorts', 'Welcomgroup Hotels'),
('3525', 6, 'Hotels and resorts', 'Dunfey Hotels'),
('3526', 6, 'Hotels and resorts', 'Prince Hotels'),
('3527', 6, 'Hotels and resorts', 'Downtowner-passport Hotel'),
('3528', 6, 'Hotels and resorts', 'Red Lion Hotels'),
('3529', 6, 'Hotels and resorts', 'Canadian Pacific Hotels'),
('3530', 6, 'Hotels and resorts', 'Renaissance Hotels'),
('3531', 6, 'Hotels and resorts', 'Astir Hotels'),
('3532', 6, 'Hotels and resorts', 'Sun Route Hotels'),
('3533', 6, 'Hotels and resorts', 'Hotel Ibis'),
('3534', 6, 'Hotels and resorts', 'Southern Pacific Hotels'),
('3535', 6, 'Hotels and resorts', 'Hilton International'),
('3536', 6, 'Hotels and resorts', 'Amfac Hotels'),
('3537', 6, 'Hotels and resorts', 'ANA Hotel'),
('3538', 6, 'Hotels and resorts', 'Concorde Hotels'),
('3539', 6, 'Hotels and resorts', 'Summerfield Suites Hotels'),
('3540', 6, 'Hotels and resorts', 'Iberotel Hotels'),
('3541', 6, 'Hotels and resorts', 'Okura Hotels & Resorts'),
('3542', 6, 'Hotels and resorts', 'Royal Hotels'),
('3543', 6, 'Hotels and resorts', 'Four Seasons Hotels'),
('3544', 6, 'Hotels and resorts', 'Ciga Hotels'),
('3545', 6, 'Hotels and resorts', 'Shangri-La Hotels and Resorts'),
('3546', 6, 'Hotels and resorts', 'Hotel Sierra'),
('3547', 6, 'Hotels and resorts', 'Breakers Resort'),
('3548', 6, 'Hotels and resorts', 'Melia Hotels International'),
('3549', 6, 'Hotels and resorts', 'Auberge Des Governeurs'),
('3550', 6, 'Hotels and resorts', 'Regal 8 Inns'),
('3551', 6, 'Hotels and resorts', 'Mirage Hotels and Casino'),
('3552', 6, 'Hotels and resorts', 'Coast Hotels'),
('3553', 6, 'Hotels and resorts', 'Park Inns International'),
('3554', 6, 'Hotels and resorts', 'Pinehurst Resort'),
('3555', 6, 'Hotels and resorts', 'Treasure Island Hotel and Casino'),
('3556', 6, 'Hotels and resorts', 'Barton Creek Resort'),
('3557', 6, 'Hotels and resorts', 'Manhattan East Suite Hotels'),
('3558', 6, 'Hotels and resorts', 'Jolly Hotels'),
('3559', 6, 'Hotels and resorts', 'Candleood Suites'),
('3560', 6, 'Hotels and resorts', 'Alladin Resort and Casino'),
('3561', 6, 'Hotels and resorts', 'Golden Nugget'),
('3562', 6, 'Hotels and resorts', 'Comfort Inns'),
('3563', 6, 'Hotels and resorts', 'Journey’s End Motеls'),
('3564', 6, 'Hotels and resorts', 'Sam Town Hotel and Casino'),
('3565', 6, 'Hotels and resorts', 'Relax Inns'),
('3566', 6, 'Hotels and resorts', 'Garden Place Hotel'),
('3567', 6, 'Hotels and resorts', 'Soho Grand Hotel'),
('3568', 6, 'Hotels and resorts', 'Ladbroke Hotels'),
('3569', 6, 'Hotels and resorts', 'Tribeca Grand Hotels'),
('3570', 6, 'Hotels and resorts', 'Grand Met Forum Hotels'),
('3571', 6, 'Hotels and resorts', 'Grand Wailea Hotels'),
('3572', 6, 'Hotels and resorts', 'Miyako Hotels & Resorts'),
('3573', 6, 'Hotels and resorts', 'Sandman Hotels'),
('3574', 6, 'Hotels and resorts', 'Venture Inns'),
('3575', 6, 'Hotels and resorts', 'Vagabond Hotels'),
('3576', 6, 'Hotels and resorts', 'La Quinta Resort'),
('3577', 6, 'Hotels and resorts', 'Mandarin Oriental Hotel'),
('3578', 6, 'Hotels and resorts', 'Bavarian Inn Lodge'),
('3579', 6, 'Hotels and resorts', 'Hotel Mercure'),
('3580', 6, 'Hotels and resorts', 'Hotel Del Coronado'),
('3581', 6, 'Hotels and resorts', 'Delta Hotels'),
('3582', 6, 'Hotels and resorts', 'California Hotel and Casino'),
('3583', 6, 'Hotels and resorts', 'Radisson Blue Hotel'),
('3584', 6, 'Hotels and resorts', 'Princess Hotels International'),
('3585', 6, 'Hotels and resorts', 'Hungary Hotels'),
('3586', 6, 'Hotels and resorts', 'Sokos Hotels'),
('3587', 6, 'Hotels and resorts', 'Doral Hotels'),
('3588', 6, 'Hotels and resorts', 'Helmsley Hotels'),
('3589', 6, 'Hotels and resorts', 'Doral Golf Resort'),
('3590', 6, 'Hotels and resorts', 'Fairmont Hotels'),
('3591', 6, 'Hotels and resorts', 'Sonesta Hotels'),
('3592', 6, 'Hotels and resorts', 'Omni Hotels & Resorts'),
('3593', 6, 'Hotels and resorts', 'Cunard Hotels'),
('3594', 6, 'Hotels and resorts', 'Arizona Biltmore, A Waldorf Astoria Resort'),
('3595', 6, 'Hotels and resorts', 'Hospitality International'),
('3596', 6, 'Hotels and resorts', 'Wynn Las Vegas'),
('3597', 6, 'Hotels and resorts', 'Riverside Resort and Casino'),
('3598', 6, 'Hotels and resorts', 'Regent Hotels & Resorts'),
('3599', 6, 'Hotels and resorts', 'Pannonia Hotels'),
('3600', 6, 'Hotels and resorts', 'Saddlebrook Resort'),
('3601', 6, 'Hotels and resorts', 'TradeWinds Island Grand Resort'),
('3602', 6, 'Hotels and resorts', 'Hudson Hotel'),
('3603', 6, 'Hotels and resorts', 'Noah''s Ark Hotel and Resort'),
('3604', 6, 'Hotels and resorts', 'Hilton Garden Inn'),
('3605', 6, 'Hotels and resorts', 'Jurys Inn'),
('3606', 6, 'Hotels and resorts', 'Jefferson Hotel'),
('3607', 6, 'Hotels and resorts', 'Fontainebleau Resort'),
('3608', 6, 'Hotels and resorts', 'Gaylord Opryland Resort'),
('3609', 6, 'Hotels and resorts', 'Gaylord Palms Resort'),
('3610', 6, 'Hotels and resorts', 'Gaylord Texan Resort'),
('3611', 6, 'Hotels and resorts', 'C''mon Inn Hotel & Suites'),
('3612', 6, 'Hotels and resorts', 'Movenpick Hotels & Resorts'),
('3613', 6, 'Hotels and resorts', 'Microtel Inn and Suites'),
('3614', 6, 'Hotels and resorts', 'AmericInn'),
('3615', 6, 'Hotels and resorts', 'Travelodge Hotels'),
('3616', 6, 'Hotels and resorts', 'Hermitage Hotels'),
('3617', 6, 'Hotels and resorts', 'America’s Best Value Inn'),
('3618', 6, 'Hotels and resorts', 'Great Wolf Resorts'),
('3619', 6, 'Hotels and resorts', 'Aloft Hotels'),
('3620', 6, 'Hotels and resorts', 'Binions Horseshoe Club'),
('3621', 6, 'Hotels and resorts', 'Extended Stay'),
('3622', 6, 'Hotels and resorts', 'Merlin Hotel (Perth)'),
('3623', 6, 'Hotels and resorts', 'Dorint Hotels & Resort'),
('3624', 6, 'Hotels and resorts', 'Lady Luck Hotel and Casino'),
('3625', 6, 'Hotels and resorts', 'Hotel Universal'),
('3626', 6, 'Hotels and resorts', 'Prince Hotels / Studio Plus Hotel'),
('3627', 6, 'Hotels and resorts', 'Extended Stay America'),
('3628', 6, 'Hotels and resorts', 'Excalibur Hotel and Casino'),
('3629', 6, 'Hotels and resorts', 'Dan Hotels'),
('3630', 6, 'Hotels and resorts', 'Extended Stay Deluxe'),
('3631', 6, 'Hotels and resorts', 'Sleep Inn'),
('3632', 6, 'Hotels and resorts', 'The Phoenician Resort'),
('3633', 6, 'Hotels and resorts', 'Rank Hotels'),
('3634', 6, 'Hotels and resorts', 'Swissôtel Hotels & Resorts'),
('3635', 6, 'Hotels and resorts', 'Reso Hotels'),
('3636', 6, 'Hotels and resorts', 'Sarova Hotels'),
('3637', 6, 'Hotels and resorts', 'Ramada Inns'),
('3638', 6, 'Hotels and resorts', 'Howard Johnson Hotels'),
('3639', 6, 'Hotels and resorts', 'Mount Charlotte Hotels'),
('3640', 6, 'Hotels and resorts', 'Hyatt Hotels/International'),
('3641', 6, 'Hotels and resorts', 'Sofitel Hotels & Resorts'),
('3642', 6, 'Hotels and resorts', 'Novotel Sieh (Accor)'),
('3643', 6, 'Hotels and resorts', 'Steigenberger Hotels and Resorts'),
('3644', 6, 'Hotels and resorts', 'Econo-Travel Motor Hotel'),
('3645', 6, 'Hotels and resorts', 'Queens Moat Houses'),
('3646', 6, 'Hotels and resorts', 'Swallow Hotels'),
('3647', 6, 'Hotels and resorts', 'HUSA Hotels'),
('3648', 6, 'Hotels and resorts', 'De Vere Hotels'),
('3649', 6, 'Hotels and resorts', 'Radisson Hotels'),
('3650', 6, 'Hotels and resorts', 'Red Roof Inns'),
('3651', 6, 'Hotels and resorts', 'Imperial London Hotels'),
('3652', 6, 'Hotels and resorts', 'Embassy Suites Hotels by Hilton'),
('3653', 6, 'Hotels and resorts', 'Penta Hotels'),
('3654', 6, 'Hotels and resorts', 'Loews Hotels'),
('3655', 6, 'Hotels and resorts', 'Scandic Hotels'),
('3656', 6, 'Hotels and resorts', 'Sara Hotels'),
('3657', 6, 'Hotels and resorts', 'Oberoi Hotels & Resorts'),
('3658', 6, 'Hotels and resorts', 'New Otani Hotels'),
('3659', 6, 'Hotels and resorts', 'Taj Hotels Intl'),
('3660', 6, 'Hotels and resorts', 'Knights Inn'),
('3661', 6, 'Hotels and resorts', 'Metropole Hotel and SPA'),
('3662', 6, 'Hotels and resorts', 'Circus Circus Hotel and Casino'),
('3663', 6, 'Hotels and resorts', 'Hoteles El Presidente'),
('3664', 6, 'Hotels and resorts', 'Flag Inns'),
('3665', 6, 'Hotels and resorts', 'Hampton Inns by Hilton'),
('3666', 6, 'Hotels and resorts', 'Stakis Hotels'),
('3667', 6, 'Hotels and resorts', 'Luxor Hotel and Casino'),
('3668', 6, 'Hotels and resorts', 'Maritim'),
('3669', 6, 'Hotels and resorts', 'Eldorado Hotel and Casino'),
('3670', 6, 'Hotels and resorts', 'Arcade Hotel'),
('3671', 6, 'Hotels and resorts', 'Arctia Hotels'),
('3672', 6, 'Hotels and resorts', 'Campanile Hotel'),
('3673', 6, 'Hotels and resorts', 'Ibusz Hotels'),
('3674', 6, 'Hotels and resorts', 'Rantasipi Hotels'),
('3675', 6, 'Hotels and resorts', 'Interhotel Cedok'),
('3676', 6, 'Hotels and resorts', 'Monte Carlo Hotel and Casino'),
('3677', 6, 'Hotels and resorts', 'Climat De France Hotels'),
('3678', 6, 'Hotels and resorts', 'Cumulus Hotels'),
('3679', 6, 'Hotels and resorts', 'Silver Legacy Hotel and Casino'),
('3680', 6, 'Hotels and resorts', 'Hoteis Othan'),
('3681', 6, 'Hotels and resorts', 'Adams Mark Hotels'),
('3682', 6, 'Hotels and resorts', 'Sahara Hotel and Casino'),
('3683', 6, 'Hotels and resorts', 'Bradbury Suites'),
('3684', 6, 'Hotels and resorts', 'Budget Host Hotels'),
('3685', 6, 'Hotels and resorts', 'Budgetel'),
('3686', 6, 'Hotels and resorts', 'Suisse Chalet Hotels'),
('3687', 6, 'Hotels and resorts', 'Clarion Hotels'),
('3688', 6, 'Hotels and resorts', 'Compri Hotel Bucks County'),
('3689', 6, 'Hotels and resorts', 'Consort Hotel'),
('3690', 6, 'Hotels and resorts', 'Courtyard by Marriott Hotel'),
('3691', 6, 'Hotels and resorts', 'Dillon Inn'),
('3692', 6, 'Hotels and resorts', 'DoubleTree by Hilton'),
('3693', 6, 'Hotels and resorts', 'Drury Hotels'),
('3694', 6, 'Hotels and resorts', 'Economy Inns Of America'),
('3695', 6, 'Hotels and resorts', 'Embassy Suites by Hilton'),
('3696', 6, 'Hotels and resorts', 'Excel Inn'),
('3697', 6, 'Hotels and resorts', 'Fairfield Hotel by Marriott'),
('3698', 6, 'Hotels and resorts', 'Harley Hotel'),
('3699', 6, 'Hotels and resorts', 'Midway Motor Lodge'),
('3700', 6, 'Hotels and resorts', 'Motel 6'),
('3701', 6, 'Hotels and resorts', 'La Mansion Del Rio'),
('3702', 6, 'Hotels and resorts', 'Registry Hotels'),
('3703', 6, 'Hotels and resorts', 'Residence Inn by Marriott'),
('3704', 6, 'Hotels and resorts', 'Royce Hotel'),
('3705', 6, 'Hotels and resorts', 'Sandman Inn'),
('3706', 6, 'Hotels and resorts', 'Shilo Inn'),
('3707', 6, 'Hotels and resorts', 'Shoneys Inn'),
('3708', 6, 'Hotels and resorts', 'Virgin River Hotel and Casino'),
('3709', 6, 'Hotels and resorts', 'Super 8 Motel'),
('3710', 6, 'Hotels and resorts', 'Ritz-Carlton Hotel'),
('3711', 6, 'Hotels and resorts', 'Flag Inns (Australia)'),
('3712', 6, 'Hotels and resorts', 'Buffalo Bills Hotel and Casino'),
('3713', 6, 'Hotels and resorts', 'Quality Pacific Hotel'),
('3714', 6, 'Hotels and resorts', 'Four Seasons Hotels (Australia)'),
('3715', 6, 'Hotels and resorts', 'Fairfield Inn'),
('3716', 6, 'Hotels and resorts', 'Carlton Hotels'),
('3717', 6, 'Hotels and resorts', 'City Lodge Hotels'),
('3718', 6, 'Hotels and resorts', 'Karos Hotels'),
('3719', 6, 'Hotels and resorts', 'Protea Hotels by Marriott'),
('3720', 6, 'Hotels and resorts', 'Southern Sun Hotels'),
('3721', 6, 'Hotels and resorts', 'Conrad Hotels'),
('3722', 6, 'Hotels and resorts', 'Wyndham Hotels & Resorts'),
('3723', 6, 'Hotels and resorts', 'Rica Hotels'),
('3724', 6, 'Hotels and resorts', 'Inter Nor Hotels'),
('3725', 6, 'Hotels and resorts', 'Sea Pines Resort'),
('3726', 6, 'Hotels and resorts', 'Rio Suites'),
('3727', 6, 'Hotels and resorts', 'Broadmoor Hotel'),
('3728', 6, 'Hotels and resorts', 'Ballys Hotel and Casino'),
('3729', 6, 'Hotels and resorts', 'Nugget Casino Resort'),
('3730', 6, 'Hotels and resorts', 'MGM Grand Hotel'),
('3731', 6, 'Hotels and resorts', 'Harrah’s Hotels and Casinos'),
('3732', 6, 'Hotels and resorts', 'Opryland Hotel'),
('3733', 6, 'Hotels and resorts', 'Boca Raton Resort and Club'),
('3734', 6, 'Hotels and resorts', 'Harvey Bristol Hotels'),
('3735', 6, 'Hotels and resorts', 'Masters Economy Inns'),
('3736', 6, 'Hotels and resorts', 'Colorado Belle Edgewater Resort'),
('3737', 6, 'Hotels and resorts', 'Riviera Hotel and Casino'),
('3738', 6, 'Hotels and resorts', 'Tropicana Resort and Casino'),
('3739', 6, 'Hotels and resorts', 'Woodside Hotels and Resorts'),
('3740', 6, 'Hotels and resorts', 'Towneplace Suites'),
('3741', 6, 'Hotels and resorts', 'Millennium Times Square New York'),
('3742', 6, 'Hotels and resorts', 'Club Med'),
('3743', 6, 'Hotels and resorts', 'Atlanta Biltmore Hotel and Apartments'),
('3744', 6, 'Hotels and resorts', 'Carefree Resorts'),
('3745', 6, 'Hotels and resorts', 'St. Regis Hotel'),
('3746', 6, 'Hotels and resorts', 'The Eliot Hotel'),
('3747', 6, 'Hotels and resorts', 'Club Corporation / Club Resorts'),
('3748', 6, 'Hotels and resorts', 'Wellesley Inns'),
('3749', 6, 'Hotels and resorts', 'Beverly Hills Hotel'),
('3750', 6, 'Hotels and resorts', 'Crowne Plaza Hotels'),
('3751', 6, 'Hotels and resorts', 'Homewood Suites by Hilton'),
('3752', 6, 'Hotels and resorts', 'Peabody Hotels'),
('3753', 6, 'Hotels and resorts', 'Greenbriar Resorts'),
('3754', 6, 'Hotels and resorts', 'Amelia Island Plantation'),
('3755', 6, 'Hotels and resorts', 'Homestead Hotels'),
('3756', 6, 'Hotels and resorts', 'South Seas Island Resort'),
('3757', 6, 'Hotels and resorts', 'Canyon Ranch'),
('3758', 6, 'Hotels and resorts', 'Kahala Mandarin Oriental Hotel'),
('3759', 6, 'Hotels and resorts', 'Orchid At Mauna Lani'),
('3760', 6, 'Hotels and resorts', 'Halekulani Hotel / Waikiki Parc'),
('3761', 6, 'Hotels and resorts', 'Primadonna Hotel and Casino'),
('3762', 6, 'Hotels and resorts', 'Whiskey Pete’s Hotel and Casino'),
('3763', 6, 'Hotels and resorts', 'Chateau Elan Winery and Resort'),
('3764', 6, 'Hotels and resorts', 'Beau Rivage Hotel and Casino'),
('3765', 6, 'Hotels and resorts', 'Bellagio Resort and Casino'),
('3766', 6, 'Hotels and resorts', 'Fremont Hotel and Casino'),
('3767', 6, 'Hotels and resorts', 'Main Street Station Casino Brewery Hotel'),
('3768', 6, 'Hotels and resorts', 'Silver Star Hotel and Casino'),
('3769', 6, 'Hotels and resorts', 'Stratosphere Hotel and Casino'),
('3770', 6, 'Hotels and resorts', 'Springhill Suites'),
('3771', 6, 'Hotels and resorts', 'Caesars Hotel and Casino'),
('3772', 6, 'Hotels and resorts', 'Nemacolin Woodlands'),
('3773', 6, 'Hotels and resorts', 'Venetian Resort Hotel and Casino'),
('3774', 6, 'Hotels and resorts', 'New York-New York Hotel & Casino'),
('3775', 6, 'Hotels and resorts', 'Sands Resort'),
('3776', 6, 'Hotels and resorts', 'Nevele Grande Resort and Country Club'),
('3777', 6, 'Hotels and resorts', 'Mandalay Bay Resort'),
('3778', 6, 'Hotels and resorts', 'Four Points Hotels'),
('3779', 6, 'Hotels and resorts', 'W Hotels'),
('3780', 6, 'Hotels and resorts', 'Disneyland Resorts'),
('3781', 6, 'Hotels and resorts', 'Patricia Grand Resort Hotels'),
('3782', 6, 'Hotels and resorts', 'Rosen Hotel and Resorts'),
('3783', 6, 'Hotels and resorts', 'Town and Country Resort and Convention Center'),
('3784', 6, 'Hotels and resorts', 'First Hospitality Hotels'),
('3785', 6, 'Hotels and resorts', 'Outrigger Hotels and Resorts '),
('3786', 6, 'Hotels and resorts', 'Ohana Hotels of Hawaii'),
('3787', 6, 'Hotels and resorts', 'Caribe Royal Orlando Resort Suite and Villas'),
('3788', 6, 'Hotels and resorts', 'Ala Moana Honolulu by Mantra'),
('3789', 6, 'Hotels and resorts', 'Smugglers Notch Resort'),
('3790', 6, 'Hotels and resorts', 'Raffles Hotels & Resorts'),
('3791', 6, 'Hotels and resorts', 'Staybridge Suites'),
('3792', 6, 'Hotels and resorts', 'Claridge Casino Hotel'),
('3793', 6, 'Hotels and resorts', 'The Flamingo Hotels'),
('3794', 6, 'Hotels and resorts', 'Grand Casino Hotel & Resort'),
('3795', 6, 'Hotels and resorts', 'Paris Las Vegas Hotel'),
('3796', 6, 'Hotels and resorts', 'Peppermill Hotel Casino'),
('3797', 6, 'Hotels and resorts', 'The Atlantic Club Casino Hotel'),
('3798', 6, 'Hotels and resorts', 'Embassy Vacation Resort'),
('3799', 6, 'Hotels and resorts', 'Hale Koa Hotel'),
('3800', 6, 'Hotels and resorts', 'Homestead Suites'),
('3801', 6, 'Hotels and resorts', 'Wilderness Hotel and Resort'),
('3802', 6, 'Hotels and resorts', 'The Palace Hotel'),
('3803', 6, 'Hotels and resorts', 'The Wigwam Golf Resort and Spa'),
('3804', 6, 'Hotels and resorts', 'The Diplomat Country Club and Spa'),
('3805', 6, 'Hotels and resorts', 'The Atlantic Hotel'),
('3806', 6, 'Hotels and resorts', 'Princeville Resort'),
('3807', 6, 'Hotels and resorts', 'Element Hotel'),
('3808', 6, 'Hotels and resorts', 'LXR (Luxury Resorts)'),
('3809', 6, 'Hotels and resorts', 'Settle Inn'),
('3810', 6, 'Hotels and resorts', 'La Costa Resort'),
('3811', 6, 'Hotels and resorts', 'Premier Travel Inns'),
('3812', 6, 'Hotels and resorts', 'Hyatt Place'),
('3813', 6, 'Hotels and resorts', 'Hotel Indigo'),
('3814', 6, 'Hotels and resorts', 'The Roosevelt Hotel NY'),
('3815', 6, 'Hotels and resorts', 'Nickelodeon Family Suites by Holiday Inn'),
('3816', 6, 'Hotels and resorts', 'Home2 Suites by Hilton'),
('3817', 6, 'Hotels and resorts', 'Affinia Hotels'),
('3818', 6, 'Hotels and resorts', 'Mainstay Suites'),
('3819', 6, 'Hotels and resorts', 'Oxford Suites'),
('3820', 6, 'Hotels and resorts', 'Jumeirah Essex House'),
('3821', 6, 'Hotels and resorts', 'Caribe Royal Orlando Resort Suite and Villas'),
('3822', 6, 'Hotels and resorts', 'Crossland Economy Studios Hotels'),
('3823', 6, 'Hotels and resorts', 'Grand Sierra Resort'),
('3824', 6, 'Hotels and resorts', 'Aria Hotels'),
('3825', 6, 'Hotels and resorts', 'Vdara Hotel & Spa'),
('3826', 6, 'Hotels and resorts', 'Hotel am Steinplatz'),
('3827', 6, 'Hotels and resorts', 'The Galt House Hotel by Wyndham'),
('3828', 6, 'Hotels and resorts', 'Cosmopolitan of Las Vegas'),
('3829', 6, 'Hotels and resorts', 'Country Inn By Carlson'),
('3830', 6, 'Hotels and resorts', 'Park Plaza Hotel'),
('3831', 6, 'Hotels and resorts', 'Waldorf Astoria Hotels & Resorts'),
('3832', 6, 'Hotels and resorts', 'Curio Hotels Country Inn by Hilton'),
('3833', 6, 'Hotels and resorts', 'Canopy Hotels by Hilton'),
('3834', 6, 'Hotels and resorts', 'Baymont Inn & Suites'),
('3835', 6, 'Hotels and resorts', 'Dolce Hotels and Resorts'),
('3836', 6, 'Hotels and resorts', 'Hawthorn by Wyndham'),
('3837', 6, 'Hotels and resorts', 'Hoshino Resorts'),
('3838', 6, 'Hotels and resorts', 'Kimpton Hotels'),
('3882', 7, 'Сashing', 'Cash collection (cashing)'),
('4011', 8, 'Railway', 'Railroads - Freight'),
('4111', 8, 'Passenger transportation', 'Transportation-Suburban and Local Commuter Passenger, including Ferries'),
('4112', 8, 'Passenger railways', 'Passenger Railways'),
('4119', 8, 'Ambulance', 'Ambulance Services'),
('4121', 8, 'Taxi', 'Taxicabs and Limousines'),
('4131', 8, 'Transportation. Bus', 'Bus Lines'),
('4214', 8, 'Transportation. Delivery', 'Motor Freight Carriers,Trucking-Local/Long Distance, Moving and Storage Companies, Local Delivery'),
('4215', 8, 'Delivery service', 'Courier Services - Air and Ground, Freight Forwarders'),
('4225', 8, 'Storage', 'Public Warehousing-Farm Products, Refrigerated Goods, Household Goods Storage'),
('4304', 7, 'Miscellaneous', 'Miscellaneous'),
('4411', 8, 'Cruise Lines', 'Cruise Lines'),
('4457', 8, 'Boat Rentals', 'Boat Leases and Boat Rentals'),
('4468', 8, 'Yachting service', 'Marinas, Marine Service/Supplies'),
('4511', 4, 'Airlines', 'Air Carriers, Airlines'),
('4582', 8, 'Airports', 'Airports, Airport Terminals, Flying Fields'),
('4722', 8, 'Tourism', 'Travel Agencies and Tour Operators'),
('4723', 8, 'Tour operators', 'Package Tour Operators (Germany Only)'),
('4729', 8, 'Transportation Services', 'Passenger transportation services'),
('4761', 8, 'Telemarketing', 'Telemarketing of Travel Related Services and Vitamins'),
('4784', 8, 'Toll roads', 'Bridge and Road Fees, Tolls'),
('4785', 7, 'Miscellaneous', 'Miscellaneous'),
('4789', 8, 'Railway', 'Transportation Services'),
('4812', 9, 'Telecommunication equipment', 'Telecommunication Equipment Including Telephone Sales'),
('4813', 9, 'Retail outlets with telephony', 'Key-Entry Telecom Merchant providing single local and long-distance phone calls using a central access number in a non-face-to-face environment using key entry'),
('4814', 9, 'Mobile connection', 'Telecommunication Services'),
('4815', 9, 'Telephone services', 'Telephone services'),
('4816', 9, 'Information Services', 'Computer Network/Information Services'),
('4821', 9, 'Telegraph', 'Telegraph Services'),
('4829', 10, 'Money transfer', 'Wire Transfer Money Orders / Money Transfer'),
('4899', 9, 'The television', 'Cable, Satellite, and Other Pay Television and Radio Services'),
('4900', 9, 'Utilities', 'Utilities - Electric, Gas, Heating Oil, Sanitary, Water'),
('5013', 3, 'Auto Parts', 'Motor Vehicle Supplies and New Parts'),
('5021', 3, 'Furniture', 'Office and Commercial Furniture'),
('5039', 3, 'Building materials', 'Construction Materials'),
('5044', 3, 'Office equipment', 'Office, Photographic, Photocopy and Microfilm Equipment'),
('5045', 3, 'Computers and software', 'Computers, Computer Peripheral Equipment, Software'),
('5046', 3, 'Equipment', 'Commercial Equipment'),
('5047', 3, 'Medical equipment', 'Dental / Laboratory / Medical / Ophthalmic Hospital Equipment and Supplies'),
('5051', 3, 'Metal processing', 'Metal Service Centers and Offices'),
('5065', 3, 'Electronics', 'Electrical Parts and Equipment'),
('5072', 3, 'Equipment', 'Hardware Equipment and Supplies'),
('5074', 3, 'Plumbing', 'Plumbing and Heating Equipment'),
('5085', 3, 'Industry', 'Industrial Supplies'),
('5094', 3, 'Jewelry', 'Precious Stones and Metals, Watches and Jewelry'),
('5099', 3, 'Goods', 'Durable Goods'),
('5111', 3, 'Chancery', 'Stationery, Office Supplies, Printing and Writing Paper'),
('5122', 3, 'Drugs', 'Drugs, Drug Proprietors and Druggists Sundries'),
('5131', 3, 'Haberdashery', 'Piece Goods, Notions, and Other Dry Goods'),
('5137', 3, 'Clothing', 'Men’s, Women’s and Children’s Uniforms and Commercial Clothing'),
('5139', 3, 'Footwear', 'Commercial Footware'),
('5169', 3, 'Chemicals', 'Chemicals and Allied Products'),
('5172', 3, 'Petroleum', 'Petroleum and Petroleum Products'),
('5192', 3, 'Books. Press', 'Books, Periodicals and Newspapers'),
('5193', 3, 'Flowers', 'Florists Supplies, Nursery Stock and Flowers'),
('5198', 3, 'Paints', 'Paints, Varnishes and Supplies'),
('5199', 3, 'Goods', 'Non-Durable Goods'),
('5200', 11, 'Household products', 'Home Supply Warehouse Stores'),
('5211', 11, 'Building materials', 'Building Materials, Lumber Stores'),
('5231', 11, 'Renovation', 'Glass, Paint, Wallpaper Stores'),
('5251', 11, 'Hardware Stores', 'Hardware Stores'),
('5261', 11, 'Garden accessories', 'Lawn and Garden Supply Stores'),
('5262', 11, 'Marketplaces', 'Marketplaces'),
('5271', 11, 'Mobile homes', 'Mobile Home Dealers'),
('5292', 7, 'Miscellaneous', 'Miscellaneous'),
('5295', 7, 'Miscellaneous', 'Miscellaneous'),
('5297', 11, 'Retail stores', 'Online retail stores'),
('5298', 11, 'Retail stores', 'Internet Shopping Grocery Store'),
('5299', 11, 'Gas sales', 'Warehouse Club Gas'),
('5300', 11, 'Wholesalers', 'Wholesale Clubs'),
('5309', 11, 'Duty Free', 'Duty Free Stores'),
('5310', 11, 'Discounters', 'Discount Stores'),
('5311', 11, 'Department stores', 'Department Stores'),
('5331', 11, 'Variety stores', 'Variety Stores'),
('5399', 11, 'Merchandise stores', 'Miscellaneous General Merchandise Stores'),
('5411', 11, 'Grocery', 'Grocery Stores, Supermarkets'),
('5415', 7, 'Miscellaneous', 'Miscellaneous'),
('5422', 11, 'Meat', 'Freezer and Locker Meat Provisioners'),
('5441', 11, 'Sweets', 'Candy, Nut and Confectionery Stores'),
('5451', 11, 'Farm goods', 'Dairy Products Stores'),
('5462', 11, 'Bakeries', 'Bakeries'),
('5499', 11, 'Food stores', 'Miscellaneous Food Stores - Convenience Stores, Markets, Specialty Stores, and Vending Machines'),
('5511', 12, 'Car dealerships', 'Automobile and Truck Dealers - Sales, Service, Repairs, Parts and Leasing'),
('5521', 12, 'Car dealerships', 'Automobile and Truck Dealers-(Used Only)-Sales'),
('5531', 12, 'Auto parts', 'Auto shops and household goods'),
('5532', 12, 'Tires', 'Automotive Tire Stores'),
('5533', 12, 'Auto shops', 'Automotive Parts and Accessories Stores'),
('5541', 12, 'Service Stations', 'Service Stations (With or Without Ancillary Services)'),
('5542', 12, 'Gas station', 'Fuel Dispenser, Automated'),
('5551', 12, 'Boats', 'Boat Dealers'),
('5552', 12, 'Charging stations', 'Electric car charging stations'),
('5561', 12, 'Car dealerships', 'Camper Dealers, Recreational and Utility Trailers'),
('5571', 12, 'Car dealerships', 'Motorcycle Shops and Dealers'),
('5592', 12, 'Car dealerships', 'Motor Home Dealers'),
('5598', 12, 'Car dealerships', 'Snowmobile Dealers'),
('5599', 12, 'Car dealerships', 'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers'),
('5611', 13, 'Mens clothing', 'Men’s and Boys’ Clothing and Accessories Stores'),
('5621', 13, 'Womens clothing', 'Women’s Ready to Wear Stores'),
('5631', 13, 'Clothing stores', 'Women’s Accessory and Specialty Stores'),
('5641', 13, 'Baby clothes', 'Children’s and Infants’ Wear Stores'),
('5651', 13, 'Clothes', 'Family Clothing Stores'),
('5655', 13, 'Sportswear', 'Sports Apparel, and Riding Apparel Stores'),
('5661', 13, 'Shoes', 'Shoe Stores'),
('5681', 13, 'Fur', 'Furriers and Fur Shops'),
('5691', 13, 'Clothes', 'Men’s and Women’s Clothing Stores'),
('5697', 13, 'Atelier', 'Alterations, Mending, Seamstresses, Tailors'),
('5698', 13, 'Wigs', 'Wig and Toupee Shops'),
('5699', 13, 'Accessories', 'Accessory and Apparel Stores - Miscellaneous'),
('5712', 14, 'Furniture', 'Equipment, Furniture and Home Furnishings Stores (except Appliances)'),
('5713', 14, 'Floor coverings', 'Floor Covering Stores'),
('5714', 14, 'Curtains', 'Drapery, Upholstery and Window Coverings Stores'),
('5715', 3, 'Alcohol', 'Wholesalers of alcohol'),
('5718', 14, 'Fireplaces', 'Fireplace, Fireplace Screens and Accessories Stores'),
('5719', 14, 'Furniture', 'Miscellaneous House Furnishing Specialty Shops'),
('5722', 14, 'Household appliance', 'Household Appliance Stores'),
('5732', 14, 'Household appliance', 'Electronics Sales'),
('5733', 14, 'Musical Instruments', 'Music Stores - Musical Instruments, Pianos and Sheet Music'),
('5734', 14, 'Computer Software', 'Computer Software Stores'),
('5735', 14, 'Record Shops', 'Record Shops'),
('5811', 10, 'Caterers', 'Caterers'),
('5812', 14, 'Cafe. Restaurants', 'Eating Places and Restaurants '),
('5813', 14, 'Bars', 'Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns-Drinking Places (Alcoholic Beverages)'),
('5814', 14, 'Fast Food', 'Fast Food Restaurants'),
('5815', 14, 'Digital Goods', 'Digital Goods: Books, Movies, Music'),
('5816', 14, 'Games', 'Digital Goods: Games'),
('5817', 14, 'Applications', 'Digital Goods: Applications (Excludes Games)'),
('5818', 14, 'Digital Goods', 'Digital Goods: Large Digital Goods Merchant / Digital Goods: Multi-Category'),
('5832', 14, 'Antiques', 'Antique Shops - Sales, Repairs, and Restoration Services'),
('5912', 14, 'Drug Stores', 'Drug Stores and Pharmacies'),
('5921', 14, 'Alcohol', 'Package Stores - Beer, Wine and Liquor'),
('5931', 14, 'Second Hand', 'Second Hand Stores, Used Merchandise Stores'),
('5932', 14, 'Antiques', 'Antique Shops-Sales, Repairs and Restoration Services'),
('5933', 14, 'Pawn Shops', 'Pawn Shops'),
('5935', 14, 'Car dump', 'Wrecking and Salvage Yards'),
('5937', 14, 'Reproduction Stores', 'Antique Reproduction Stores'),
('5940', 14, 'Bicycles', 'Bicycle Shops-Sales and Service'),
('5941', 14, 'Sports goods', 'Sporting Goods Stores'),
('5942', 14, 'Book Stores', 'Book Stores'),
('5943', 14, 'Stationery', 'Office, School Supply and Stationery Stores'),
('5944', 14, 'Clock', 'Clock, Jewelry, Watch and Silverware Stores'),
('5945', 14, 'Toys', 'Game, Toy and Hobby Shops'),
('5946', 14, 'Photo goods', 'Camera and Photographic Supply Stores'),
('5947', 14, 'Souvenirs', 'Card, Gift, Novelty and Souvenir Shops'),
('5948', 14, 'Leather Products', 'Leather Goods and Luggage Stores'),
('5949', 14, 'Sewing supplies', 'Fabric, Needlework, Piece Goods and Sewing Stores'),
('5950', 14, 'Crystal / glassware', 'Crystal and Glassware Stores'),
('5960', 15, 'Insurance', 'Direct Marketing Insurance Services'),
('5961', 15, 'Goods by mail', 'Mail Order Houses Including Catalog Order Stores'),
('5962', 15, 'Travels', 'Direct Marketing - Travel Related Arrangement Services'),
('5963', 14, 'Salesmen', 'Door-to-Door Sales'),
('5964', 15, 'Goods by mail', 'Direct Marketing-Catalog Merchants'),
('5965', 15, 'Goods by mail', 'Direct Marketing - Combination Catalog and Retail Merchant'),
('5966', 15, 'Goods by mail', 'Direct Marketing - Outbound Telemarketing Merchants'),
('5967', 15, 'Information Services', 'Direct Marketing - Inbound Telemarketing Merchants'),
('5968', 15, 'Subscriptions', 'Direct Marketing - Continuity / Subscription Merchants'),
('5969', 15, 'Goods by mail', 'Direct Marketing - Other Direct Marketers'),
('5970', 14, 'Art goods', 'Artist Supply Stores, Craft Shops'),
('5971', 14, 'Galleries', 'Art Dealers and Galleries'),
('5972', 14, 'Philatelicism', 'Stamp and Coin Stores - Philatelic and Numismatic Supplies'),
('5973', 14, 'Church shops', 'Religious Goods Stores'),
('5974', 14, 'Rubber stamp', 'Rubber Stamp Store'),
('5975', 14, 'Hearing Aids', 'Hearing Aids - Sales, Service, Supply Stores'),
('5976', 14, 'Prostheses', 'Orthopedic Goods - Artificial Limb Stores'),
('5977', 14, 'Cosmetics', 'Cosmetic Stores'),
('5978', 14, 'Printing machines', 'Typewriter Stores - Rentals, Sales, Service'),
('5983', 14, 'Fuel', 'Fuel Dealers - Coal, Fuel Oil, Liquefied Petroleum, Wood'),
('5992', 14, 'Florists', 'Florists'),
('5993', 14, 'Tobacco products', 'Cigar Stores and Stands'),
('5994', 14, 'Newspapers. Magazines', 'News Dealers and Newsstands'),
('5995', 14, 'Pet supplies', 'Pet Shops, Pet Food and Supplies'),
('5996', 14, 'Swimming Pools', 'Swimming Pools - Sales and Supplies'),
('5997', 14, 'Razors', 'Electric Razor Stores - Sales and Service'),
('5998', 14, 'Tents', 'Tent and Awning Shops'),
('5999', 14, 'Miscellaneous', 'Miscellaneous and Specialty Retail Stores'),
('6010', 10, 'Сashier''s office', 'Member Financial Institution - Manual Cash Disbursements'),
('6011', 10, 'Сashier''s office', 'Member Financial Institution - Automated Cash Disbursements'),
('6012', 10, 'Financial services', 'Member Financial Institution - Merchandise And Services'),
('6022', 10, 'Banks', 'Financial Institution (internal RCL)'),
('6023', 10, 'Banks', 'State Banks (RCL Internal)'),
('6025', 10, 'Banks', 'National Banks (RCL Internal)'),
('6026', 10, 'Banks', 'National Banks Non Federal (RCL Internal)'),
('6028', 10, 'Banks', 'Unincorporated Private Banks (RCL Internal)'),
('6050', 10, 'Quasi Cash', 'Quasi Cash - Member Financial Institution'),
('6051', 10, 'Quasi Cash', 'Quasi Cash - Merchant'),
('6211', 10, 'Securities', 'Securities - Brokers and Dealers'),
('6236', 4, 'Securities', 'Aserca Airlines / Aero Servicio Carabobo (Venezuela)'),
('6300', 10, 'Insurance', 'Insurance Sales, Underwriting and Premiums'),
('6381', 10, 'Insurance', 'Insurance - Premiums'),
('6399', 10, 'Insurance', 'Insurance'),
('6513', 10, 'Rental Property', 'Real Estate Agents and Managers - Rentals'),
('6529', 10, 'Сard replenishment', 'Remote Stored Value Load - Member Financial Institution'),
('6530', 10, 'Сard replenishment', 'Remove Stored Value Load - Merchant'),
('6531', 10, 'Money transfer', 'Payment for services - money transfers'),
('6532', 10, 'Money transfer', 'Payment Transaction - Financial Institution'),
('6533', 10, 'Money transfer', 'Payment operation - seller'),
('6534', 10, 'Money transfer', 'Money Transfer - Financial Institution'),
('6535', 10, 'Money transfer', 'Value Purchase - Member Financial Institution'),
('6536', 10, 'Money transfer', 'MoneySend Intracountry'),
('6537', 10, 'Money transfer', 'MoneySend Intercountry'),
('6538', 10, 'Money transfer', 'MoneySend Funding'),
('6539', 10, 'Money transfer', 'Funding Transaction (Excluding MoneySend)'),
('6540', 10, 'Money transfer', 'POI (Point of Interaction) Funding Transactions (Excluding MoneySend)'),
('6611', 10, 'Money transfer', 'Overpayments'),
('6760', 10, 'Bonds', 'Savings Bonds'),
('7011', 6, 'Hotels and resorts', 'Hotels and resorts'),
('7012', 10, 'Timeshares', 'Timeshares'),
('7032', 10, 'Recreation', 'Sporting and Recreational Camps'),
('7033', 10, 'Campgrounds', 'Campgrounds and Trailer Parks'),
('7210', 16, 'Cleaning', 'Cleaning, Garment and Laundry Services'),
('7211', 16, 'Laundry', 'Laundry Services - Family and Commercial'),
('7216', 16, 'Dry Cleaners', 'Dry Cleaners'),
('7217', 16, 'Cleaning', 'Carpet and Upholstery Cleaning'),
('7221', 16, 'Photographic Studios', 'Photographic Studios'),
('7230', 16, 'The beauty', 'Barber and Beauty Shops'),
('7251', 16, 'Clothing repair', 'Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors'),
('7261', 16, 'Funeral services', 'Funeral Service and Crematories'),
('7272', 16, 'Escort', 'Escort Services'),
('7273', 16, 'Dating. Escort', 'Dating Services'),
('7276', 16, 'Taxes', 'Tax Preparation Service'),
('7277', 16, 'Consultation', 'Debt, Marriage, Personal - Counseling Services'),
('7278', 16, 'Shopping', 'Buying / Shopping Clubs, Services'),
('7280', 16, 'Hospitals', 'Hospital Patient - Personal Funds Withdrawal'),
('7295', 16, 'Babysitters', 'Babysitting Services'),
('7296', 16, 'Clothing rental', 'Clothing Rental - Costumes, Uniforms and Formal Wear'),
('7297', 16, 'Massage', 'Massage Parlors'),
('7298', 16, 'Health and beauty', 'Health and Beauty Spas'),
('7299', 16, 'Miscellaneous', 'Other Services'),
('7311', 17, 'Advertising', 'Advertising Services'),
('7321', 17, 'Credit bureaus', 'Consumer Credit Reporting Agencies'),
('7322', 17, 'Collection agencies', 'Debt collection agencies'),
('7332', 17, 'Copy centers', 'Blueprinting and Photocopying Services'),
('7333', 17, 'Photography and art', 'Commercial Art, Graphics, Photography'),
('7338', 17, 'Copy centers', 'Quick Copy, Reproduction and Blueprinting Services'),
('7339', 17, 'Stenography', 'Stenographic and Secretarial Support Services'),
('7342', 17, 'Disinfecting', 'Exterminating and Disinfecting Services'),
('7349', 17, 'Cleaning and maintenance', 'Cleaning and Maintenance, Janitorial Services'),
('7361', 17, 'Employment', 'Employment Agencies and Temporary Help Services'),
('7372', 17, 'Programming', 'Computer Programming, Data Processing and Integrated System Design Services'),
('7375', 17, 'Information Services', 'Information Retrieval Services'),
('7379', 17, 'Computer Repair', 'Computer Maintenance, Repair And Services'),
('7389', 17, 'Business Services', 'Business Services'),
('7392', 17, 'Consulting, PR', 'Consulting, Management and Public Relations Services'),
('7393', 17, 'Detective agencies', 'Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs'),
('7394', 17, 'Equipment rental', 'Equipment Rental and Leasing Services, Furniture Rental, Tool Rental'),
('7395', 17, 'Photo printing', 'Photo Developing, Photofinishing Laboratories'),
('7399', 17, 'Business Services', 'Business Services'),
('7511', 17, 'Parking', 'Truck parking'),
('7512', 5, 'Car rent', 'Automobile Rental Agency'),
('7513', 5, 'Truck Rental', 'Truck Rental'),
('7519', 5, 'Car rent', 'Motor Home and Recreational Vehicle Rental'),
('7523', 17, 'Parking', 'Automobile Parking Lots and Garages'),
('7524', 17, 'Parking', 'Express Payment Service Merchants - Parking Lots and Garages'),
('7531', 18, 'Auto repair', 'Automotive Body Repair Shops'),
('7534', 18, 'Tire service', 'Tire Retreading and Repair Shops'),
('7535', 18, 'Car paints', 'Automotive Paint Shops'),
('7538', 18, 'Maintenance stations', 'Automotive Service Shops'),
('7542', 18, 'Car Washes', 'Car Washes'),
('7549', 18, 'Tow truck', 'Towing Services'),
('7622', 18, 'Repair of equipment', 'Electronic Repair Shops'),
('7623', 18, 'HVAC equipment repair', 'Air Conditioning and Refrigeration Repair Shops'),
('7629', 18, 'Repair of equipment', 'Appliance Repair Shops, Electrical and Small '),
('7631', 18, 'Repair of watches and jewelry', 'Clock, Jewelry and Watch Repair Shops'),
('7641', 18, 'Furniture repair', 'Furniture - Reupholstery, Repair and Refinishing'),
('7692', 18, 'Welding works', 'Welding Repair'),
('7699', 18, 'Repairs', 'Miscellaneous Repair Shops and Related Services'),
('7800', 19, 'Government Owned Lottery', 'Government Owned Lottery'),
('7801', 19, 'Online casino', 'Government-Licensed Casinos (Online or Internet Gambling)'),
('7802', 19, 'Horse / Dog racing', 'Government-Licensed Horse / Dog Racing'),
('7829', 19, 'Video rental', 'Motion Picture and Video Tape Production and Distribution'),
('7832', 19, 'Cinemas', 'Motion Picture Theaters'),
('7833', 19, 'Cinemas', 'Express Payment Service — Motion Picture Theater'),
('7841', 19, 'Video rental', 'DVD/Video Tape Rental Stores'),
('7911', 19, 'Dance studios. Dance schools', 'Dance Halls, Schools and Studios'),
('7922', 19, 'Tickets', 'Theatrical Producers (Except Motion Pictures), Ticket Agencies'),
('7929', 19, 'Music bands. Orchestras', 'Bands, Orchestras and Miscellaneous Entertainers'),
('7932', 19, 'Billiard', 'Pool and Billiard Establishments'),
('7933', 19, 'Bowling clubs', 'Bowling Alleys'),
('7941', 19, 'Sports clubs', 'Athletic Fields, Commercial Sports, Professional Sports Clubs, Sports Promoters'),
('7991', 19, 'Tourism', 'Tourist Attractions and Exhibits'),
('7992', 19, 'Golf', 'Golf Courses, Public'),
('7993', 19, 'Videogames', 'Video Amusement Game Supplies'),
('7994', 19, 'Videogames', 'Video Game Arcades and Establishments'),
('7995', 19, 'Gambling', 'Gambling Transactions, Betting'),
('7996', 19, 'Entertainment', 'Amusement Parks, Carnivals, Circuses, Fortune Tellers'),
('7997', 19, 'Entertainment and sport', 'Clubs-Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses'),
('7998', 19, 'Aquariums. Dolphinariums', 'Aquariums, Dolphinariums, Zoos and Seaquariums'),
('7999', 19, 'Entertainment and sport', 'Recreation Services'),
('8011', 20, 'Medicine', 'Doctors'),
('8021', 20, 'Dentistry', 'Dentists and Orthodontists'),
('8031', 20, 'Medicine', 'Osteopathic Physicians'),
('8041', 20, 'Chiropractors', 'Chiropractors'),
('8042', 20, 'Optics', 'Optometrists and Ophthalmologists'),
('8043', 20, 'Optics', 'Opticians, Optical Goods and Eyeglasses'),
('8044', 20, 'Optics', 'Optical Goods and Eyeglasses'),
('8049', 20, 'Podiatrists', 'Chiropodists, Podiatrists'),
('8050', 20, 'Caregiver / Nurse', 'Nursing and Personal Care Facilities'),
('8062', 20, 'Hospitals', 'Hospitals'),
('8071', 20, 'Medicine and dentistry', 'Dental and Medical Laboratories'),
('8099', 20, 'Medical services', 'Health Practitioners, Medical Services'),
('8110', 20, 'Lawyers', 'Attorneys, Legal Services'),
('8111', 20, 'Lawyers', 'Attorneys, Legal Services'),
('8211', 20, 'School', 'Schools, Elementary and Secondary'),
('8220', 20, 'Education. University', 'Colleges, Universities, Professional Schools and Junior Colleges'),
('8241', 20, 'Schools, Correspondence', 'Schools, Correspondence'),
('8244', 20, 'Education. Business', 'Schools, Business and Secretarial '),
('8249', 20, 'Education', 'Schools, Trade and Vocational'),
('8299', 20, 'Education', 'Schools And Educational Services'),
('8351', 20, 'Kindergarten', 'Child Care Services'),
('8398', 21, 'Charity', 'Organizations, Charitable and Social Service'),
('8641', 21, 'Public organizations', 'Associations - Civic, Social and Fraternal'),
('8651', 21, 'Organizations, Political', 'Organizations, Political'),
('8661', 21, 'Organizations, Religious', 'Organizations, Religious'),
('8664', 7, 'Miscellaneous', 'Miscellaneous'),
('8675', 21, 'Autoclub', 'Automobile Associations'),
('8699', 21, 'Organizations, Membership', 'Organizations, Membership'),
('8734', 20, 'Testing laboratories', 'Testing Laboratories (Non-Medical)'),
('8743', 20, 'Testing laboratories', 'Testing Laboratories (Non-Medical)'),
('8911', 20, 'Architects', 'Architectural, Engineering and Surveying Services'),
('8931', 20, 'Accounting. Audit', 'Accounting, Auditing and Bookkeeping Services'),
('8999', 20, 'Professional services', 'Professional services'),
('9034', 22, 'I-Purchasing Pilot', 'I-Purchasing Pilot'),
('9211', 22, 'Court', 'Court Costs Including Alimony and Child Support'),
('9222', 22, 'Fines', 'Fines'),
('9223', 22, 'Payouts. Bonds', 'Bail and Bond Payments'),
('9311', 22, 'Taxes', 'Tax Payments'),
('9399', 22, 'Government Services', 'Government Services'),
('9401', 22, 'I-Purchasing Pilot', 'I-Purchasing Pilot'),
('9402', 22, 'Mail', 'Postal Services - Government Only'),
('9405', 22, 'Government procurement', 'Intra-Government Purchases - Government Only'),
('9406', 19, 'Government Owned Lottery', 'Government Owned Lottery'),
('9411', 22, 'Government Services', 'Government loan payments'),
('9700', 7, 'Cashback', 'Automated Referral Service'),
('9701', 7, 'VISA', 'Visa Credential Server'),
('9702', 7, 'Emergency services', 'GCAS Emergency Services'),
('9751', 3, 'Document flow', 'UK Supermarkets, Electronic Hot File'),
('9752', 3, 'Document flow', 'UK Petrol Stations, Electronic Hot File'),
('9754', 22, 'Horse / Dog racing', 'Government-Licensed Horse / Dog Racing'),
('9950', 7, 'In-company purchases', 'Intra-Company Purchases'),
('9999', 7, 'Miscellaneous', 'Miscellaneous');
