UPDATE category SET title = 'Currency Purchase'       WHERE id = 1  AND is_default = 1;
UPDATE category SET title = 'Currency Sale'            WHERE id = 2  AND is_default = 1;
UPDATE category SET title = 'Crypto Purchase'          WHERE id = 3  AND is_default = 1;
UPDATE category SET title = 'Crypto Sale'              WHERE id = 4  AND is_default = 1;
UPDATE category SET title = 'Stock Purchase'           WHERE id = 5  AND is_default = 1;
UPDATE category SET title = 'Stock Sale'               WHERE id = 6  AND is_default = 1;
UPDATE category SET title = 'Currency Transfer'        WHERE id = 7  AND is_default = 1;
UPDATE category SET title = 'Crypto Transfer'          WHERE id = 8  AND is_default = 1;
UPDATE category SET title = 'Stock Transfer'           WHERE id = 9  AND is_default = 1;
UPDATE category SET title = 'Housing & Utilities'      WHERE id = 10 AND is_default = 1;
UPDATE category SET title = 'Groceries'                WHERE id = 11 AND is_default = 1;
UPDATE category SET title = 'Restaurants & Cafes'      WHERE id = 12 AND is_default = 1;
UPDATE category SET title = 'Transportation'           WHERE id = 13 AND is_default = 1;
UPDATE category SET title = 'Car & Fuel'               WHERE id = 14 AND is_default = 1;
UPDATE category SET title = 'Health & Medical'         WHERE id = 15 AND is_default = 1;
UPDATE category SET title = 'Insurance'                WHERE id = 16 AND is_default = 1;
UPDATE category SET title = 'Debt Payments'            WHERE id = 17 AND is_default = 1;
UPDATE category SET title = 'Savings'                  WHERE id = 18 AND is_default = 1;
UPDATE category SET title = 'Investments'              WHERE id = 19 AND is_default = 1;
UPDATE category SET title = 'Salary & Wages'           WHERE id = 20 AND is_default = 1;
UPDATE category SET title = 'Freelance & Side Hustle'  WHERE id = 21 AND is_default = 1;
UPDATE category SET title = 'Shopping'                 WHERE id = 22 AND is_default = 1;
UPDATE category SET title = 'Subscriptions'            WHERE id = 23 AND is_default = 1;
UPDATE category SET title = 'Entertainment'            WHERE id = 24 AND is_default = 1;
UPDATE category SET title = 'Education'                WHERE id = 25 AND is_default = 1;
UPDATE category SET title = 'Gifts & Donations'        WHERE id = 26 AND is_default = 1;
UPDATE category SET title = 'Family & Kids'            WHERE id = 27 AND is_default = 1;
UPDATE category SET title = 'Pets'                     WHERE id = 28 AND is_default = 1;
UPDATE category SET title = 'Travel'                   WHERE id = 29 AND is_default = 1;
UPDATE category SET title = 'Business Expenses'        WHERE id = 30 AND is_default = 1;
UPDATE category SET title = 'Taxes'                    WHERE id = 31 AND is_default = 1;
UPDATE category SET title = 'Bank Fees & Charges'      WHERE id = 32 AND is_default = 1;
UPDATE category SET title = 'Home Maintenance'         WHERE id = 33 AND is_default = 1;
UPDATE category SET title = 'Personal Care'            WHERE id = 34 AND is_default = 1;
UPDATE category SET title = 'Electronics & Gadgets'    WHERE id = 35 AND is_default = 1;
UPDATE category SET title = 'Sport & Fitness'          WHERE id = 36 AND is_default = 1;
UPDATE category SET title = 'Clothing & Accessories'   WHERE id = 37 AND is_default = 1;
UPDATE category SET title = 'Other'                    WHERE id = 38 AND is_default = 1;
UPDATE category SET title = 'Emergency Fund'           WHERE id = 39 AND is_default = 1;
