ALTER TABLE `instruments` ADD `price_provider` text;--> statement-breakpoint
ALTER TABLE `instruments` ADD `provider_instrument_id` text;--> statement-breakpoint
ALTER TABLE `instruments` ADD `market_cap_rank` integer;--> statement-breakpoint
INSERT INTO `instruments` (`type`, `code`, `name`, `symbol`, `price_provider`, `provider_instrument_id`, `market_cap_rank`) VALUES
('CRYPTO', 'BTC', 'Bitcoin', 'BTC', 'COINGECKO', 'bitcoin', 1),
('CRYPTO', 'ETH', 'Ethereum', 'ETH', 'COINGECKO', 'ethereum', 2),
('CRYPTO', 'USDT', 'Tether', 'USDT', 'COINGECKO', 'tether', 3),
('CRYPTO', 'BNB', 'BNB', 'BNB', 'COINGECKO', 'binancecoin', 4),
('CRYPTO', 'USDC', 'USDC', 'USDC', 'COINGECKO', 'usd-coin', 5),
('CRYPTO', 'XRP', 'XRP', 'XRP', 'COINGECKO', 'ripple', 6),
('CRYPTO', 'SOL', 'Solana', 'SOL', 'COINGECKO', 'solana', 7),
('CRYPTO', 'TRX', 'TRON', 'TRX', 'COINGECKO', 'tron', 8),
('CRYPTO', 'FIGR_HELOC', 'Figure Heloc', 'FIGR_HELOC', 'COINGECKO', 'figure-heloc', 9),
('CRYPTO', 'HYPE', 'Hyperliquid', 'HYPE', 'COINGECKO', 'hyperliquid', 10),
('CRYPTO', 'DOGE', 'Dogecoin', 'DOGE', 'COINGECKO', 'dogecoin', 11),
('CRYPTO', 'USDS', 'USDS', 'USDS', 'COINGECKO', 'usds', 12),
('CRYPTO', 'LEO', 'LEO Token', 'LEO', 'COINGECKO', 'leo-token', 13),
('CRYPTO', 'ZEC', 'Zcash', 'ZEC', 'COINGECKO', 'zcash', 14),
('CRYPTO', 'RAIN', 'Rain', 'RAIN', 'COINGECKO', 'rain', 15),
('CRYPTO', 'ADA', 'Cardano', 'ADA', 'COINGECKO', 'cardano', 16),
('CRYPTO', 'XLM', 'Stellar', 'XLM', 'COINGECKO', 'stellar', 17),
('CRYPTO', 'XMR', 'Monero', 'XMR', 'COINGECKO', 'monero', 18),
('CRYPTO', 'LAB', 'LAB', 'LAB', 'COINGECKO', 'lab', 19),
('CRYPTO', 'CC', 'Canton', 'CC', 'COINGECKO', 'canton-network', 20),
('CRYPTO', 'LINK', 'Chainlink', 'LINK', 'COINGECKO', 'chainlink', 21),
('CRYPTO', 'WBT', 'WhiteBIT Coin', 'WBT', 'COINGECKO', 'whitebit', 22),
('CRYPTO', 'BCH', 'Bitcoin Cash', 'BCH', 'COINGECKO', 'bitcoin-cash', 23),
('CRYPTO', 'USD1', 'USD1', 'USD1', 'COINGECKO', 'usd1-wlfi', 24),
('CRYPTO', 'TON', 'Toncoin', 'TON', 'COINGECKO', 'the-open-network', 25),
('CRYPTO', 'USDE', 'Ethena USDe', 'USDE', 'COINGECKO', 'ethena-usde', 26),
('CRYPTO', 'M', 'MemeCore', 'M', 'COINGECKO', 'memecore', 28),
('CRYPTO', 'DAI', 'Dai', 'DAI', 'COINGECKO', 'dai', 27),
('CRYPTO', 'HBAR', 'Hedera', 'HBAR', 'COINGECKO', 'hedera-hashgraph', 29),
('CRYPTO', 'LTC', 'Litecoin', 'LTC', 'COINGECKO', 'litecoin', 30),
('CRYPTO', 'AVAX', 'Avalanche', 'AVAX', 'COINGECKO', 'avalanche-2', 31),
('CRYPTO', 'SUI', 'Sui', 'SUI', 'COINGECKO', 'sui', 32),
('CRYPTO', 'NEAR', 'NEAR Protocol', 'NEAR', 'COINGECKO', 'near', 33),
('CRYPTO', 'PYUSD', 'PayPal USD', 'PYUSD', 'COINGECKO', 'paypal-usd', 34),
('CRYPTO', 'USYC', 'Circle USYC', 'USYC', 'COINGECKO', 'hashnote-usyc', 35),
('CRYPTO', 'SHIB', 'Shiba Inu', 'SHIB', 'COINGECKO', 'shiba-inu', 36),
('CRYPTO', 'XAUT', 'Tether Gold', 'XAUT', 'COINGECKO', 'tether-gold', 37),
('CRYPTO', 'CRO', 'Cronos', 'CRO', 'COINGECKO', 'crypto-com-chain', 38),
('CRYPTO', 'USDG', 'Global Dollar', 'USDG', 'COINGECKO', 'global-dollar', 39),
('CRYPTO', 'BUIDL', 'BlackRock USD Institutional Digital Liquidity Fund', 'BUIDL', 'COINGECKO', 'blackrock-usd-institutional-digital-liquidity-fund', 40),
('CRYPTO', 'USDY', 'Ondo US Dollar Yield', 'USDY', 'COINGECKO', 'ondo-us-dollar-yield', 41),
('CRYPTO', 'PAXG', 'PAX Gold', 'PAXG', 'COINGECKO', 'pax-gold', 42),
('CRYPTO', 'TAO', 'Bittensor', 'TAO', 'COINGECKO', 'bittensor', 43),
('CRYPTO', 'WLFI', 'World Liberty Financial', 'WLFI', 'COINGECKO', 'world-liberty-financial', 44),
('CRYPTO', 'MNT', 'Mantle', 'MNT', 'COINGECKO', 'mantle', 45),
('CRYPTO', 'DOT', 'Polkadot', 'DOT', 'COINGECKO', 'polkadot', 46),
('CRYPTO', 'ONDO', 'Ondo', 'ONDO', 'COINGECKO', 'ondo-finance', 47),
('CRYPTO', 'RLUSD', 'Ripple USD', 'RLUSD', 'COINGECKO', 'ripple-usd', 48),
('CRYPTO', 'ASTER', 'Aster', 'ASTER', 'COINGECKO', 'aster-2', 49),
('CRYPTO', 'UNI', 'Uniswap', 'UNI', 'COINGECKO', 'uniswap', 51),
('CRYPTO', 'WLD', 'Worldcoin', 'WLD', 'COINGECKO', 'worldcoin-wld', 50),
('CRYPTO', 'OKB', 'OKB', 'OKB', 'COINGECKO', 'okb', 52),
('CRYPTO', 'HTX', 'HTX DAO', 'HTX', 'COINGECKO', 'htx-dao', 53),
('CRYPTO', 'USDF', 'Falcon USD', 'USDF', 'COINGECKO', 'falcon-finance', 54),
('CRYPTO', 'SKY', 'Sky', 'SKY', 'COINGECKO', 'sky', 55),
('CRYPTO', 'ICP', 'Internet Computer', 'ICP', 'COINGECKO', 'internet-computer', 56),
('CRYPTO', 'USDD', 'USDD', 'USDD', 'COINGECKO', 'usdd', 57),
('CRYPTO', 'PI', 'Pi Network', 'PI', 'COINGECKO', 'pi-network', 58),
('CRYPTO', 'BFUSD', 'BFUSD', 'BFUSD', 'COINGECKO', 'bfusd', 59),
('CRYPTO', 'BGB', 'Bitget Token', 'BGB', 'COINGECKO', 'bitget-token', 60),
('CRYPTO', 'PEPE', 'Pepe', 'PEPE', 'COINGECKO', 'pepe', 61),
('CRYPTO', 'MORPHO', 'Morpho', 'MORPHO', 'COINGECKO', 'morpho', 62),
('CRYPTO', 'ETC', 'Ethereum Classic', 'ETC', 'COINGECKO', 'ethereum-classic', 63),
('CRYPTO', 'H', 'Humanity', 'H', 'COINGECKO', 'humanity', 64),
('CRYPTO', 'AAVE', 'Aave', 'AAVE', 'COINGECKO', 'aave', 65),
('CRYPTO', 'USDTB', 'USDtb', 'USDTB', 'COINGECKO', 'usdtb', 66),
('CRYPTO', 'EUTBL', 'Spiko EU T-Bills Money Market Fund', 'EUTBL', 'COINGECKO', 'eutbl', 67),
('CRYPTO', 'QNT', 'Quant', 'QNT', 'COINGECKO', 'quant-network', 68),
('CRYPTO', 'BCAP', 'Blockchain Capital', 'BCAP', 'COINGECKO', 'blockchain-capital', 69),
('CRYPTO', 'RENDER', 'Render', 'RENDER', 'COINGECKO', 'render-token', 70),
('CRYPTO', 'U', 'United Stables', 'U', 'COINGECKO', 'united-stables', 71),
('CRYPTO', 'POL', 'POL (ex-MATIC)', 'POL', 'COINGECKO', 'polygon-ecosystem-token', 72),
('CRYPTO', 'USTB', 'Superstate Short Duration U.S. Government Securities Fund (USTB)', 'USTB', 'COINGECKO', 'superstate-short-duration-us-government-securities-fund-ustb', 73),
('CRYPTO', 'KCS', 'KuCoin', 'KCS', 'COINGECKO', 'kucoin-shares', 74),
('CRYPTO', 'ALGO', 'Algorand', 'ALGO', 'COINGECKO', 'algorand', 76),
('CRYPTO', 'ATOM', 'Cosmos Hub', 'ATOM', 'COINGECKO', 'cosmos', 75),
('CRYPTO', 'DEXE', 'DeXe', 'DEXE', 'COINGECKO', 'dexe', 77),
('CRYPTO', 'JTRSY', 'Janus Henderson Anemoy Treasury Fund', 'JTRSY', 'COINGECKO', 'janus-henderson-anemoy-treasury-fund', 78),
('CRYPTO', 'STABLE', '​​Stable', 'STABLE', 'COINGECKO', 'stable-2', 80),
('CRYPTO', 'ENA', 'Ethena', 'ENA', 'COINGECKO', 'ethena', 79),
('CRYPTO', 'VVV', 'Venice Token', 'VVV', 'COINGECKO', 'venice-token', 81),
('CRYPTO', 'KAS', 'Kaspa', 'KAS', 'COINGECKO', 'kaspa', 82),
('CRYPTO', 'NEXO', 'NEXO', 'NEXO', 'COINGECKO', 'nexo', 83),
('CRYPTO', 'GT', 'Gate', 'GT', 'COINGECKO', 'gatechain-token', 84),
('CRYPTO', 'FIL', 'Filecoin', 'FIL', 'COINGECKO', 'filecoin', 85),
('CRYPTO', '币安人生', '币安人生 (BinanceLife)', '币安人生', 'COINGECKO', 'bianrensheng', 86),
('CRYPTO', 'JST', 'JUST', 'JST', 'COINGECKO', 'just', 87),
('CRYPTO', 'BDX', 'Beldex', 'BDX', 'COINGECKO', 'beldex', 88),
('CRYPTO', 'FLR', 'Flare', 'FLR', 'COINGECKO', 'flare-networks', 90),
('CRYPTO', 'APT', 'Aptos', 'APT', 'COINGECKO', 'aptos', 89),
('CRYPTO', 'NIGHT', 'Midnight', 'NIGHT', 'COINGECKO', 'midnight-3', 91),
('CRYPTO', 'XDC', 'XDC Network', 'XDC', 'COINGECKO', 'xdce-crowd-sale', 92),
('CRYPTO', 'INJ', 'Injective', 'INJ', 'COINGECKO', 'injective-protocol', 93),
('CRYPTO', 'GHO', 'GHO', 'GHO', 'COINGECKO', 'gho', 94),
('CRYPTO', 'JUP', 'Jupiter', 'JUP', 'COINGECKO', 'jupiter-exchange-solana', 95),
('CRYPTO', 'PUMP', 'Pump.fun', 'PUMP', 'COINGECKO', 'pump-fun', 96),
('CRYPTO', 'USD0', 'Usual USD', 'USD0', 'COINGECKO', 'usual-usd', 97),
('CRYPTO', 'ARB', 'Arbitrum', 'ARB', 'COINGECKO', 'arbitrum', 98),
('CRYPTO', 'YLDS', 'YLDS', 'YLDS', 'COINGECKO', 'ylds', 99),
('CRYPTO', 'SIREN', 'Siren', 'SIREN', 'COINGECKO', 'siren-2', 100),
('CRYPTO', 'A7A5', 'A7A5', 'A7A5', 'COINGECKO', 'a7a5', 101),
('CRYPTO', 'HASH', 'Provenance Blockchain', 'HASH', 'COINGECKO', 'hash-2', 102),
('CRYPTO', 'FET', 'Artificial Superintelligence Alliance', 'FET', 'COINGECKO', 'fetch-ai', 103),
('CRYPTO', 'TUSD', 'TrueUSD', 'TUSD', 'COINGECKO', 'true-usd', 105),
('CRYPTO', 'USX', 'USX', 'USX', 'COINGECKO', 'usx', 104),
('CRYPTO', 'OUSG', 'OUSG', 'OUSG', 'COINGECKO', 'ousg', 106),
('CRYPTO', 'VET', 'VeChain', 'VET', 'COINGECKO', 'vechain', 107),
('CRYPTO', 'EURSAFO', 'Spiko Amundi Overnight Swap Fund (EUR)', 'EURSAFO', 'COINGECKO', 'spiko-amundi-overnight-swap-fund-eur', 108),
('CRYPTO', 'APXUSD', 'apxUSD', 'APXUSD', 'COINGECKO', 'apxusd', 109),
('CRYPTO', 'DASH', 'Dash', 'DASH', 'COINGECKO', 'dash', 110),
('CRYPTO', 'JAAA', 'Janus Henderson Anemoy AAA CLO Fund', 'JAAA', 'COINGECKO', 'janus-henderson-anemoy-aaa-clo-fund', 111),
('CRYPTO', 'EURC', 'EURC', 'EURC', 'COINGECKO', 'euro-coin', 112),
('CRYPTO', 'TRUMP', 'Official Trump', 'TRUMP', 'COINGECKO', 'official-trump', 113),
('CRYPTO', 'PENGU', 'Pudgy Penguins', 'PENGU', 'COINGECKO', 'pudgy-penguins', 114),
('CRYPTO', 'VIRTUAL', 'Virtuals Protocol', 'VIRTUAL', 'COINGECKO', 'virtual-protocol', 115),
('CRYPTO', 'KITE', 'Kite', 'KITE', 'COINGECKO', 'kite-2', 116),
('CRYPTO', 'BONK', 'Bonk', 'BONK', 'COINGECKO', 'bonk', 117),
('CRYPTO', 'BEAT', 'Audiera', 'BEAT', 'COINGECKO', 'audiera', 118),
('CRYPTO', 'CAKE', 'PancakeSwap', 'CAKE', 'COINGECKO', 'pancakeswap-token', 119),
('CRYPTO', 'PRIME', 'PRIME', 'PRIME', 'COINGECKO', 'hastra-prime', 120),
('CRYPTO', 'ADI', 'ADI', 'ADI', 'COINGECKO', 'adi-token', 121),
('CRYPTO', '9BIT', 'The9bit', '9BIT', 'COINGECKO', 'the9bit', 122),
('CRYPTO', 'LIT', 'Lighter', 'LIT', 'COINGECKO', 'lighter', 123),
('CRYPTO', 'LUNC', 'Terra Luna Classic', 'LUNC', 'COINGECKO', 'terra-luna', 124),
('CRYPTO', 'SEI', 'Sei', 'SEI', 'COINGECKO', 'sei-network', 125),
('CRYPTO', 'STX', 'Stacks', 'STX', 'COINGECKO', 'blockstack', 126),
('CRYPTO', 'FDUSD', 'First Digital USD', 'FDUSD', 'COINGECKO', 'first-digital-usd', 127),
('CRYPTO', 'KAU', 'Kinesis Gold', 'KAU', 'COINGECKO', 'kinesis-gold', 128),
('CRYPTO', 'AERO', 'Aerodrome Finance', 'AERO', 'COINGECKO', 'aerodrome-finance', 129),
('CRYPTO', 'SUN', 'Sun Token', 'SUN', 'COINGECKO', 'sun-token', 130),
('CRYPTO', 'TIA', 'Celestia', 'TIA', 'COINGECKO', 'celestia', 131),
('CRYPTO', 'XTZ', 'Tezos', 'XTZ', 'COINGECKO', 'tezos', 132),
('CRYPTO', 'CRV', 'Curve DAO', 'CRV', 'COINGECKO', 'curve-dao-token', 133),
('CRYPTO', 'USDAI', 'USDai', 'USDAI', 'COINGECKO', 'usdai', 134),
('CRYPTO', 'JTO', 'Jito', 'JTO', 'COINGECKO', 'jito-governance-token', 136),
('CRYPTO', 'ZRO', 'LayerZero', 'ZRO', 'COINGECKO', 'layerzero', 135),
('CRYPTO', 'SPX', 'SPX6900', 'SPX', 'COINGECKO', 'spx6900', 137),
('CRYPTO', 'CHZ', 'Chiliz', 'CHZ', 'COINGECKO', 'chiliz', 138),
('CRYPTO', 'ETHFI', 'Ether.fi', 'ETHFI', 'COINGECKO', 'ether-fi', 139),
('CRYPTO', 'OHM', 'Olympus', 'OHM', 'COINGECKO', 'olympus', 140),
('CRYPTO', 'KAG', 'Kinesis Silver', 'KAG', 'COINGECKO', 'kinesis-silver', 141),
('CRYPTO', 'FRAX', 'Legacy Frax Dollar', 'FRAX', 'COINGECKO', 'frax', 142),
('CRYPTO', 'NFT', 'AINFT', 'NFT', 'COINGECKO', 'apenft', 143),
('CRYPTO', 'PYTH', 'Pyth Network', 'PYTH', 'COINGECKO', 'pyth-network', 144),
('CRYPTO', 'BTT', 'BitTorrent', 'BTT', 'COINGECKO', 'bittorrent', 145),
('CRYPTO', 'BSV', 'Bitcoin SV', 'BSV', 'COINGECKO', 'bitcoin-cash-sv', 146),
('CRYPTO', 'ZBCN', 'Zebec Network', 'ZBCN', 'COINGECKO', 'zebec-network', 147),
('CRYPTO', '2Z', 'DoubleZero', '2Z', 'COINGECKO', 'doublezero', 148),
('CRYPTO', 'GNO', 'Gnosis', 'GNO', 'COINGECKO', 'gnosis', 149),
('CRYPTO', 'UB', 'Unibase', 'UB', 'COINGECKO', 'unibase', 150),
('CRYPTO', 'RUSD', 'Royal Dollar', 'RUSD', 'COINGECKO', 'royal-dollar', 151),
('CRYPTO', 'CFX', 'Conflux', 'CFX', 'COINGECKO', 'conflux-token', 152),
('CRYPTO', 'TEL', 'Telcoin', 'TEL', 'COINGECKO', 'telcoin', 153),
('CRYPTO', 'DCR', 'Decred', 'DCR', 'COINGECKO', 'decred', 154),
('CRYPTO', 'GRASS', 'Grass', 'GRASS', 'COINGECKO', 'grass', 155),
('CRYPTO', 'KAIA', 'Kaia', 'KAIA', 'COINGECKO', 'kaia', 156),
('CRYPTO', 'JASMY', 'JasmyCoin', 'JASMY', 'COINGECKO', 'jasmycoin', 157),
('CRYPTO', 'FLOKI', 'FLOKI', 'FLOKI', 'COINGECKO', 'floki', 158),
('CRYPTO', 'GRT', 'The Graph', 'GRT', 'COINGECKO', 'the-graph', 159),
('CRYPTO', 'LDO', 'Lido DAO', 'LDO', 'COINGECKO', 'lido-dao', 160),
('CRYPTO', 'OP', 'Optimism', 'OP', 'COINGECKO', 'optimism', 161),
('CRYPTO', 'APEPE', 'Ape and Pepe', 'APEPE', 'COINGECKO', 'ape-and-pepe', 162),
('CRYPTO', 'B', 'BUILDon', 'B', 'COINGECKO', 'build-on', 163),
('CRYPTO', 'PIEVERSE', 'Pieverse', 'PIEVERSE', 'COINGECKO', 'pieverse', 164),
('CRYPTO', 'COCO', 'coco', 'COCO', 'COINGECKO', 'coco-2', 165),
('CRYPTO', 'MON', 'Monad', 'MON', 'COINGECKO', 'monad', 166),
('CRYPTO', 'PENDLE', 'Pendle', 'PENDLE', 'COINGECKO', 'pendle', 167),
('CRYPTO', 'FF', 'Falcon Finance', 'FF', 'COINGECKO', 'falcon-finance-ff', 168),
('CRYPTO', 'USDA', 'USDa', 'USDA', 'COINGECKO', 'usda-2', 169),
('CRYPTO', 'XPL', 'Plasma', 'XPL', 'COINGECKO', 'plasma', 170),
('CRYPTO', 'STRK', 'Starknet', 'STRK', 'COINGECKO', 'starknet', 171),
('CRYPTO', 'APYUSD', 'apyUSD', 'APYUSD', 'COINGECKO', 'apyusd', 173),
('CRYPTO', 'IOTA', 'IOTA', 'IOTA', 'COINGECKO', 'iota', 172),
('CRYPTO', 'USDM', 'MegaUSD', 'USDM', 'COINGECKO', 'megausd', 174),
('CRYPTO', 'GWEI', 'ETHGas', 'GWEI', 'COINGECKO', 'ethgas-2', 175),
('CRYPTO', 'ENS', 'Ethereum Name Service', 'ENS', 'COINGECKO', 'ethereum-name-service', 176),
('CRYPTO', 'PC0000031', 'Tradable NA Rent Financing Platform SSTN', 'PC0000031', 'COINGECKO', 'tradable-na-rent-financing-platform-sstn', 177),
('CRYPTO', 'ULTIMA', 'Ultima', 'ULTIMA', 'COINGECKO', 'ultima', 178),
('CRYPTO', 'CRVUSD', 'crvUSD', 'CRVUSD', 'COINGECKO', 'crvusd', 179),
('CRYPTO', 'EDGE', 'edgeX', 'EDGE', 'COINGECKO', 'edgex', 180),
('CRYPTO', 'BILL', 'Billions Network', 'BILL', 'COINGECKO', 'billions-network', 181),
('CRYPTO', 'AKT', 'Akash Network', 'AKT', 'COINGECKO', 'akash-network', 182),
('CRYPTO', 'KOGE', 'KOGE', 'KOGE', 'COINGECKO', 'bnb48-club-token', 183),
('CRYPTO', 'ONYC', 'OnRe Tokenized Reinsurance', 'ONYC', 'COINGECKO', 'onyc', 184),
('CRYPTO', 'TWT', 'Trust Wallet', 'TWT', 'COINGECKO', 'trust-wallet-token', 185),
('CRYPTO', 'TRAC', 'OriginTrail', 'TRAC', 'COINGECKO', 'origintrail', 186),
('CRYPTO', 'REUSD', 'Re Protocol reUSD', 'REUSD', 'COINGECKO', 're-protocol-reusd', 187),
('CRYPTO', 'SKYAI', 'SkyAI', 'SKYAI', 'COINGECKO', 'skyai', 188),
('CRYPTO', 'AXS', 'Axie Infinity', 'AXS', 'COINGECKO', 'axie-infinity', 189),
('CRYPTO', 'REAL', 'RealLink', 'REAL', 'COINGECKO', 'reallink', 190),
('CRYPTO', 'WFI', 'WeFi', 'WFI', 'COINGECKO', 'wefi', 191),
('CRYPTO', 'NEX', 'Nexus', 'NEX', 'COINGECKO', 'nexus-4', 192),
('CRYPTO', 'NEO', 'NEO', 'NEO', 'COINGECKO', 'neo', 194),
('CRYPTO', 'USAT', 'USAT', 'USAT', 'COINGECKO', 'usa', 193),
('CRYPTO', 'COMP', 'Compound', 'COMP', 'COINGECKO', 'compound-governance-token', 195),
('CRYPTO', 'WIF', 'dogwifhat', 'WIF', 'COINGECKO', 'dogwifcoin', 196),
('CRYPTO', 'RAY', 'Raydium', 'RAY', 'COINGECKO', 'raydium', 197),
('CRYPTO', 'THETA', 'Theta Network', 'THETA', 'COINGECKO', 'theta-token', 198),
('CRYPTO', 'PC0000033', 'Tradable APAC Diversified Finance Provider SSTN', 'PC0000033', 'COINGECKO', 'tradable-apac-diversified-finance-provider-sstn', 199),
('CRYPTO', 'SYRUP', 'Maple Finance', 'SYRUP', 'COINGECKO', 'syrup', 200);
