export enum ConsolidationFamilyKeyEnum {
    ATM_CASH_WITHDRAWAL = 'ATM_CASH_WITHDRAWAL',
    EXISTING_TRANSFER_BRIDGE = 'EXISTING_TRANSFER_BRIDGE',
    EXISTING_TRANSFER_CHAIN_RECLAIM = 'EXISTING_TRANSFER_CHAIN_RECLAIM',
    EXISTING_TRANSFER_INCOME_DUPLICATE = 'EXISTING_TRANSFER_INCOME_DUPLICATE',
    IBAN_BRIDGE_CANONICAL_DUPLICATE = 'IBAN_BRIDGE_CANONICAL_DUPLICATE',
    IBAN_BRIDGE_CHAIN_TRANSFER = 'IBAN_BRIDGE_CHAIN_TRANSFER',
    IBAN_BRIDGE_TRANSFER = 'IBAN_BRIDGE_TRANSFER',
    P2P_FIAT_TRANSFER = 'P2P_FIAT_TRANSFER',
    REFUND = 'REFUND',
    TRANSFER_PAIR = 'TRANSFER_PAIR'
}
