export const RUNWAY_HISTORY_BAR_AREA_HEIGHT = 76;
export const RUNWAY_HISTORY_BAR_GAP = 2;
export const RUNWAY_HISTORY_CHART_WIDTH = 300;
export const RUNWAY_HISTORY_MIN_BAR_HEIGHT = 1.5;
export const RUNWAY_HISTORY_PLOT_TOP = 16;
export const RUNWAY_HISTORY_SPIKE_MULTIPLIER = 1.5;
