/* eslint-disable no-console */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as Schema from 'effect/Schema';

import { isDefined, isNotEmptyString } from '@rnw-community/shared';

import { normalizeIconSearchText } from '../src/@generic/utils/normalize-icon-search-text.util.ts';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const APP_DIR = resolve(SCRIPT_DIR, '..');
const REICON_DIR = join(APP_DIR, 'node_modules', 'reicon-react-native');
const ENUM_FILE = resolve(APP_DIR, '..', 'contracts', 'src', '@generic', 'enum', 'user-icon-name.enum.ts');
const CHUNKS_DIR = join(APP_DIR, 'src', '@generic', 'constant', 'icons');
const AGGREGATOR_FILE = join(APP_DIR, 'src', '@generic', 'constant', 'icons.constant.ts');
const SEARCH_INDEX_FILE = join(APP_DIR, 'src', '@generic', 'constant', 'icon-search-index.json');
const REICON_MAPPING_FILE = join(APP_DIR, 'src', '@generic', 'constant', 'user-icon-reicon-names.constant.json');
const EMOJIBASE_DIR = join(APP_DIR, 'node_modules', 'emojibase-data');
const KEYWORDS_DIR = join(SCRIPT_DIR, 'icon-keywords');
const PRESERVED_KEYWORDS_FILE = join(KEYWORDS_DIR, 'preserved-icon-keywords.json');
const EXTRA_TAGS_FILE = join(SCRIPT_DIR, 'icon-tags.json');
const EMOJI_LANGUAGES = ['en', 'uk', 'ru', 'de', 'es', 'fr'];
const EMOJI_COMPONENT_GROUP = 2;
const MIN_TRANSLATED_WORD_LENGTH = 3;
const PRESERVED_KEYWORDS_FILE_NAME = 'preserved-icon-keywords.json';
const INTERFACE_IMPORT_FROM_CHUNKS = '../../interface/reicon-module.interface';
const INTERFACE_IMPORT_FROM_AGGREGATOR = '../interface/reicon-module.interface';
const CHUNK_SIZE = 240;
const HEADER = '// Generated by scripts/generate-icons-constant.ts. Do not edit.';

interface IconEntryInterface {
    readonly componentName: string;
    readonly savedName: string;
}

const ReiconPackageSchema = Schema.Struct({
    name: Schema.String,
    exports: Schema.Record(Schema.String, Schema.Unknown)
});

const ReiconMappingSchema = Schema.Record(Schema.String, Schema.String);

const IconTagsSchema = Schema.Record(Schema.String, Schema.Array(Schema.String));

const WordTranslationsSchema = Schema.Record(Schema.String, Schema.Array(Schema.String));

const PreservedIconKeywordsSchema = Schema.Record(Schema.String, Schema.String);

const EmojibaseDataSchema = Schema.Array(
    Schema.Struct({
        emoji: Schema.String,
        label: Schema.String,
        tags: Schema.optional(Schema.Array(Schema.String)),
        group: Schema.optional(Schema.Number)
    })
);

const parseEnumValues = (enumFile: string): string[] => {
    const source = readFileSync(enumFile, 'utf8');
    const memberRegex = /^\s{4}([A-Za-z0-9]+) = '([A-Za-z0-9]+)',?\s*$/gm;
    const values: string[] = [];

    let match = memberRegex.exec(source);
    while (match !== null) {
        if (match[1] !== match[2]) {
            console.error(`Enum member/value mismatch: ${match[1]} = '${match[2]}'`);
            process.exit(1);
        }
        values.push(match[2]);
        match = memberRegex.exec(source);
    }

    if (values.length === 0) {
        console.error(`No enum members parsed from ${enumFile}`);
        process.exit(1);
    }

    return values;
};

const resolveIconSpecifierPrefix = (reiconDir: string): string => {
    const packageJson = Schema.decodeUnknownSync(ReiconPackageSchema)(JSON.parse(readFileSync(join(reiconDir, 'package.json'), 'utf8')));
    const wildcardKey = Object.keys(packageJson.exports).find(key => key.includes('icons') && key.endsWith('*'));

    if (!isDefined(wildcardKey)) {
        console.error(`reicon-react-native has no per-icon "./icons/*" export. Found: ${Object.keys(packageJson.exports).join(', ')}`);
        process.exit(1);
    }

    return `${packageJson.name}${wildcardKey.slice(1).replace(/\*$/, '')}`;
};

const buildReiconExportNames = (reiconDir: string): Set<string> => {
    const indexDeclaration = readFileSync(join(reiconDir, 'index.d.ts'), 'utf8');
    const exportRegex = /^export \{ ([A-Za-z0-9]+) \} from '\.\/icons\/[A-Za-z0-9]+\.js';$/gm;
    const exportNames = new Set<string>();

    let match = exportRegex.exec(indexDeclaration);
    while (match !== null) {
        exportNames.add(match[1]);
        match = exportRegex.exec(indexDeclaration);
    }

    if (exportNames.size === 0) {
        console.error(`No Reicon exports parsed from ${join(reiconDir, 'index.d.ts')}`);
        process.exit(1);
    }

    return exportNames;
};

const readReiconMapping = (mappingFile: string): Record<string, string> => {
    if (!existsSync(mappingFile)) {
        console.error(`Missing Reicon mapping file: ${mappingFile}`);
        process.exit(1);
    }

    return Schema.decodeUnknownSync(ReiconMappingSchema)(JSON.parse(readFileSync(mappingFile, 'utf8')));
};

const validateMappingCoverage = (
    enumValues: readonly string[],
    reiconMapping: Record<string, string>,
    reiconExportNames: ReadonlySet<string>
): void => {
    const enumNames = new Set(enumValues);
    const mappingNames = Object.keys(reiconMapping);
    const missingNames = enumValues.filter(value => !isDefined(reiconMapping[value]));
    const extraNames = mappingNames.filter(value => !enumNames.has(value)).sort();
    const missingExportNames = [
        ...new Set(Object.values(reiconMapping).filter(componentName => !reiconExportNames.has(componentName)))
    ].sort();

    if (missingNames.length > 0 || extraNames.length > 0 || missingExportNames.length > 0) {
        if (missingNames.length > 0) {
            console.error(`Missing Reicon mappings for ${missingNames.length} saved icon names: ${missingNames.join(', ')}`);
        }
        if (extraNames.length > 0) {
            console.error(`Reicon mapping has ${extraNames.length} names not present in UserIconNameEnum: ${extraNames.join(', ')}`);
        }
        if (missingExportNames.length > 0) {
            console.error(`Reicon mapping points at ${missingExportNames.length} missing exports: ${missingExportNames.join(', ')}`);
        }
        process.exit(1);
    }
};

const collectIconEntries = (enumValues: readonly string[], reiconMapping: Record<string, string>): IconEntryInterface[] =>
    enumValues
        .map(savedName => ({ savedName, componentName: reiconMapping[savedName] }))
        .sort((first, second) => (first.savedName < second.savedName ? -1 : first.savedName > second.savedName ? 1 : 0));

const renderChunk = (chunkIndex: number, chunk: readonly IconEntryInterface[], specifierPrefix: string): string =>
    [
        HEADER,
        "import { UserIconNameEnum } from '@budgie/contracts';",
        '',
        `import type { ReiconModuleInterface } from '${INTERFACE_IMPORT_FROM_CHUNKS}';`,
        '',
        `export const ICON_IMPORTS_CHUNK_${chunkIndex} = {`,
        chunk
            .map(
                (entry, index) =>
                    `    ${entry.savedName}: () => import('${specifierPrefix}${entry.componentName}')${index === chunk.length - 1 ? '' : ','}`
            )
            .join('\n'),
        '} satisfies Partial<Record<UserIconNameEnum, () => Promise<ReiconModuleInterface>>>;',
        ''
    ].join('\n');

const renderAggregator = (chunkBaseNames: readonly string[]): string =>
    [
        HEADER,
        "import { UserIconNameEnum } from '@budgie/contracts';",
        '',
        chunkBaseNames.map((baseName, index) => `import { ICON_IMPORTS_CHUNK_${index + 1} } from './icons/${baseName}';`).join('\n'),
        '',
        `import type { ReiconModuleInterface } from '${INTERFACE_IMPORT_FROM_AGGREGATOR}';`,
        '',
        'export const ICON_IMPORTS: Partial<Record<UserIconNameEnum, () => Promise<ReiconModuleInterface>>> = {',
        chunkBaseNames
            .map((_, index) => `    ...ICON_IMPORTS_CHUNK_${index + 1}${index === chunkBaseNames.length - 1 ? '' : ','}`)
            .join('\n'),
        '};',
        ''
    ].join('\n');

const toKebabName = (pascalName: string): string => pascalName.replaceAll(/(?<=[a-z0-9])(?=[A-Z])/gu, '-').toLowerCase();

const writeChunks = (iconEntries: readonly IconEntryInterface[], specifierPrefix: string): string[] => {
    rmSync(CHUNKS_DIR, { force: true, recursive: true });
    mkdirSync(CHUNKS_DIR, { recursive: true });

    const chunkBaseNames: string[] = [];
    for (let startIndex = 0; startIndex < iconEntries.length; startIndex += CHUNK_SIZE) {
        const chunk = iconEntries.slice(startIndex, startIndex + CHUNK_SIZE);
        const chunkIndex = chunkBaseNames.length + 1;
        const chunkBaseName = `icons-${toKebabName(chunk[0].savedName)}.constant`;
        chunkBaseNames.push(chunkBaseName);

        writeFileSync(join(CHUNKS_DIR, `${chunkBaseName}.ts`), renderChunk(chunkIndex, chunk, specifierPrefix));
    }

    return chunkBaseNames;
};

const joinKeywords = (phrases: readonly string[]): string =>
    [...new Set(phrases.map(normalizeIconSearchText).filter(phrase => phrase.length > 0 && !phrase.includes('|')))].join('|');

const joinKeywordSections = (namePhrases: readonly string[], otherPhrases: readonly string[]): string =>
    `${joinKeywords(namePhrases)}||${joinKeywords(otherPhrases)}`;

const readWordTranslations = (): Record<string, string[]>[] =>
    existsSync(KEYWORDS_DIR)
        ? readdirSync(KEYWORDS_DIR)
              .filter(fileName => fileName.endsWith('.json'))
              .filter(fileName => fileName !== PRESERVED_KEYWORDS_FILE_NAME)
              .sort()
              .map(fileName => {
                  console.log(`Using word translations ${fileName}`);

                  return Schema.decodeUnknownSync(WordTranslationsSchema)(JSON.parse(readFileSync(join(KEYWORDS_DIR, fileName), 'utf8')));
              })
        : [];

const readPreservedIconKeywords = (): Record<string, string> =>
    Schema.decodeUnknownSync(PreservedIconKeywordsSchema)(JSON.parse(readFileSync(PRESERVED_KEYWORDS_FILE, 'utf8')));

const splitKeywordSection = (section: string): string[] => section.split('|').filter(isNotEmptyString);

const buildIconKeywords = (savedName: string, existingKeywords: string | undefined, extraTags: readonly string[]): string => {
    const [existingNameKeywords, existingOtherKeywords = ''] = existingKeywords?.split('||') ?? [];
    const fallbackNameKeywords = savedName.replaceAll(/(?<=[a-z0-9])(?=[A-Z])/gu, ' ');
    const nameKeywords = splitKeywordSection(existingNameKeywords ?? fallbackNameKeywords);
    const otherKeywords = [...splitKeywordSection(existingOtherKeywords), ...extraTags];

    return joinKeywordSections(nameKeywords, otherKeywords);
};

const buildReiconIndex = (iconEntries: readonly IconEntryInterface[]): [string, string][] => {
    const extraTagsByName = Schema.decodeUnknownSync(IconTagsSchema)(JSON.parse(readFileSync(EXTRA_TAGS_FILE, 'utf8')));
    const preservedKeywordsByName = readPreservedIconKeywords();

    return iconEntries.map(entry => [
        entry.savedName,
        buildIconKeywords(entry.savedName, preservedKeywordsByName[entry.savedName], extraTagsByName[entry.savedName] ?? [])
    ]);
};

const buildWordIndex = (iconIndex: readonly [string, string][]): Record<string, string> => {
    const wordTranslations = readWordTranslations();
    const words = [...new Set(iconIndex.flatMap(([, keywords]) => keywords.split(/[^a-z]+/u)))].filter(
        word => word.length >= MIN_TRANSLATED_WORD_LENGTH
    );

    return Object.fromEntries(
        words
            .map(word => [word, joinKeywords(wordTranslations.flatMap(translations => translations[word] ?? []))])
            .filter(([, keywords]) => keywords.length > 0)
    );
};

const buildEmojiIndex = (): [string, string][] => {
    const itemsByEmoji = new Map<string, typeof EmojibaseDataSchema.Type>();

    for (const language of EMOJI_LANGUAGES) {
        for (const item of Schema.decodeUnknownSync(EmojibaseDataSchema)(
            JSON.parse(readFileSync(join(EMOJIBASE_DIR, language, 'data.json'), 'utf8'))
        )) {
            if (isDefined(item.group) && item.group !== EMOJI_COMPONENT_GROUP) {
                itemsByEmoji.set(item.emoji, [...(itemsByEmoji.get(item.emoji) ?? []), item]);
            }
        }
    }

    return [...itemsByEmoji].map(([emoji, items]) => [
        emoji,
        joinKeywordSections(
            items.map(item => item.label),
            items.flatMap(item => item.tags ?? [])
        )
    ]);
};

const main = (): void => {
    const enumValues = parseEnumValues(ENUM_FILE);
    const reiconExportNames = buildReiconExportNames(REICON_DIR);
    const reiconMapping = readReiconMapping(REICON_MAPPING_FILE);

    validateMappingCoverage(enumValues, reiconMapping, reiconExportNames);

    const iconEntries = collectIconEntries(enumValues, reiconMapping);
    const chunkBaseNames = writeChunks(iconEntries, resolveIconSpecifierPrefix(REICON_DIR));

    writeFileSync(AGGREGATOR_FILE, renderAggregator(chunkBaseNames));
    const reiconIndex = buildReiconIndex(iconEntries);

    writeFileSync(
        SEARCH_INDEX_FILE,
        `${JSON.stringify({ icons: [...reiconIndex, ...buildEmojiIndex()], translations: buildWordIndex(reiconIndex) }, null, 4)}\n`
    );

    console.log(`Generated ${chunkBaseNames.length} chunks covering ${iconEntries.length} mapped Reicon icons:`);
    for (const chunkBaseName of chunkBaseNames) {
        console.log(`  ${CHUNKS_DIR}/${chunkBaseName}.ts`);
    }
    console.log(`  ${AGGREGATOR_FILE}`);
    console.log(`  ${SEARCH_INDEX_FILE}`);
};

main();
