/* eslint-disable no-console */
// Generates lazily-importable lucide icon constants from UserIconNameEnum.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

import { isDefined } from '@rnw-community/shared';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const APP_DIR = resolve(SCRIPT_DIR, '..');
const LUCIDE_DIR = join(APP_DIR, 'node_modules', 'lucide-react-native');
const ENUM_FILE = resolve(APP_DIR, '..', 'contracts', 'src', '@generic', 'enum', 'user-icon-name.enum.ts');
const CHUNKS_DIR = join(APP_DIR, 'src', '@generic', 'constant', 'icons');
const AGGREGATOR_FILE = join(APP_DIR, 'src', '@generic', 'constant', 'icons.constant.ts');
const INTERFACE_IMPORT_FROM_CHUNKS = '../../interface/lucide-icon-module.interface';
const INTERFACE_IMPORT_FROM_AGGREGATOR = '../interface/lucide-icon-module.interface';
const CHUNK_SIZE = 240;
const HEADER = '// Generated by scripts/generate-icons-constant.ts. Do not edit.';

interface IconEntryInterface {
    readonly fileName: string;
    readonly pascalName: string;
}

const LucidePackageSchema = z.object({
    name: z.string(),
    exports: z.record(z.string(), z.unknown())
});

const parseEnumValues = (enumFile: string): string[] => {
    const source = readFileSync(enumFile, 'utf8');
    const memberRegex = /^\s{4}([A-Za-z0-9]+) = '([A-Za-z0-9]+)',?\s*$/gm;
    const values: string[] = [];

    let match = memberRegex.exec(source);
    while (match !== null) {
        if (match[1] !== match[2]) {
            console.error(`Enum member/value mismatch: ${match[1]} = '${match[2]}'`);
            process.exit(1);
        }
        values.push(match[2]);
        match = memberRegex.exec(source);
    }

    if (values.length === 0) {
        console.error(`No enum members parsed from ${enumFile}`);
        process.exit(1);
    }

    return values;
};

const resolveIconSpecifierPrefix = (lucideDir: string): string => {
    const packageJson = LucidePackageSchema.parse(JSON.parse(readFileSync(join(lucideDir, 'package.json'), 'utf8')));
    const wildcardKey = Object.keys(packageJson.exports).find(key => key.includes('icons') && key.endsWith('*'));

    if (!isDefined(wildcardKey)) {
        console.error(`lucide-react-native has no per-icon "./icons/*" export. Found: ${Object.keys(packageJson.exports).join(', ')}`);
        process.exit(1);
    }

    return `${packageJson.name}${wildcardKey.slice(1).replace(/\*$/, '')}`;
};

const buildIconFileNameByExportName = (lucideDir: string): Map<string, string> => {
    const barrel = readFileSync(join(lucideDir, 'dist', 'esm', 'lucide-react-native.mjs'), 'utf8');
    const reExportRegex = /^export \{([^}]+)\} from '\.\/icons\/([a-z0-9-]+)\.mjs';$/gm;
    const aliasRegex = /^default as ([A-Za-z0-9]+)$/;
    const fileNameByExportName = new Map<string, string>();

    let reExportMatch = reExportRegex.exec(barrel);
    while (reExportMatch !== null) {
        for (const exportItem of reExportMatch[1].split(',')) {
            const aliasMatch = aliasRegex.exec(exportItem.trim());
            if (aliasMatch !== null) {
                fileNameByExportName.set(aliasMatch[1], reExportMatch[2]);
            }
        }
        reExportMatch = reExportRegex.exec(barrel);
    }

    return fileNameByExportName;
};

const collectIconEntries = (enumValues: readonly string[], fileNameByExportName: ReadonlyMap<string, string>): IconEntryInterface[] => {
    const entries: IconEntryInterface[] = [];

    for (const value of enumValues) {
        const fileName = fileNameByExportName.get(value);
        if (isDefined(fileName)) {
            entries.push({ fileName, pascalName: value });
        }
    }

    return entries.sort((first, second) => (first.fileName < second.fileName ? -1 : first.fileName > second.fileName ? 1 : 0));
};

const renderChunk = (chunkIndex: number, chunk: readonly IconEntryInterface[], specifierPrefix: string): string =>
    [
        HEADER,
        "import { UserIconNameEnum } from '@budgie/contracts';",
        '',
        `import type { LucideIconModuleInterface } from '${INTERFACE_IMPORT_FROM_CHUNKS}';`,
        '',
        `export const ICON_IMPORTS_CHUNK_${chunkIndex} = {`,
        chunk.map(entry => `    ${entry.pascalName}: () => import('${specifierPrefix}${entry.fileName}'),`).join('\n'),
        '} satisfies Partial<Record<UserIconNameEnum, () => Promise<LucideIconModuleInterface>>>;',
        ''
    ].join('\n');

const renderAggregator = (chunkBaseNames: readonly string[]): string =>
    [
        HEADER,
        "import { UserIconNameEnum } from '@budgie/contracts';",
        '',
        chunkBaseNames.map((baseName, index) => `import { ICON_IMPORTS_CHUNK_${index + 1} } from './icons/${baseName}';`).join('\n'),
        '',
        `import type { LucideIconModuleInterface } from '${INTERFACE_IMPORT_FROM_AGGREGATOR}';`,
        '',
        'export const ICON_IMPORTS: Partial<Record<UserIconNameEnum, () => Promise<LucideIconModuleInterface>>> = {',
        chunkBaseNames.map((_, index) => `    ...ICON_IMPORTS_CHUNK_${index + 1},`).join('\n'),
        '};',
        ''
    ].join('\n');

const writeChunks = (iconEntries: readonly IconEntryInterface[], specifierPrefix: string): string[] => {
    rmSync(CHUNKS_DIR, { force: true, recursive: true });
    mkdirSync(CHUNKS_DIR, { recursive: true });

    const chunkBaseNames: string[] = [];
    for (let startIndex = 0; startIndex < iconEntries.length; startIndex += CHUNK_SIZE) {
        const chunk = iconEntries.slice(startIndex, startIndex + CHUNK_SIZE);
        const chunkIndex = chunkBaseNames.length + 1;
        const chunkBaseName = `icons-${chunk[0].fileName}.constant`;
        chunkBaseNames.push(chunkBaseName);

        writeFileSync(join(CHUNKS_DIR, `${chunkBaseName}.ts`), renderChunk(chunkIndex, chunk, specifierPrefix));
    }

    return chunkBaseNames;
};

const main = (): void => {
    const enumValues = parseEnumValues(ENUM_FILE);
    const specifierPrefix = resolveIconSpecifierPrefix(LUCIDE_DIR);
    const fileNameByExportName = buildIconFileNameByExportName(LUCIDE_DIR);
    const resolvedValues = enumValues.filter(value => fileNameByExportName.has(value));
    const missingValues = enumValues.filter(value => !fileNameByExportName.has(value));

    if (missingValues.length > 0) {
        console.log(`Unresolvable icon names (${missingValues.length}/${enumValues.length}), they render the fallback icon at runtime:`);
        for (const value of missingValues) {
            console.log(`  ${value}`);
        }
    }

    const iconEntries = collectIconEntries(resolvedValues, fileNameByExportName);
    const chunkBaseNames = writeChunks(iconEntries, specifierPrefix);

    writeFileSync(AGGREGATOR_FILE, renderAggregator(chunkBaseNames));

    console.log(`Generated ${chunkBaseNames.length} chunks covering ${iconEntries.length} icons:`);
    for (const chunkBaseName of chunkBaseNames) {
        console.log(`  ${CHUNKS_DIR}/${chunkBaseName}.ts`);
    }
    console.log(`  ${AGGREGATOR_FILE}`);
};

main();
