export const EMBEDDING_SIMILARITY_THRESHOLD = 0.75;
export const EMBEDDING_RECENT_TITLE_COUNT = 5;
export const EMBEDDING_BATCH_LIMIT = 20;
export const EMBEDDING_CATEGORY_SUGGESTION_LIMIT = 3;
export const EMBEDDING_TAG_SUGGESTION_LIMIT = 3;
