import {
    AccountBalanceRepository,
    AccountRepository,
    BankSyncRepository,
    CategoryRepository,
    CommentEmbeddingRepository,
    ExchangeRateRepository,
    HistoricalExchangeRateRepository,
    InstrumentRepository,
    MccCategoryRepository,
    MerchantEmbeddingRepository,
    RefundPairRepository,
    RuleActionRepository,
    RuleConditionRepository,
    RuleRepository,
    SettingsRepository,
    StatisticsRepository,
    TagRepository,
    TransactionEmbeddingRepository,
    TransactionEntryRepository,
    TransactionPatternRepository,
    TransactionRepository,
    TransactionRuleRepository,
    TransactionTagsRepository,
    TransferPairRepository
} from '@budgie/contracts';
import type { DB } from '@budgie/contracts';

export const createTestRepositories = (db: DB) => ({
    tagRepository: new TagRepository(db),
    accountRepository: new AccountRepository(db),
    settingsRepository: new SettingsRepository(db),
    categoryRepository: new CategoryRepository(db),
    instrumentRepository: new InstrumentRepository(db),
    exchangeRateRepository: new ExchangeRateRepository(db),
    historicalExchangeRateRepository: new HistoricalExchangeRateRepository(db),
    accountBalanceRepository: new AccountBalanceRepository(db),
    bankSyncRepository: new BankSyncRepository(db),
    ruleRepository: new RuleRepository(db),
    ruleActionRepository: new RuleActionRepository(db),
    ruleConditionRepository: new RuleConditionRepository(db),
    mccCategoryRepository: new MccCategoryRepository(db),
    statisticsRepository: new StatisticsRepository(db),
    transactionEmbeddingRepository: new TransactionEmbeddingRepository(db),
    transactionEntryRepository: new TransactionEntryRepository(db),
    transactionPatternRepository: new TransactionPatternRepository(db),
    transactionRepository: new TransactionRepository(db),
    transactionRuleRepository: new TransactionRuleRepository(db),
    transactionTagsRepository: new TransactionTagsRepository(db),
    merchantEmbeddingRepository: new MerchantEmbeddingRepository(db),
    commentEmbeddingRepository: new CommentEmbeddingRepository(db),
    transferPairRepository: new TransferPairRepository(db),
    refundPairRepository: new RefundPairRepository(db)
});
