export const RUNWAY_IRREGULAR_CV_THRESHOLD = 0.6;
export const RUNWAY_IRREGULAR_CONCENTRATION_THRESHOLD = 0.75;
export const RUNWAY_MAX_MONTHS = 12;
export const RUNWAY_DRIVER_MIN_BURN_SHARE = 0.03;
export const RUNWAY_WINDOW_MONTHS = 6;
