export const EMBEDDING_RECENT_TITLE_COUNT = 5;
export const EMBEDDING_BATCH_LIMIT = 20;
export const EMBEDDING_CATEGORY_SUGGESTION_LIMIT = 3;
export const EMBEDDING_TAG_SUGGESTION_LIMIT = 3;
export const EMBEDDING_VEC_SEARCH_LIMIT = 10;
export const EMBEDDING_VEC_PATTERN_SEARCH_LIMIT = 5;
export const EMBEDDING_CONTEXT_MAX_LENGTH = 1000;
