export const EMBEDDING_RECENT_TITLE_COUNT = 10;
export const EMBEDDING_BATCH_LIMIT = 50;
export const EMBEDDING_CATEGORY_SUGGESTION_LIMIT = 3;
export const EMBEDDING_TAG_SUGGESTION_LIMIT = 3;
export const EMBEDDING_VEC_SEARCH_LIMIT = 10;
export const EMBEDDING_VEC_OVERSAMPLE_LIMIT = 50;
export const EMBEDDING_CONTEXT_MAX_LENGTH = 1000;
export const EMBEDDING_VEC_DISTANCE_THRESHOLD = 0.9;
