export const REPEATED_TRANSACTION_TIME_WINDOW_MINUTES = 60;
export const REPEATED_TRANSACTION_AMOUNT_TOLERANCE_PERCENT = 0.15;
export const REPEATED_TRANSACTION_DEFAULT_LIMIT = 5;
export const MINUTES_IN_DAY = 24 * 60 - 1;
