export enum CategorySourceEnum {
    USER = 'USER',
    MCC_DEFAULT = 'MCC_DEFAULT',
    RULE = 'RULE',
    AI = 'AI',
    INBOX = 'INBOX',
    FEE = 'FEE',
    DEBT_SETTLEMENT = 'DEBT_SETTLEMENT',
    MANUAL_EXPENSE_DUPLICATE = 'MANUAL_EXPENSE_DUPLICATE'
}
