/* Generated by `pnpm --filter @budgie-at/landing media:manifest` from `packages/landing/public/media`. Do not edit by hand. */
import type { MediaAssetType } from '../interface/media-asset.type';

export const MEDIA_MANIFEST: readonly MediaAssetType[] = [];
