/* Generated by `pnpm --filter @budgie-at/landing media:manifest` from `packages/landing/public/media`. Do not edit by hand. */
import type { MediaAssetInterface } from '../interface/media-asset.interface';

export const MEDIA_MANIFEST: readonly MediaAssetInterface[] = [];
