/* Generated by `pnpm --filter @budgie-at/landing media:manifest` from `packages/landing/public/media`. Do not edit by hand. */
import { MediaKindEnum } from '../enum/media-kind.enum';
import { MediaThemeEnum } from '../enum/media-theme.enum';

import type { MediaManifestEntryInterface } from '../interface/media-manifest-entry.interface';

export const MEDIA_MANIFEST: readonly MediaManifestEntryInterface[] = [
    {
        slug: 'account-management',
        scene: 'account-management-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'account-management',
        scene: 'account-management-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'account-management',
        scene: 'account-management-3',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'account-transfers',
        scene: 'account-transfers-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'account-transfers',
        scene: 'account-transfers-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'ai-auto-categorization',
        scene: 'ai-auto-categorization-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'ai-auto-categorization',
        scene: 'ai-auto-categorization-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'ai-category-translation',
        scene: 'ai-category-translation-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'ai-tag-suggestions',
        scene: 'ai-tag-suggestions-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'ai-transaction-suggestions',
        scene: 'ai-transaction-suggestions-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'bank-fee-tracking',
        scene: 'bank-fee-tracking-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'bank-fee-tracking',
        scene: 'bank-fee-tracking-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'bank-resync-window',
        scene: 'bank-resync-window-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'binance-sync',
        scene: 'binance-sync-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'budget-planning',
        scene: 'budget-planning-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'bulk-categorize-transactions',
        scene: 'bulk-categorize-transactions-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'bulk-categorize-transactions',
        scene: 'bulk-categorize-transactions-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'categorization-rules',
        scene: 'categorization-rules-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'categorization-rules',
        scene: 'categorization-rules-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'convert-to-refund',
        scene: 'convert-to-refund-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'convert-to-refund',
        scene: 'convert-to-refund-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'convert-to-transfer',
        scene: 'convert-to-transfer-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'crypto-investment-tracking',
        scene: 'crypto-investment-tracking-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'crypto-investment-tracking',
        scene: 'crypto-investment-tracking-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'crypto-investment-tracking',
        scene: 'crypto-investment-tracking-3',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'csv-import',
        scene: 'csv-import-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'csv-import',
        scene: 'csv-import-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'custom-categories',
        scene: 'custom-categories-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'custom-categories',
        scene: 'custom-categories-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'custom-categories',
        scene: 'custom-categories-3',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'database-backup',
        scene: 'database-backup-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'date-filter-presets',
        scene: 'date-filter-presets-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'date-filter-presets',
        scene: 'date-filter-presets-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'debt-tracking',
        scene: 'debt-tracking-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'debt-tracking',
        scene: 'debt-tracking-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'debt-tracking',
        scene: 'debt-tracking-3',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'deposit-tracking',
        scene: 'deposit-tracking-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'deposit-tracking',
        scene: 'deposit-tracking-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'erste-bank-pdf-import',
        scene: 'erste-bank-pdf-import-1',
        kind: MediaKindEnum.STILL,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'erste-bank-pdf-import',
        scene: 'erste-bank-pdf-import-1',
        kind: MediaKindEnum.STILL,
        locales: ['fr'],
        themes: [MediaThemeEnum.LIGHT]
    },
    {
        slug: 'expense-tracking',
        scene: 'expense-tracking-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'expense-tracking',
        scene: 'expense-tracking-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'home-hero',
        scene: 'home-hero-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'home-hero',
        scene: 'home-hero-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'home-hero',
        scene: 'home-hero-clip-1',
        kind: MediaKindEnum.MOTION,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'mcc-auto-category',
        scene: 'mcc-auto-category-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'mcc-auto-category',
        scene: 'mcc-auto-category-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'monobank-sync',
        scene: 'monobank-sync-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'monobank-sync',
        scene: 'monobank-sync-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'monobank-sync',
        scene: 'monobank-sync-clip-1',
        kind: MediaKindEnum.MOTION,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'multi-currency',
        scene: 'multi-currency-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'multi-language-app',
        scene: 'multi-language-app-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'net-worth-tracker',
        scene: 'net-worth-tracker-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'net-worth-tracker',
        scene: 'net-worth-tracker-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'no-bank-login-budget-app',
        scene: 'no-bank-login-budget-app-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'offline-first-expense-tracker',
        scene: 'offline-first-expense-tracker-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'offline-first-expense-tracker',
        scene: 'offline-first-expense-tracker-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'on-device-ai-budget-app',
        scene: 'on-device-ai-budget-app-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'open-source-budget-app-mobile',
        scene: 'open-source-budget-app-mobile-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'pin-app-lock',
        scene: 'pin-app-lock-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'pin-app-lock',
        scene: 'pin-app-lock-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'primary-tag',
        scene: 'primary-tag-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'privatbank-import',
        scene: 'privatbank-import-1',
        kind: MediaKindEnum.STILL,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'privatbank-import',
        scene: 'privatbank-import-2',
        kind: MediaKindEnum.STILL,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'private-budget-app-alternative',
        scene: 'private-budget-app-alternative-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'recurring-payments-calendar',
        scene: 'recurring-payments-calendar-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'recurring-payments-calendar',
        scene: 'recurring-payments-calendar-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'runway',
        scene: 'runway-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'runway',
        scene: 'runway-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'runway',
        scene: 'runway-3',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'runway',
        scene: 'runway-4',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'runway',
        scene: 'runway-clip-1',
        kind: MediaKindEnum.MOTION,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'screenshot-protection',
        scene: 'screenshot-protection-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'spending-analytics',
        scene: 'spending-analytics-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'spending-analytics',
        scene: 'spending-analytics-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'spending-analytics',
        scene: 'spending-analytics-clip-1',
        kind: MediaKindEnum.MOTION,
        locales: ['en'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'split-transactions',
        scene: 'split-transactions-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'split-transactions',
        scene: 'split-transactions-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'statistics-tags-tab',
        scene: 'statistics-tags-tab-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'subscription-free-budget-app',
        scene: 'subscription-free-budget-app-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'transaction-long-press-menu',
        scene: 'transaction-long-press-menu-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'transaction-tags',
        scene: 'transaction-tags-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'transaction-tags',
        scene: 'transaction-tags-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'transfer-pair-detection',
        scene: 'transfer-pair-detection-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'transfer-pair-detection',
        scene: 'transfer-pair-detection-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'uncategorized-transactions',
        scene: 'uncategorized-transactions-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'uncategorized-transactions',
        scene: 'uncategorized-transactions-2',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    },
    {
        slug: 'voice-transaction-entry',
        scene: 'voice-transaction-entry-1',
        kind: MediaKindEnum.STILL,
        locales: ['de', 'en', 'es', 'fr', 'uk'],
        themes: [MediaThemeEnum.DARK, MediaThemeEnum.LIGHT]
    }
];
