import { FEATURE_METADATA as ACCOUNT_MANAGEMENT_FEATURE_METADATA } from './account-management/metadata';
import { FEATURE_METADATA as ACCOUNT_TRANSFERS_FEATURE_METADATA } from './account-transfers/metadata';
import { FEATURE_METADATA as AI_AUTO_CATEGORIZATION_FEATURE_METADATA } from './ai-auto-categorization/metadata';
import { FEATURE_METADATA as AI_MERCHANT_TRANSLATION_FEATURE_METADATA } from './ai-merchant-translation/metadata';
import { FEATURE_METADATA as AI_TAG_SUGGESTIONS_FEATURE_METADATA } from './ai-tag-suggestions/metadata';
import { FEATURE_METADATA as AI_TRANSACTION_SUGGESTIONS_FEATURE_METADATA } from './ai-transaction-suggestions/metadata';
import { FEATURE_METADATA as BANK_RESYNC_WINDOW_FEATURE_METADATA } from './bank-resync-window/metadata';
import { FEATURE_METADATA as BIOMETRIC_AUTHENTICATION_FEATURE_METADATA } from './biometric-authentication/metadata';
import { FEATURE_METADATA as CONVERT_TO_REFUND_FEATURE_METADATA } from './convert-to-refund/metadata';
import { FEATURE_METADATA as CONVERT_TO_TRANSFER_FEATURE_METADATA } from './convert-to-transfer/metadata';
import { FEATURE_METADATA as CRYPTO_INVESTMENT_TRACKING_FEATURE_METADATA } from './crypto-investment-tracking/metadata';
import { FEATURE_METADATA as CSV_IMPORT_FEATURE_METADATA } from './csv-import/metadata';
import { FEATURE_METADATA as CUSTOM_CATEGORIES_FEATURE_METADATA } from './custom-categories/metadata';
import { FEATURE_METADATA as DARK_MODE_FEATURE_METADATA } from './dark-mode/metadata';
import { FEATURE_METADATA as DATA_EXPORT_FEATURE_METADATA } from './data-export/metadata';
import { FEATURE_METADATA as DATABASE_BACKUP_FEATURE_METADATA } from './database-backup/metadata';
import { FEATURE_METADATA as DATE_FILTER_PRESETS_FEATURE_METADATA } from './date-filter-presets/metadata';
import { FEATURE_METADATA as DEBT_TRACKING_FEATURE_METADATA } from './debt-tracking/metadata';
import { FEATURE_METADATA as ERSTE_BANK_PDF_IMPORT_FEATURE_METADATA } from './erste-bank-pdf-import/metadata';
import { FEATURE_METADATA as EXPENSE_TRACKING_FEATURE_METADATA } from './expense-tracking/metadata';
import { FEATURE_METADATA as MCC_AUTO_CATEGORY_FEATURE_METADATA } from './mcc-auto-category/metadata';
import { FEATURE_METADATA as MONOBANK_SYNC_FEATURE_METADATA } from './monobank-sync/metadata';
import { FEATURE_METADATA as MULTI_CURRENCY_FEATURE_METADATA } from './multi-currency/metadata';
import { FEATURE_METADATA as MULTI_LANGUAGE_APP_FEATURE_METADATA } from './multi-language-app/metadata';
import { FEATURE_METADATA as NET_WORTH_TRACKER_FEATURE_METADATA } from './net-worth-tracker/metadata';
import { FEATURE_METADATA as NO_BANK_LOGIN_BUDGET_APP_FEATURE_METADATA } from './no-bank-login-budget-app/metadata';
import { FEATURE_METADATA as OFFLINE_FIRST_EXPENSE_TRACKER_FEATURE_METADATA } from './offline-first-expense-tracker/metadata';
import { FEATURE_METADATA as ON_DEVICE_AI_BUDGET_APP_FEATURE_METADATA } from './on-device-ai-budget-app/metadata';
import { FEATURE_METADATA as OPEN_SOURCE_BUDGET_APP_MOBILE_FEATURE_METADATA } from './open-source-budget-app-mobile/metadata';
import { FEATURE_METADATA as PIN_APP_LOCK_FEATURE_METADATA } from './pin-app-lock/metadata';
import { FEATURE_METADATA as PRIMARY_TAG_FEATURE_METADATA } from './primary-tag/metadata';
import { FEATURE_METADATA as PRIVATBANK_IMPORT_FEATURE_METADATA } from './privatbank-import/metadata';
import { FEATURE_METADATA as PRIVATE_BUDGET_APP_ALTERNATIVE_FEATURE_METADATA } from './private-budget-app-alternative/metadata';
import { FEATURE_METADATA as RECURRING_PAYMENTS_CALENDAR_FEATURE_METADATA } from './recurring-payments-calendar/metadata';
import { FEATURE_METADATA as SCREENSHOT_PROTECTION_FEATURE_METADATA } from './screenshot-protection/metadata';
import { FEATURE_METADATA as SELF_HOSTED_FINANCE_APP_MOBILE_FEATURE_METADATA } from './self-hosted-finance-app-mobile/metadata';
import { FEATURE_METADATA as SPENDING_ANALYTICS_FEATURE_METADATA } from './spending-analytics/metadata';
import { FEATURE_METADATA as SPLIT_TRANSACTIONS_FEATURE_METADATA } from './split-transactions/metadata';
import { FEATURE_METADATA as STATISTICS_TAGS_TAB_FEATURE_METADATA } from './statistics-tags-tab/metadata';
import { FEATURE_METADATA as SUBSCRIPTION_FREE_BUDGET_APP_FEATURE_METADATA } from './subscription-free-budget-app/metadata';
import { FEATURE_METADATA as TAG_ANALYTICS_FEATURE_METADATA } from './tag-analytics/metadata';
import { FEATURE_METADATA as TRANSACTION_LONG_PRESS_MENU_FEATURE_METADATA } from './transaction-long-press-menu/metadata';
import { FEATURE_METADATA as TRANSACTION_TAGS_FEATURE_METADATA } from './transaction-tags/metadata';
import { FEATURE_METADATA as TRANSFER_PAIR_DETECTION_FEATURE_METADATA } from './transfer-pair-detection/metadata';
import { FEATURE_METADATA as UNCATEGORIZED_TRANSACTIONS_FEATURE_METADATA } from './uncategorized-transactions/metadata';
import { FEATURE_METADATA as VOICE_TRANSACTION_ENTRY_FEATURE_METADATA } from './voice-transaction-entry/metadata';

export const FEATURE_METADATA_LIST = [
    OFFLINE_FIRST_EXPENSE_TRACKER_FEATURE_METADATA,
    MONOBANK_SYNC_FEATURE_METADATA,
    AI_AUTO_CATEGORIZATION_FEATURE_METADATA,
    AI_TRANSACTION_SUGGESTIONS_FEATURE_METADATA,
    AI_TAG_SUGGESTIONS_FEATURE_METADATA,
    VOICE_TRANSACTION_ENTRY_FEATURE_METADATA,
    NET_WORTH_TRACKER_FEATURE_METADATA,
    EXPENSE_TRACKING_FEATURE_METADATA,
    TRANSACTION_LONG_PRESS_MENU_FEATURE_METADATA,
    ACCOUNT_MANAGEMENT_FEATURE_METADATA,
    SPENDING_ANALYTICS_FEATURE_METADATA,
    UNCATEGORIZED_TRANSACTIONS_FEATURE_METADATA,
    CUSTOM_CATEGORIES_FEATURE_METADATA,
    TRANSACTION_TAGS_FEATURE_METADATA,
    ACCOUNT_TRANSFERS_FEATURE_METADATA,
    CSV_IMPORT_FEATURE_METADATA,
    ERSTE_BANK_PDF_IMPORT_FEATURE_METADATA,
    PRIVATBANK_IMPORT_FEATURE_METADATA,
    PIN_APP_LOCK_FEATURE_METADATA,
    BIOMETRIC_AUTHENTICATION_FEATURE_METADATA,
    DATA_EXPORT_FEATURE_METADATA,
    DATABASE_BACKUP_FEATURE_METADATA,
    DATE_FILTER_PRESETS_FEATURE_METADATA,
    RECURRING_PAYMENTS_CALENDAR_FEATURE_METADATA,
    TRANSFER_PAIR_DETECTION_FEATURE_METADATA,
    SPLIT_TRANSACTIONS_FEATURE_METADATA,
    AI_MERCHANT_TRANSLATION_FEATURE_METADATA,
    MULTI_CURRENCY_FEATURE_METADATA,
    DEBT_TRACKING_FEATURE_METADATA,
    BANK_RESYNC_WINDOW_FEATURE_METADATA,
    MCC_AUTO_CATEGORY_FEATURE_METADATA,
    TAG_ANALYTICS_FEATURE_METADATA,
    STATISTICS_TAGS_TAB_FEATURE_METADATA,
    CONVERT_TO_TRANSFER_FEATURE_METADATA,
    CONVERT_TO_REFUND_FEATURE_METADATA,
    SCREENSHOT_PROTECTION_FEATURE_METADATA,
    CRYPTO_INVESTMENT_TRACKING_FEATURE_METADATA,
    DARK_MODE_FEATURE_METADATA,
    MULTI_LANGUAGE_APP_FEATURE_METADATA,
    PRIMARY_TAG_FEATURE_METADATA,
    PRIVATE_BUDGET_APP_ALTERNATIVE_FEATURE_METADATA,
    SUBSCRIPTION_FREE_BUDGET_APP_FEATURE_METADATA,
    NO_BANK_LOGIN_BUDGET_APP_FEATURE_METADATA,
    OPEN_SOURCE_BUDGET_APP_MOBILE_FEATURE_METADATA,
    SELF_HOSTED_FINANCE_APP_MOBILE_FEATURE_METADATA,
    ON_DEVICE_AI_BUDGET_APP_FEATURE_METADATA
];
