import { PRECISION } from '../../@generic/constant/precision.constant';

const SAME_BANK_HINTED_FEE_TRANSFER_TIME_WINDOW_MINUTES = 2;

export const TRANSFER_PAIR_SAME_BANK_HINTED_FEE_TIME_WINDOW_SECONDS = SAME_BANK_HINTED_FEE_TRANSFER_TIME_WINDOW_MINUTES * 60;

export const TRANSFER_PAIR_SAME_BANK_HINTED_FEE_MAX_AMOUNT_DELTA = 500 * PRECISION;

export const TRANSFER_PAIR_SAME_BANK_HINTED_FEE_MAX_AMOUNT_DELTA_RATIO = 0.05;

const INTERBANK_HINTED_FEE_TRANSFER_TIME_WINDOW_HOURS = 2;

export const TRANSFER_PAIR_INTERBANK_HINTED_FEE_TIME_WINDOW_SECONDS = INTERBANK_HINTED_FEE_TRANSFER_TIME_WINDOW_HOURS * 60 * 60;

export const TRANSFER_PAIR_INTERBANK_HINTED_FEE_MAX_AMOUNT_DELTA = 500 * PRECISION;

const INTERBANK_HINTED_FEE_TRANSFER_MAX_AMOUNT_DELTA_PERCENT = 2;

const INTERBANK_HINTED_FEE_TRANSFER_PERCENT_DIVISOR = 100;

export const TRANSFER_PAIR_INTERBANK_HINTED_FEE_MAX_AMOUNT_DELTA_RATIO =
    INTERBANK_HINTED_FEE_TRANSFER_MAX_AMOUNT_DELTA_PERCENT / INTERBANK_HINTED_FEE_TRANSFER_PERCENT_DIVISOR;

export const TRANSFER_PAIR_ACCOUNT_HINT_SUFFIX_LENGTH = 4;
