const P2P_FIAT_TRANSFER_TIME_WINDOW_MINUTES = 60;

export const TRANSFER_PAIR_P2P_FIAT_TIME_WINDOW_SECONDS = P2P_FIAT_TRANSFER_TIME_WINDOW_MINUTES * 60;

export const TRANSFER_PAIR_P2P_FIAT_RATE_TOLERANCE = 0.1;

export const BINANCE_C2C_EXTERNAL_ID_PREFIX = 'binance:c2c:';
