export enum BankSyncBatchReasonEnum {
    PAGINATING = 'PAGINATING',
    STREAK_EXTENDING = 'STREAK_EXTENDING',
    STREAK_RESET = 'STREAK_RESET',
    DORMANCY_BOUNDARY = 'DORMANCY_BOUNDARY',
    CAUGHT_UP = 'CAUGHT_UP'
}
