name: Deploy production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  EXPO_APPLE_TEAM_TYPE: INDIVIDUAL
  EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Git user
        uses: fregante/setup-git-user@v2.0.1

      - name: Install dependencies
        run: yarn install

      - name: Publish a release
        run: yarn release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true

  web-deploy:
    name: Install and build Web
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: yarn install

      - name: Build expo web
        run: npx expo export --platform=web

      - name: Deploy to Vercel
        working-directory: ./dist
        run: |
          echo "!node_modules" > .vercelignore
          cp ../vercel.json .
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

  expo-build:
    name: Build and Deploy IOS and Android
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ASC API Key file creation
        uses: MobileDevOps/secret-to-file-action@v1.0.0
        with:
          base64-encoded-secret: ${{ secrets.EXPO_API_KEY }}
          filename: "asc_api_key.p8"

      - name: ASC API Key file creation
        uses: MobileDevOps/secret-to-file-action@v1.0.0
        with:
          base64-encoded-secret: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          filename: "google-service-account.json"

      - name: Install dependencies
        run: yarn install

      - name: Build on EAS
        run: eas build --platform all --non-interactive --auto-submit --no-wait
