name: Deploy production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Install and build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: yarn install

      - name: Build expo web
        run: npx expo export --platform=web

      - name: Deploy to Vercel
        working-directory: ./dist
        run: |
          cd dist
          echo "!node_modules" > .vercelignore
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

  ios-and-android-deploy:
    name: Build and Deploy IOS and Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build on EAS
        run: eas build --platform ios --non-interactive

      - name: Submit IOS
        run: eas submit --platform ios --latest --non-interactive
