name: Build Development build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dev-release:
    name: iOS development build and release
    permissions:
      contents: write
    uses: rnw-community/mobile-ci/.github/workflows/native-dev-release.yml@a252f5df9e911387598b2b01b0bb28bc40057ce0 # v1.2.0
    with:
      enable-ios: true
      enable-android: false
      ios-runner-labels: '["self-hosted","macOS","ARM64","macos-tartelet"]'
      app-dir: packages/app
      tag-prefix: dev
      keep-releases: 5
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      ASC_API_KEY: ${{ secrets.EXPO_IOS_ASC_API_KEY }}
      EAS_EXTRA_ENV: EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_PASSWORD }}
