name: Build Development build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dev-release:
    name: iOS development build and release
    permissions:
      contents: write
    uses: rnw-community/mobile-ci/.github/workflows/native-dev-release.yml@0eadcb345bc704b1ccc8e9965634af1ff3d2e25e # v1.1.0
    with:
      enable-ios: true
      enable-android: false
      ios-runner-labels: '["self-hosted","macOS","ARM64","macos-tartelet"]'
      app-dir: packages/app
      tag-prefix: dev
      keep-releases: 5
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      ASC_API_KEY: ${{ secrets.EXPO_IOS_ASC_API_KEY }}
